### ISSUE TITLE
[SOLVED] Issues 1521/717

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/Sponge#373] opened 2015-10-16 16:37 UTC
http://pastebin.com/embed_js.php?i=LvXddzVq"></script>

Items cannot be picked up and server seems to run in a sort of loop. When I want to pick up an item it makes the respective sound, but no items land in the inventory. Instead it makes a continuous noise as if constantly picking up items. 

Now it gets interesting. When I leave the spot where I was to pick up the item the sound stops - when I approach the spot again it starts again. 
This is decidedly weird

**Comment by Zidane** [comment] 2015-10-16 16:46
Pastie link is invalid.

**Comment by Billabonga** [comment] 2015-10-16 16:54
http://pastebin.com/embed_js.php?i=CEYJHFb5"></script>

**Comment by liach** [comment] 2015-10-16 17:11
http://pastebin.com/LvXddzVq/

Is this the actual log?

**Comment by Billabonga** [comment] 2015-10-16 17:12
Yep

**Comment by liach** [comment] 2015-10-16 17:15
Looks like that [craftbook] (https://github.com/sk89q/CraftBook/) used an out-of-date spongeapi. Recently there was big factors on api, so you should ask @me4502 to update craftbook's spongeapi.

**Comment by Billabonga** [comment] 2015-10-16 17:17
OK

**Comment by simon816** [comment] 2015-10-16 17:55
Well no that's impossible since `com.sk89q.craftbook` wouldn't appear in the log file if that were the case.
Either you didn't remove the plugin or it's a different issue. Please paste a log without any plugins

**Comment by Billabonga** [comment] 2015-10-16 18:00
http://pastebin.com/embed_js.php?i=GwAD85Wz"></script>

**Comment by simon816** [comment] 2015-10-16 18:07
I don't see an error there. Looks like you just loaded Sponge on the client, opened a single player world and exited. Is there anything I'm missing?

**Comment by Billabonga** [comment] 2015-10-16 18:09
That's right but as I said the problem persists

**Comment by simon816** [comment] 2015-10-16 18:33
OK I forgot what this issue was about I was looking for a crash

I can confirm this issue. It seems to be caused by @bloodmc's most recent commit, a9815489375cd618a6470216a88258da2d57c84e
The previous build (716) doesn't have this issue

**Comment by Billabonga** [comment] 2015-10-16 18:34
Ok I'll go back to 716 then?

**Comment by Billabonga** [comment] 2015-10-16 18:42
http://pastebin.com/u1E0PsCy

same problem with 716 I'm afraid

**Comment by Billabonga** [comment] 2015-10-16 18:52
Yep, thanks a lot guys

**Comment by bloodmc** [comment] 2015-10-16 19:54
Fixed in commit https://github.com/SpongePowered/Sponge/commit/b52f78ff15d6a4f081230461b782e606f417f4df

**Closed by bloodmc** 2015-10-16 19:54 UTC
