### ISSUE TITLE
The 'DestructEntityEvent' event is not triggered when the boat is broken by the player.

### ISSUE THREAD

**Issue by TheNullablePrototype** [SpongePowered/Sponge#1819] opened 2018-02-27 19:26 UTC
**I am currently running**

- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43
- SpongeForge: 1.12.2-2611-7.1.0-BETA-2925
- Minecraft Forge: 14.23.1.2604
- Java version:  1.8_152
- Operating System: Windows 10

- Plugins/Mods:

 Plugins (12): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Announcer, Console Scheduler, Database Access Object, FixDupeWithBoat, GriefPrevention, LuckPerms, Nucleus, SaveInventory

 Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Super Pickaxe

**Issue Description**
The 'DestructEntityEvent' event is not triggered when the boat is broken by the player.

`   @Listener
    public void destruct(DestructEntityEvent event) {
        Sponge.getServer().getBroadcastChannel().send(Text.of(event.getCause().toString()));
    }
`
https://youtu.be/o1vNxmgp7tE

**Comment by ImMorpheus** [comment] 2018-10-12 18:24
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/999

**Closed as completed by ImMorpheus** 2018-10-12 18:24 UTC
Labels: system: event, version: 1.12 (u)
