### ISSUE TITLE
Spongeforge 3361+ at least won't load with forge 39 

### ISSUE THREAD

**Issue by Trillo7** [SpongePowered/Sponge#2049] opened 2018-08-07 00:28 UTC
**I am currently running**

- SpongeForge version: 3361
- Java version: 8
- Operating System: windows 10

- Plugins/Mods:  sponge wont load

**Issue Description**
Sponge 3361 wont load with Forge 2739.
I can for example use Sponge 3206 and it loads.
But latest sponge it just won't load like if u didnt put the .jar, also tried beta versions and the same. 3206 works fine. Modpack is enigmatica 2

**Comment by ryantheleach** [comment] 2018-08-07 02:06
If by Forge 39 you mean, Forge build 39, then this is a side effect of us being a coremod that mixes into Forge classes. It's not by design, but is expected and won't be fixed.

Your forge build should match the forge build specifier (or at least be close to it) in the spongeforge filename.

39 is a very very different build then Forge '2705' I'm honestly surprised it worked at all.

I'd suggest updating your Forge build, but I'm not familiar with how difficult that is with your modpack.

**Comment by Trillo7** [comment] 2018-08-07 02:30
Im sorry I meant forge 2739

**Comment by ryantheleach** [comment] 2018-08-07 02:31
~move sf

**Comment by ryantheleach** [comment] 2018-08-07 02:32
~move to sf

**Comment by limbo-app** [comment] 2018-08-07 02:32
Hey @trender7! I've moved your issue to [SpongePowered/SpongeForge#2370](https://github.com/SpongePowered/SpongeForge/issues/2370).

**Closed as completed** 2018-08-07 02:32 UTC
Labels: resolution: moved
