### ISSUE TITLE
Server Crashes when Player breaks block

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/Sponge#3538] opened 2021-09-15 20:10 UTC
**I am currently running**

- SpongeForge version: RC899
- Java version: 11
- Operating System: windows 10

- Plugins/Mods: Tinkerers construct, CarryOn, Mantle, ProjectE

**Break a block, Server Crashes**

https://gist.github.com/Cleardragonf/98b9f66894d4bd3ade8f389f91e7d3bb

**Comment by dualspiral** [comment] 2021-09-15 20:21
I've just committed a fix to the issue in your log, which isn't the issue you're reporting, sadly. Once the build has been created, can you try again? You should still get an error, but the error should point to where the problem is now.

**Comment by Cleardragonf** [comment] 2021-09-17 15:47
[crash-2021-09-17_10.45.41-server.txt](https://github.com/SpongePowered/Sponge/files/7186864/crash-2021-09-17_10.45.41-server.txt
[latest.log](https://github.com/SpongePowered/Sponge/files/7186866/latest.log)
)

Here are the latest logs...from the crash

or Gist
https://gist.github.com/Cleardragonf/f285892af2c935f5931a681c5210206f

**Comment by Cleardragonf** [comment] 2021-09-20 12:12
Updating with LATEST build from sponge and a new version of forge....3.2.5.  Same issue break a block server breaks and minecraft gives a Java.lang.illegalStateException: Asynchronous thread Access to PhaseTracker: PhaseTracker[sidedThread=java.lang.ref.WeakReference@3f274b81a.hasRun=false]

https://gist.github.com/Cleardragonf/d508053b76e7ac107cd9e43553659385

**Comment by Cleardragonf** [comment] 2021-09-25 02:18
https://gist.github.com/Cleardragonf/71eb30d691280d244f48b1b2184a5a47

**Comment by Cleardragonf** [comment] 2021-10-06 15:51
Same issue with latest 192.  ALSO just a bit more...in the Connection Lost on the Client side...it says
'Internal Exception: java.lang.IllegalStateException: Asynchronous Thread Access to PhaseTracker: PhaseTracker[sidedThread=java.lang.ref.WeakReference@27239f9c, hasRun=false]'

**Comment by Cleardragonf** [comment] 2021-10-24 13:06
updated...still no change within the RC932.  Same issue still remains.

**Comment by gabizou** [comment] 2022-02-03 11:20
Mind giving a re-test on this?

**Comment by Zidane** [comment] 2022-03-24 04:26
Closing due to lack of response.

**Closed as completed by Zidane** 2022-03-24 04:26 UTC
Labels: type: bug, version: 1.16 (u), platform: forge
