### ISSUE TITLE
Sponge command still throws error

### ISSUE THREAD

**Issue by Fatmice** [SpongePowered/Sponge#1954] opened 2018-06-23 11:22 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3221.jar
- SpongeVanilla version: 
- Java version: 
- Operating System:

- Plugins/Mods:

**Issue Description**
/sponge command and all its subcommand still missing and throwing error
https://github.com/SpongePowered/SpongeCommon/issues/1953

**Comment by dualspiral** [comment] 2018-06-23 11:38
Logs? Other information? This bug is near to useless. I don't know what error you're on about.

This is the current error which is correct. I just tested it on a freshly downloaded SF 3221 myself and this is what I get.

![screenshot_20180623_123422](https://user-images.githubusercontent.com/1904167/41809228-f66f0598-76e1-11e8-8f9b-9bdad17750dc.png)

If you're not getting this, then I need more information, logs, commands written, etc. If you _are_ getting this, this is the expected behaviour (as it stands).

**Comment by Fatmice** [comment] 2018-06-23 12:07
Uh, what is there to log?
> sponge
[12:04:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Unknown command. Try /help for a list of commands

Isn't the issue clear enough?  I do not get the output that you get.  This didn't happen on SpongeForge: 1.12.2-2705-7.1.0-BETA-3204
https://github.com/SpongePowered/SpongeForge/issues/2248

I notice it first on spongeforge-1.12.2-2705-7.1.0-BETA-3218.jar as well as others
https://github.com/SpongePowered/SpongeCommon/issues/1953

There was a "fix" of some kind for 3221 but I don't see any effect thus I reported again.
[debug.log](https://github.com/SpongePowered/SpongeCommon/files/2129887/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeCommon/files/2129888/latest.log)

**Comment by Lemmmy** [comment] 2018-06-23 12:12
this is unrelated to #1953 - sponge did not even load on your server, which is why the command doesnt work for you

**Comment by Fatmice** [comment] 2018-06-23 12:21
Are you sure?
debug.log:79:[11:14:22] [main/DEBUG] [FML]: Examining file: SpongeForge.jar
debug.log:216:[11:14:22] [main/DEBUG] [FML]:   Adding SpongeForge.jar to the mod list
debug.log:503:[11:14:22] [main/DEBUG] [FML]: Examining for coremod candidacy SpongeForge.jar
debug.log:504:[11:14:22] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SpongeForge.jar
debug.log:594:[11:14:23] [main/DEBUG] [mixin]: Scanning file:/dev/shm/minecraft/./mods/SpongeForge.jar for mixin tweaker
debug.log:595:[11:14:23] [main/DEBUG] [mixin]: file:/dev/shm/minecraft/./mods/SpongeForge.jar contains a mixin tweaker, adding agents
debug.log:596:[11:14:23] [main/DEBUG] [mixin]: Adding mixin platform agents for container file:/dev/shm/minecraft/./mods/SpongeForge.jar
debug.log:597:[11:14:23] [main/DEBUG] [mixin]: Instancing new MixinPlatformAgentFML for file:/dev/shm/minecraft/./mods/SpongeForge.jar
debug.log:598:[11:14:23] [main/DEBUG] [mixin]: SpongeForge.jar has core plugin org.spongepowered.mod.SpongeCoremod. Injecting it into FML for co-initialisation:
debug.log:646:	at org.spongepowered.common.launch.SpongeLaunch.setupMixinEnvironment(SpongeLaunch.java:125) ~[SpongeForge.jar:1.12.2-2705-7.1.0-BETA-3221]
debug.log:647:	at org.spongepowered.mod.SpongeCoremod.<init>(SpongeCoremod.java:92) ~[SpongeForge.jar:1.12.2-2705-7.1.0-BETA-3221]
debug.log:655:[11:14:23] [main/DEBUG] [mixin]: Instancing new MixinPlatformAgentDefault for file:/dev/shm/minecraft/./mods/SpongeForge.jar
debug.log:718:[11:14:25] [main/DEBUG] [mixin]: Processing prepare() for PlatformAgent[MixinPlatformAgentFML:file:/dev/shm/minecraft/./mods/SpongeForge.jar]
debug.log:719:[11:14:25] [main/DEBUG] [mixin]: Processing prepare() for PlatformAgent[MixinPlatformAgentDefault:file:/dev/shm/minecraft/./mods/SpongeForge.jar]
debug.log:760:[11:14:25] [main/DEBUG] [mixin]: Processing inject() for PlatformAgent[MixinPlatformAgentFML:file:/dev/shm/minecraft/./mods/SpongeForge.jar]
debug.log:761:[11:14:25] [main/DEBUG] [mixin]: Processing inject() for PlatformAgent[MixinPlatformAgentDefault:file:/dev/shm/minecraft/./mods/SpongeForge.jar]
debug.log:847:[11:14:25] [main/DEBUG] [FML]: Loaded 463 rules from AccessTransformer mod jar file ./mods/SpongeForge.jar!META-INF/common_at.cfg
debug.log:1231:[11:14:30] [Server thread/TRACE] [FML]: Skipping known library file /dev/shm/minecraft/./mods/SpongeForge.jar
debug.log:1306:[11:14:30] [Server thread/DEBUG] [FML]:   Adding SpongeForge.jar to the mod list
debug.log:1450:[11:14:30] [Server thread/TRACE] [FML]: Skipping already parsed coremod or tweaker SpongeForge.jar
latest.log:39:[11:14:22] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SpongeForge.jar
latest.log:90:	at org.spongepowered.common.launch.SpongeLaunch.setupMixinEnvironment(SpongeLaunch.java:125) ~[SpongeForge.jar:1.12.2-2705-7.1.0-BETA-3221]
latest.log:91:	at org.spongepowered.mod.SpongeCoremod.<init>(SpongeCoremod.java:92) ~[SpongeForge.jar:1.12.2-2705-7.1.0-BETA-3221]

**Comment by Lemmmy** [comment] 2018-06-23 12:22
just because it found the jar doesn't mean it loaded successfully, if you read the log you will see that it errored after trying to load a mixin, and didn't output any further than that.

**Comment by Fatmice** [comment] 2018-06-23 12:23
I thought that belong to LagGoggle.  Sponge complained that it needed mixin 0.7.10 and found 0.7.5

**Comment by Fatmice** [comment] 2018-06-23 12:31
Indeed, removing LagGoggles allowed Sponge to load so it must be the conflicting Mixin that was included in LagGoggles?

**Comment by Lemmmy** [comment] 2018-06-23 12:32
yes - this is probably an issue for LagGoggles, not SpongeForge

**Comment by dualspiral** [comment] 2018-06-23 12:36
> sponge
> [12:04:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Unknown command. Try /help for a list of commands

Yes, this is nothing to do with #1953, this is _why_ we ask for logs. Closing as this is nothing to do with Sponge.

**Closed as completed by dualspiral** 2018-06-23 12:36 UTC
Labels: system: command, resolution: invalid
