### ISSUE TITLE
[1.11] and [1.11.2] SPV SPF :Breaking containers gives partial drops, consistant Sponge errors 

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1110] opened 2016-12-31 04:57 UTC
_**[01:33:42] [Server thread/ERROR] [EntityTracker]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track**_

Noticed in Spongevanilla 1.11 (188) for a while now, spurious errors in logs, finally identified source and can highly reproduce: When breaking a chest or furnace (and likely other containers), anywhere from none to a few to almost all of the drops from the container contents are spawned to pickup, and a blob of error appears in sponge pertaining to tracking entities (BELOW).  TESTED WITH NO PLUGINS AT ALL = ERRORS STILL.

Tested in SPV 1.11.2 as well (V 192), same result.  Also a brand new, clean, out of box install version of SPV 1.11.2, new maps, same results.   I also tried to disable the "TRACKING" features in the configs, no impact.

Did a fresh, clean out of box forge 2201 and spongeforge-1.11.2-2201-6.0.0-BETA-2012  install, no changes to default installs of anything, brand new map, and still get reproducable result.

To reproduce: Stick a stack of cobblestone into the first slot of a chest, then break the chest.   At least 9 out of 10 times throws an error:

```
[23:37:36] [Server thread/INFO]: <drewchalberg> Chest One
[23:37:40] [Server thread/INFO]: <BooMod> go
[23:37:41] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:256) ~[lt.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:145) ~[lt.class:?]
	at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:37) ~[lx.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1211) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1120) ~[lw.class:?]
	at net.minecraft.world.WorldServer.onSpongeEntityAdded(WorldServer.java:1384) ~[lw.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:1430) ~[lw.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(WorldServer.java:1413) ~[lw.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.processEntities(PacketFunction.java:608) ~[PacketFunction.class:1.11.2-2201-6.0.0-BETA-2012]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$28(PacketFunction.java:592) ~[PacketFunction.class:1.11.2-2201-6.0.0-BETA-2012]
	at org.spongepowered.common.event.tracking.CapturedMultiMapSupplier.ifPresentAndNotEmpty(CapturedMultiMapSupplier.java:60) ~[CapturedMultiMapSupplier.class:1.11.2-2201-6.0.0-BETA-2012]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$29(PacketFunction.java:563) ~[PacketFunction.class:1.11.2-2201-6.0.0-BETA-2012]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) [PacketPhase.class:1.11.2-2201-6.0.0-BETA-2012]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.11.2-2201-6.0.0-BETA-2012]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:141) [PacketUtil.class:1.11.2-2201-6.0.0-BETA-2012]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zji000(SourceFile:39) [fo$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Entity EntityItem['item.tile.stonebrick'/3116, l='world', x=306.28, y=63.78, z=213.79] is already tracked for world: world
	at net.minecraft.entity.EntityTracker.redirect$reportEntityAlreadyTrackedWithWorld$zda000(EntityTracker.java:65) ~[lt.class:?]
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:224) ~[lt.class:?]
	... 24 more
[23:37:43] [Server thread/INFO]: <BooMod> error
```

A link to where a player broke a chest full of many things spewing many globs of this error for different items (from SPV-188 1.11 version log):
[http://pastebin.com/qn11g78t](http://pastebin.com/qn11g78t)

**Comment by Zerthick** [comment] 2017-01-02 22:32
Duplicate of #1079

**Closed as completed** 2017-01-21 23:58 UTC
Labels: resolution: duplicate
