### ISSUE TITLE
Error on RCOM parsing input

### ISSUE THREAD

**Issue by MrIngelborn** [SpongePowered/Sponge#1533] opened 2017-09-20 00:27 UTC
**I am currently running...**
- SpongeVanilla version: 1.12.2-7.0.0-BETA-330
- Java version: 
    OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
    OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
> Plugins (8): Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, Discord Bridge, GriefPrevention, LuckPerms, Nucleus

**What is the expected result?**
Server parsing and executing commands from RCON connection
**What is the current result?**
>Exception whilst parsing RCON input
>java.lang.IllegalStateException: CauseStackManager called from off main thread!

**Server log:**
http://termbin.com/8on5

**Comment by ryantheleach** [comment] 2017-09-20 01:05
https://github.com/SpongePowered/SpongeCommon/blob/c96a2d8c2b7a3ab8bb2d1c61cdea47a55ba3a8a9/src/main/java/org/spongepowered/common/mixin/core/network/rcon/MixinRConThreadClient.java#L110

Is being injected in closeSocket on head.

**Comment by Cybermaxke** [comment] 2017-09-20 06:55
The following PR will fix this issue: #1526 
The current RCON implementation is completely broken, even without the cause tracking.

**Comment by ryantheleach** [comment] 2017-09-21 01:24
Thanks @Cybermaxke I remembered seeing the code committed recently, searched recent commits in multiple branches and projects and didn't see it. Didn't realize it was a PR.

**Comment by parlough** [comment] 2017-11-23 18:30
I will get this fix in soon once I can get on a computer and test it.

**Comment by kashike** [comment] 2017-11-23 19:24
#1526

**Closed as completed by kashike** 2017-11-23 19:24 UTC
Labels: system: phase tracker, version: 1.12 (u)
