### ISSUE TITLE
Placing signs with NBT prompts for text.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#289] opened 2015-06-03 22:57 UTC
Placing signs with NBT (acquirable with ctrl + middle click) prompts the user for text and provides a blank sign.

On single player vanilla/forge this results in the sign being placed, with no prompt, with the text of the original sign as expected.

**Comment by modwizcode** [comment] 2015-06-04 11:32
I noticed this bug myself. I believe it has something to do with forge's fix for hacks involving manipulated sign data. I don't know if this is how vanilla 1.8.6 handles the same thing but if not someone needs to override forge to restore the vanilla behavior and replace it with vanilla's fix instead of a broken one.

**Comment by progwml6** [comment] 2015-06-04 12:00
I'd think fixing forge might be the better move

**Comment by simon816** [comment] 2015-07-08 20:57
I can confirm this is a forge bug. Tested with vanilla 1.8.7 works as expected, Forge 11.14.3.1450 will prompt for sign text when placing. I'll see what I can do about getting a PR to forge.

**Comment by modwizcode** [comment] 2015-07-08 20:57
I already wrote and submitted one. Waiting for a response still.

**Comment by simon816** [comment] 2015-07-08 21:05
@modwizcode I'm not seeing any PR to forge that addresses this issue. Sure you have a PR for this?

**Comment by modwizcode** [comment] 2015-07-08 21:09
Oops thought this was the leaf issue. My apologies. The sign text one I
thought might be a challenge since forge intentionally broke it for safety.

**Comment by ryantheleach** [comment] 2015-07-09 15:10
Ok, found out why Joe's server works as expected, Joe's server runs SpongeVanilla not sponge.

**Comment by simon816** [comment] 2015-07-24 21:28
Should be fixed now if you use Forge 11.14.3.1497. I suppose this Sponge issue is only really 'fixed' when the forge dependency is bumped.

**Comment by JBYoshi** [comment] 2015-07-30 19:43
Can thisbe closed now that Forge has been bumped? 067d1bc167c82b2b214bb97af887a3dfc543a1e2

**Closed** 2015-07-30 19:44 UTC
Labels: forge-bug, input wanted
