### ISSUE TITLE
ConstructPortalEvent. The event is not canceled. 

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#2034] opened 2018-08-02 09:00 UTC
**I am currently running**

- SpongeForge version:  1.12.2-2705-7.1.0-BETA-3364
- SpongeVanilla version: 1.12.2-7.1.0-BETA-78
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
- Operating System: Windows 7 / Debian 9

- Plugins (28): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LangSwitch, LuckPerms, MineReset, Nucleus, PayDay, PlaceholderAPI, ProjectCore, StackBan, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, VirtualTool, WorldEdit, spark

- Mods (50): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Better Questing, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Deadly Monsters, Fishing Net Mod, Forestry, Hammer Core, HoloInventory, Immersive Engineering, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, Mantle, McJtyLib, MrCrayfish's Furniture Mod, Netherending Ores, QuestUtils, Quick Leaf Decay, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Solar Flux Reborn, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

**Issue Description**

Not Work:

	@Listener
	public void onCreatePortal(ConstructPortalEvent event) {
		event.setCancelled(true);
	}

Logs are clean.

**Comment by ImMorpheus** [comment] 2018-08-02 14:30
Not implemented. https://github.com/SpongePowered/SpongeCommon/pull/1608

Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1916, https://github.com/SpongePowered/SpongeCommon/issues/1559

**Closed as completed** 2018-08-02 17:09 UTC
Labels: resolution: duplicate, version: 1.12 (u)
