### ISSUE TITLE
Owner of grown plants, trees, and world genned blocks?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1798] opened 2018-02-13 01:46 UTC
Reported on discord, the owner of grown plants and tree's are currently the owner of the person who planted the saplings.

This causes numerous issues, due to the difficulty of tracking 'artificially' grown blocks vs 'naturally' grown blocks.

e.g. @Zerthicks usecase.

They want to be able to track when a player knocks down tree's or plants, and reward them XP.

However, they only want to reward the player for tree's / plants that have finished growing, and not having their blocks manually placed by the players.

Yet currently it's impossible to determine whether the blocks were placed previously (across restarts) or grown.

One option would be to manipulate this yourself (see https://github.com/Daniel12321/AdventureMMO/blob/master/src/main/java/me/mrdaniel/adventuremmo/listeners/WorldListener.java)

Another would be for Sponge to somehow tell the difference between machine built, and naturally grown things... (how?)

And treat them differently.

But what about machine grown things? should they count?

If you were trying to avoid grief, then a tnt block being placed by a block placer probably should have an owner of the player who placed the block placer...

Another random thought, would it be worth assigning generated blocks the owner of the worlds UUID? and the player that generated it as the notifier?

Should grown plants have an owner of their origin block, or of the world uuid/empty?

**Comment by Eufranio** [comment] 2018-02-13 01:52
I vote for grown blocks like trees/sugar cane have no creator, but notifier with the owner of the first block. This allows developers to make sure a block was placed by a player while still allows the old tracking.

**Comment by Zerthick** [comment] 2018-02-13 01:52
There are also inconsistencies with how things like sugar cane are handled. When the player places sugar cane they are set as the creator of the bottom block. However, if subsequent sugar cane blocks grow, the player is not set as the creator of these new blocks.

**Comment by gabizou** [comment] 2018-02-13 01:55
Personally, I feel that the creator should be the person who planted the first block (say for example if a player places a sapling in their region). Afterwards, what I imagine what would make the most sense is if the player artificially forced something to grow, say directly with bonemeal, or indirectly (through a TileEntity that is owned by said player), the player would be marked as the owner of the block change, and therefor the owner of the block itself. This would make the literal sense of they owned the block changes, whereas notifying the block is simple as they are either breaking the block or interacting with the block to cause a notification to occur. 

Let me know if this makes more sense, because if it does, I can implement the necessary changes in how it's tracked over the next maybe couple of weeks.

**Comment by Zerthick** [comment] 2018-02-13 01:57
Right, but then there would still be no way to differentiate between oak logs that were "bone mealed" into existence by a player, versus those that were directly placed by them.

**Comment by gabizou** [comment] 2018-02-13 02:00
While there wouldn't be a way to directly tell, except by listening to the `ChangeBlockEvent` with the original block (the sapling) being owned by no one. Likewise, that owner/notifier information is always available during events, just that you'd need to understand that the person that placed the sapling is always stored separately from the person notifying/nurturing the sapling to grow into a tree, at which point the tree is now created by the second player.

**Comment by Zerthick** [comment] 2018-02-13 02:03
Right, so this all came about because we were trying to come up with a way that would avoid the necessity to implement your own cause tracker of sorts by listening to events and then storing the locations of all of the blocks of interest to a DB to be queried whenever the player breaks a block.

**Comment by gabizou** [comment] 2018-02-13 08:49
But this is already provided for you with the sponge implementation. You just have to listen to the events and work based on that. Because the person breaking a block would have to be an by either direct or indirect placement. I don’t see what we’re now trying to say what the problem is specifically that we can fix with code.

**Comment by RedNesto** [comment] 2018-02-13 11:15
@gabizou i'm actually working on refactoring the ChangeBlockEvent (removal of `Grow` and `Decay`), so if you want I could try to implement the changes requested in this issue, but I have to know what do to.

I think that the player who placed a sapling should always be the owner of the blocks forming the grown tree, but I work on a way to track if a tree has grown by force (bonemeal) or naturally (with a `EventContextKeys#BLOCK_CHANGE_ACTION`), and a way to define the creator as the TileEntity or Entity who forced the growth (if there is one), maybe via an `EventContextKeys#BLOCK_CHANGE_SOURCE`. What do you think of this?

**Comment by ryantheleach** [comment] 2018-02-13 13:27
@RedNesto That won't work without considerable refactoring, due to the current storage format of UUID's that are the owners / notifiers. Have you seen how they are stored? What was your plan?

**Comment by ryantheleach** [comment] 2018-02-13 13:30
@gabizou Specifically,

They would like a way to tell the difference between direct placement of blocks by players, and blocks that are 'organically' grown.

I suspect there isn't much we can do, if people are reluctant of having the creator be empty for blocks *indirectly* placed.

I suggested they make an issue, so we can attempt to work out a solution (Or if there even is one?)

**Comment by RedNesto** [comment] 2018-02-13 15:11
@ryantheleach We should keep the Owner things, but adjust them in the case of the ChangeBlockEvent, like having an `Owner` for the `BlockChangeEvent.Place` who is the placer of the sapling (for a tree), but not the `Creator` of the blocks forming this tree.

**Comment by Zerthick** [comment] 2018-02-13 19:06
So I understand that this can already be accomplished by listening to events, the problem I'm attempting to solve is that when the player breaks a block within a ChangeBlockEvent.Break I'm trying to determine if the block that was broken was spawned naturally or directly by the player.  Such information is not provided in this event.  The only way to currently accomplish this task is to have previously listened to things like ChangeBlockEvent.Grow record this information somewhere and then retrieve it to check against during ChangeBlockEvent.Break which is a non-trival task at it involves creating a data storage system that can quickly retrieve data based on a block location.

**Comment by RedNesto** [comment] 2018-02-13 19:17
As I said (but maybe not clearly enough), we may use the `EventContextKeys#CREATOR` to determine the player who placed the target block (but I think this is too restrictive of having only a `User` `CREATOR`).

**Comment by Zerthick** [comment] 2018-02-13 19:41
A solution such as that would work, perhaps a new EventContextKey would need to be created instead though to prevent restricting to `User`?

**Comment by RedNesto** [comment] 2018-02-13 19:44
The thing which would seems strange is the need of using `Object` as value for this key, since mods could place blocks via other blocks, or any entities.

**Comment by Zerthick** [comment] 2018-02-13 19:49
You could perhaps enforce that the value be `DataSerializable`? Though I'm not sure if such a restriction is necessary.

**Comment by Zerthick** [comment] 2018-05-04 20:53
@RedNesto Any movement on this issue?

**Comment by gabizou** [comment] 2018-10-09 17:23
So, having recently revisited this sort of issue with @Zidane, currently, our implementation is as such:

Player places a sapling in a world, it is naturally grown over time into a tree. The creator and notifier of those tree blocks is the same owner as the original sapling.

When a player places a sapling and someone else uses bonemeal on the sapling, the tree grown is formed with the notifier of the sapling as the creator of all the new blocks formed, with the previous owner of the sapling being still the owner, but a new notifier of the original sapling block position being the person who bonemealed the sapling.

I get that there's trouble about determining whether a tree is grown naturally because the owner is always set when the tree is grown, based on the last notifier/owner of the sapling that is growing.

A potential would be that the "owner" of the blocks would be empty in the cases of natural growth, whereas bonemeal or "direct" growth would be resulting with the notifier as the creator.

Would this suffice as a "fix" and clarification?

In essence: Natural growth will only attach notifiers of the newly generated blocks, but not owners from the original sapling. Forced or "interacted" growth will apply the owner on the newly generated blocks.

**Comment by ryantheleach** [comment] 2018-10-10 00:47
That would solve this issue, but it's my suspicion that it will make plugins such as Prism a lot more complicated for the logging of 'viral' blocks.

Would/does mycelium, grass, vines, (in future kelp) ender plants, Ice, match the current (or proposed) behavior of trees?

**Comment by gabizou** [comment] 2018-10-10 01:28
Currently:

Any passive growth, from saplings to grass to whatever occurs during "random ticks" for growth, will associate both the Owner and Notifier of the original block placed that is causing the spread.

Proposed:
Any passive growth, from saplings to grass to whatever occurs during "random ticks" for growth, will associate only the new blocks as having no new Owner, but instead, have the Notifier applied from the original source block (if the original owner of the sapling or grass block didn't do anything except place, and someone else notified the block, the notifier will propagate, but if the owner/notifier is the same person, the owner will propagate).

Previous to my fix, no owner or notifier was being propagated.

@Zidane since this affected you more recently, can you weigh in on the options presented?

**Comment by ImMorpheus** [comment] 2019-06-22 20:41
Superseded by https://github.com/SpongePowered/SpongeCommon/issues/2241

**Closed as completed by ImMorpheus** 2019-06-22 20:41 UTC
Labels: system: phase tracker, resolution: superseded
