### ISSUE TITLE
Deadlock when joining a new world

### ISSUE THREAD

**Issue by jpenilla** [SpongePowered/Sponge#3402] opened 2021-05-08 02:50 UTC
Since the builds on May 1st, there has been an issue where when generating a new world on a SpongeVanilla dedicated server, after joining the server the chunks in a 0 (no chunks) to about 1 chunk radius will be sent to the client, and afterwards the server will entirely deadlock, and after 60 seconds watchdog kills it. Sometimes the deadlock will happen after joining for the first 2-3 loads of a world, or sometimes will stop happening on the second load.

log of generating a new world, joining, and the proceeding crash: https://paste.gg/p/anonymous/a9252da0967c4eca838db4dacd7523b9

This is the last known commit without the issue: 2def9ef39130023a09ce800873ac163943bf92e8
I have yet to track down which May 1 commit caused it

**Comment by Draycia** [comment] 2021-05-08 02:55
<https://paste.gg/p/anonymous/43ffd4012e3141f88ba878417358578f>
Or in my case, the issue persists no matter how many restarts occur.

**Comment by Draycia** [comment] 2021-05-08 03:02
Potentially relevant commit, as these 2 methods are in the thread dump (logScheduledUpdate & getBlockEntity).
<https://github.com/SpongePowered/Sponge/commit/429de3b0261bcd066fded34bb7a97677fc545171>

**Comment by aromaa** [comment] 2021-05-08 11:52
The commit at fault is the 429de3b0261bcd066fded34bb7a97677fc545171 and partial fix for this was in 18ab8c06000136d6e29fc0338423daf36c96f8a8

**Comment by gabizou** [comment] 2021-05-08 15:14
This is exasterbated by the transactional recording of scheduled ticks, but it seems there’s a possible issue with EntityActivation prematurely loading chunks, leading to the unnecessary transactions to be recorded from those chunks being freshly generated/reloaded.

**Comment by dualspiral** [comment] 2021-05-08 16:07
It looks to me that you're right there, but the crux of the matter is that the scheduled updates are being called during the chunk load, which then tries to get the current chunk, which you're trying to load - and it deadlocks because it's waiting for the current chunk load to finish... which you're in the middle of doing in the first place.

Entity activation is indeed at fault here. I think that if we change the `getChunk` call in `EntityActivationRange#activateEntities` to `getChunkNow` we will sidestep the issue because `getChunkNow` does not appear to cause any loading.

As a side note, it's fair to say that it was intended that `getChunk` _should not_ load, because the boolean is false. However, under some cirumstances it looks like the chunk loader will _still_ try to load a chunk. `getChunkNow` is overriden in `ServerChunkCache` and doesn't do any of that rigmarole, as the chunk EntityActivation is targetting should exist in the first place, such a call would appear to be sensible.

I'm going through the entity activation code now because in tracking this down, there was `ServerWorldMixin_EntityActivation` insteaad of `ServerLevelMixin_EntityActivation` - it took me some time to realise that mixin existed. Various style issues too so I'm just gonna go clean that up so it's clearer in the stack trace.

**Comment by dualspiral** [comment] 2021-05-08 18:25
Try the latest commit please! (f4cf38d180221a5fb157a026947649d460adbaa9)

**Comment by jpenilla** [comment] 2021-05-08 23:16
> Try the latest commit please! ([f4cf38d](https://github.com/SpongePowered/Sponge/commit/f4cf38d180221a5fb157a026947649d460adbaa9))

I seem to be able to generate a new world and join as expected running the latest build.

**Closed as completed** 2021-05-08 23:27 UTC
