### ISSUE TITLE
Server crash when DetonateExplosiveEvent is cancelled

### ISSUE THREAD

**Issue by phit** [SpongePowered/Sponge#1613] opened 2017-11-23 18:30 UTC
Reopening here, original issue https://github.com/SpongePowered/SpongeVanilla/issues/349
>Server encounters 'java.lang.IllegalStateException: not primed' and dies when DetonateExplosiveEvent is canceled.
>
>Build number: 1.12.1-7.0.0-BETA-327
>Server log: https://pastebin.com/peWkgXsQ
>
>I am installing my plugin, but no other plugins.
>This is the code that I guess causing this error:

```
@Listener
public void onDetonateExplosive(DetonateExplosiveEvent event) {
        event.setCancelled(true);
}
```

>Same with SF 1.12.2-2529-7.0.0-BETA-2742.

**Comment by parlough** [comment] 2017-11-23 18:31
@JBYoshi I know you were fixing some things with explosions previously. Is this connected or could you handle this?

**Comment by JBYoshi** [comment] 2017-11-24 19:54
Not connected, but this seems to be an easy fix. I just need to test it.

**Comment by ryantheleach** [comment] 2017-11-25 07:28
@JBYoshi I'm not 100% sure that this is the correct fix, What is the correct definition of Primed? Maybe it shouldn't be checking the primed state at all?

**Comment by JBYoshi** [comment] 2017-11-25 20:57
"Primed" means it will explode. "Defuse" means cancelling a future (primed) explosion. During the event, the TNT is still "primed" because it only explodes after the event finishes.

**Comment by ImMorpheus** [comment] 2018-01-31 18:53
Tested on SpongeForge 1.12 (bleeding branch)

I'm not able to reproduce the crash, this can be closed.

**Comment by phit** [comment] 2018-01-31 18:55
@ryantheleach you reopened this, status?

**Comment by ryantheleach** [comment] 2018-02-01 00:45
It was reopened based on looking at the code, not the error.

Basically, I see fused explosives as having the following timeline.

fuseTicking -> primed -> exploding.

The problem is the edge cases at the transitions, during the event the fix made it seem like a tnt could be BOTH in primed state and in exploding state.

In my mind they are mutually exclusive. exploding is the state after primed.

>During the event, the TNT is still "primed" because it only explodes after the event finishes.

Covered most of the concerned I had, but is the TNT considered exploding in the detonate event if it happens before the explosion?

**Comment by Zidane** [comment] 2018-02-02 23:56
Closing this, open a new issue ryan and don't take over this issue. The original issue, the crash, is fixed.

**Closed as completed by Zidane** 2018-02-02 23:56 UTC
Labels: status: accepted, type: bug, system: event, version: 1.12 (u)
