### ISSUE TITLE
setRawData not working

### ISSUE THREAD

**Issue by Zeon8** [SpongePowered/Sponge#2319] opened 2019-07-09 17:17 UTC
I want to add LootTable

        Chest chest (Chest)Sponge.getServer().getWorld("world").get().getLocation(chestc).getTileEntity().get();
        DataContainer nbt = chest.toContainer();
        nbt.set(DataQuery.of("UnsafeData","LootTable"),"test:chests/table");
        chest.setRawData(nbt.getContainer());
        
        logger.info(chest.toContainer().get(DataQuery.of("UnsafeData")).toString()); // print
But, NBT has not change
I print DataView and nothing has changed

       Optional[MemoryDataView{path=UnsafeData, safety=ALL_DATA_CLONED, map={x=300, y=1, z=1, Items=[], id=minecraft:chest, Lock=}}]

**Comment by ImMorpheus** [comment] 2019-07-19 15:59
That's because it's not implemented.

Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1694

**Closed as completed by ImMorpheus** 2019-07-19 15:59 UTC
Labels: resolution: duplicate
