### ISSUE TITLE
Legacy data registration doesn't work

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1396] opened 2017-06-17 19:44 UTC
**I am currently running...**

- SpongeForge version: 2384
- SpongeVanilla version: 1.11.2-6.1.0-BETA-11

- Plugins/Mods:
  - [Holograms](https://github.com/randombyte-developer/holograms)

At startup this error occurs: https://gist.github.com/randombyte-developer/3e8e0f5d706f403e235790f4d46af439

@gabizou did [a commit](https://github.com/SpongePowered/SpongeCommon/commit/c928639ae8fcb4a51c1a4fb128c443870e78baaa) to fix a similar issue with legacy data registration.
[Forum topic where it all started](https://forums.spongepowered.org/t/holograms-easily-create-floating-texts/12861/241?u=randombyte).
[Issue reporting the same](https://github.com/randombyte-developer/holograms/issues/16).
[The data registration](https://github.com/randombyte-developer/holograms/blob/1de67660b7146c6d43a777209bb8de8b101d8f35/src/main/kotlin/de/randombyte/holograms/Holograms.kt#L47) in Holograms.

**Comment by gabizou** [comment] 2017-06-18 04:36
I see what happened, I wrote it into SpongeForge but failed to write it into SpongeCommon directly (since forge listeners still have to be applied the same way) I'll get a fix for this tomorrow.

**Comment by randombyte-developer** [comment] 2017-06-24 16:43
@gabizou What's the status on this?

**Comment by randombyte-developer** [comment] 2017-08-20 16:36
I hope this gets resolved soon ;)

**Comment by realGWM** [comment] 2017-09-30 10:59
Any news?

**Comment by ImMorpheus** [comment] 2018-08-29 13:04
Closing this issue, as of Jan 1st 2018 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue on Minecraft 1.12.2 and this issue was wrongly closed, please open a new issue with updated information.

Note: the legacy data registration was removed with https://github.com/SpongePowered/SpongeCommon/commit/5409aef39d4b6c1ee2db8484d9d92a0e0acfc69a . I think this is not even reproducible

**Closed as completed by ImMorpheus** 2018-08-29 13:04 UTC
Labels: type: bug, system: data, version: 1.11 (u)
