### ISSUE TITLE
LaunchProjectileEvent not firing

### ISSUE THREAD

**Issue by simonerighi96** [SpongePowered/Sponge#2576] opened 2020-04-21 13:00 UTC
**I am currently running**

- SpongeForge version: 7.2.0
- Java version: 8
- Operating System: Windows 8.1

- Plugins/Mods: none

**Issue Description**
The Event LaunchProjectileEvent is not firing when an arrow is shot by a player. I tried with every listener annotation configuration but i can't get it to work.

> @Listener( order = Order.FIRST, beforeModifications = true)
>     public void onArrowThrow( LaunchProjectileEvent event ){
> 
>         plugin.getLogger().info("Detected a thrown projectile");
> 
>     }

**Comment by ImMorpheus** [comment] 2020-04-21 17:34
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1397

**Closed as completed by ImMorpheus** 2020-04-21 17:34 UTC
Labels: resolution: duplicate
