### ISSUE TITLE
How to stop SpongeForge from adding NBT tags to mc region files

### ISSUE THREAD

**Issue by Pangamma** [SpongePowered/Sponge#2530] opened 2020-03-15 06:41 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.8   
- SpongeVanilla version:  ??? 1.12.2 ??   (RLCraft modpack still uses 1.12.2)
- Java version: 8
- Operating System: Debian 

- Plugins/Mods:
`
/mods
05/08/2019  09:34 PM            23,934 # LibLoader.jar
03/05/2020  06:12 PM            71,312 AdHooks-1.12.2-3.2.3.0-build.0435.jar
05/31/2019  05:31 PM           277,112 Advanced-Fishing-1.12.2-1.3.3.jar
05/07/2019  07:29 PM           109,321 alcatrazcore-1.0.4.jar
11/07/2019  10:38 PM         1,239,580 antiqueatlas-1.12.2-4.6.3.jar
05/31/2019  05:36 PM            17,974 anvilpatch-1.0.0.jar
05/31/2019  05:31 PM           186,686 Aquaculture-1.12.2-1.6.8.jar
05/12/2019  07:17 PM           163,703 armorunder-mc1.12.2-1.0.0.jar
09/19/2019  01:28 PM           108,306 AutoRegLib-1.3-32.jar
10/02/2019  11:52 AM             3,969 BacoDifficulty-1.0.3.jar
10/27/2019  04:21 PM           886,037 BattleTowers-1.12.2.jar
02/12/2018  11:43 PM           108,450 Baubles-1.12-1.5.2.jar
05/15/2019  06:25 PM            58,248 BaublesHud-1.12.2-5.0.2.jar
09/26/2018  04:23 PM            98,955 BetterCombat-1.12.2-1.5.6.jar
03/05/2020  07:05 PM           926,081 BetterFoliage-MC1.12-2.2.0.jar
11/25/2019  08:00 PM         1,487,187 better_survival-1.4.1.jar
09/07/2018  07:12 PM            47,505 Bloodmoon-MC1.12.2-1.5.3.jar
09/24/2019  10:31 PM           132,644 BNBGamingLib-1.12.2-2.17.6.jar
03/12/2020  09:42 AM             3,642 Born+In+A+Barn+V1.8-1.12-1.1.jar
03/05/2020  07:12 PM           443,029 Bountiful Baubles-1.12.2-0.1.5.jar
10/04/2018  11:13 AM            32,235 campfire-1.12-v1.2.jar
11/30/2019  11:06 PM           290,843 carrotslib-mc1.12.2-1.0.0b1.jar
11/01/2019  09:45 AM           317,135 CarryOn MC1.12.2 v1.12.3.jar
02/12/2018  11:43 PM            25,447 ChunkAnimator-MC1.12-1.2.jar
03/05/2020  07:12 PM           167,301 comforts-1.12.2-1.4.1.3.jar
10/25/2019  11:47 AM           378,621 CompatSkills-1.12.2-1.17.0.jar
09/07/2018  07:12 PM            73,465 CoralReef-2.5-1.12.2.jar
03/05/2020  07:14 PM           124,181 corpsecomplex-1.12.2-1.0.8.jar
05/06/2019  01:19 PM            12,600 craftablechainmail-1.0.jar
02/12/2018  11:43 PM             3,515 CraftableHorseArmour-1.3.0-1.12.jar
03/05/2020  07:26 PM         1,363,036 CraftTweaker2-1.12-4.1.20.jar
03/05/2020  07:34 PM           961,299 CreativeCore_v1.9.90_mc1.12.2.jar
03/05/2020  07:23 PM            91,121 CustomMainMenu-MC1.12.2-2.0.9.1.jar
12/01/2019  11:15 AM           780,421 defiledlands-1.12.2-1.4.3.jar
10/25/2019  11:44 AM           111,421 disenchanter-[1.12]1.6.jar
03/05/2020  07:41 PM           702,808 DoomlikeDungeons-1.13.1-MC1.12.2.jar
05/07/2019  05:46 PM            70,431 dttraverse-1.5.jar
11/11/2019  04:02 PM        16,014,866 DynamicSurroundings-1.12.2-3.6.0.2.jar
11/02/2019  12:41 PM            96,279 DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar
03/05/2020  06:52 PM           789,332 DynamicTrees-1.12.2-0.9.7.jar
09/22/2019  02:53 PM            17,075 EnchantmentDescriptions-1.12.2-1.1.19.jar
10/22/2019  01:05 PM         3,774,252 EnhancedVisuals_v1.2.7_mc1.12.2.jar
05/07/2019  05:43 PM           381,455 FamiliarFauna-1.12.2-1.0.11.jar
10/27/2018  08:21 PM           177,413 FancyBlockParticles-1.12.x-2.4.1.jar
03/06/2020  12:05 AM           459,232 firstaid-1.6.13.jar
03/05/2020  08:02 PM           201,683 foamfix-0.10.10-1.12.2.jar
09/07/2018  07:16 PM            81,460 FoodExpansion1.3.3-1.12.2.jar
03/05/2020  06:11 PM           910,504 ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar
09/19/2019  03:03 PM         6,278,399 Forgelin-1.8.4.jar
09/30/2019  04:32 PM           617,200 ForgottenItems+MC1.12.2+v1.2.1.jar
11/30/2019  09:35 PM             2,608 FriendlyEndermite_v1.0.1_mc1.12.2.jar
05/07/2019  02:15 PM            24,050 GlobalGameRules-1.12.2-2.2.7.jar
09/07/2018  08:10 PM           157,747 grapplemod-v11.1-1.12.2.jar
11/02/2019  01:59 PM        16,086,478 iceandfire-1.7.1-1.12.2.jar
09/19/2019  01:16 PM           183,579 InfernalMobs-1.12.2.jar
03/05/2020  06:10 PM           286,149 InventoryTweaks-1.64+dev.150.jar
11/21/2019  10:10 PM            24,985 ISeeDragons-0.12.jar
03/05/2020  06:08 PM            48,564 ItemPhysic_Full_1.4.28_mc1.12.2.jar
10/29/2019  11:23 PM            15,618 itlt-1.12.2-1.0.2.jar
02/13/2018  12:29 AM           455,763 IvToolkit-1.3.3-1.12.jar
10/20/2019  09:22 AM           651,473 jei_1.12.2-4.15.0.291.jar
09/19/2019  02:01 PM           187,346 Level Up! 2-1.1.23-1.12.jar
05/07/2019  01:35 PM           884,837 llibrary-1.7.19-1.12.2.jar
09/24/2019  10:31 PM            42,647 LoadingScreens-1.12.2-0.3.1.jar
03/05/2020  05:45 PM           789,743 lostcities-1.12-2.0.22.jar
05/31/2019  05:31 PM            30,677 lostsouls-1.12-1.1.4.jar
03/14/2020  05:57 PM        74,676,193 lycanitesmobs-1.12.2-2.0.6.7I.jar
09/24/2019  10:32 PM             4,174 MainMenuScale-1.3.2.jar
03/06/2020  09:35 PM    <DIR>          memory_repo
02/13/2018  01:56 AM           669,015 mobends-0.24_for_MC-1.12.jar
03/12/2020  11:44 AM            21,508 Morpheus-1.12.2-3.5.106.jar
11/02/2019  01:50 PM            75,170 MouseTweaks-2.10-mc1.12.2.jar
09/27/2019  11:19 PM            64,791 MultiMine-1.12.2.jar
11/30/2019  10:54 PM            18,527 Neat 1.4-17.jar
03/12/2020  01:55 PM         2,121,429 notreepunching-2.0.20.jar
11/02/2019  12:40 PM           341,728 OreLib-1.12.2-3.6.0.1.jar
09/19/2019  03:36 PM         1,082,311 phosphor-1.12.2-0.2.6+build50-universal.jar
09/19/2019  01:43 PM           141,940 PotionCore-1.8_for_1.12.2.jar
11/10/2019  02:04 PM            11,319 PotionFingers-r1.0-8.jar
09/19/2019  01:44 PM            83,553 QualityTools-1.0.7_for_1.12.2.jar
02/12/2018  11:45 PM            74,187 RealisticTorches-1.12.2-2.1.1.jar
03/05/2020  06:08 PM         2,427,402 RebornCore-1.12.2-3.19.1.521-universal.jar
05/07/2019  01:24 PM         7,076,645 RecurrentComplex-1.4.8.2.jar
10/25/2019  11:47 AM           338,650 Reskillable-1.12.2-1.13.0.jar
09/24/2019  10:31 PM            16,612 ResourceLoader-MC1.12.1-1.5.3.jar
02/12/2018  11:45 PM           701,215 RoguelikeDungeons-1.12.2-1.8.0.jar
09/07/2018  07:16 PM            25,875 roughTweaks0.2.4-1.12.2.jar
11/30/2019  11:06 PM           244,703 Ruins-1.12.2.jar
10/27/2019  04:19 PM           369,985 ScalingHealth-1.12.2-1.3.42+147.jar
10/10/2019  02:22 PM           185,187 SereneSeasons-1.12.2-1.2.18-universal.jar
03/05/2020  06:06 PM           369,314 SilentLib-1.12.2-3.0.14+168.jar
03/05/2020  05:48 PM            10,110 sit-1.12.2-v1.3.jar
11/30/2019  10:56 PM            27,124 SnowRealMagic-0.3.3.jar
09/19/2019  03:11 PM           448,545 So+Many+Enchantments+V0.4.4.jar
03/05/2020  05:47 PM            43,161 SoundFilters-0.12_for_1.12.jar
11/02/2019  02:00 PM           506,832 spartanfire-0.05.jar
11/30/2019  10:57 PM           430,944 SpartanShields-1.12.2-1.5.4.jar
11/22/2019  07:54 PM           937,558 SpartanWeaponry-1.12.2-beta-1.3.8.jar
09/19/2019  01:47 PM            49,537 SpawnerControl-1.6.3b.jar
03/14/2020  05:42 PM        22,178,301 spongeforge-1.12.2-2838-7.1.8.jar
11/30/2019  10:58 PM            24,024 stg-1.12.2-1.2.3.jar
09/28/2019  12:23 AM           469,871 switchbow-1.5.7.jar
03/05/2020  05:45 PM            30,788 tanspit-1.12.2-1.4.jar
10/06/2018  11:35 PM           638,924 TickProfiler-1.12-0.0.7.jar
10/03/2019  06:39 PM            31,034 tnt_utilities-mc1.12-1.2.3.jar
10/20/2019  09:23 AM           155,009 ToolBelt-1.12.2-1.9.12.jar
05/15/2019  06:34 PM           357,504 ToughAsNails-1.12.2-3.1.0.141-universal.jar
10/11/2018  02:50 PM           270,133 Traverse-1.12.2-1.6.0-69.jar
03/05/2020  05:20 PM           610,961 Trinkets and Baubles-1.12.2-0.29.2.jar
10/10/2018  05:58 PM            42,657 trumpetskeleton-1.12-1.0.2.1.jar
09/15/2019  10:36 PM            47,850 TschippLib MC1.12.2 v1.1.3.jar
03/05/2020  02:41 PM            87,400 tumbleweed-1.12-0.4.7.jar
03/12/2020  11:34 AM           177,953 vanilladeathchest-1.12.2-1.10.3.3.jar
11/21/2019  10:16 PM         1,567,926 VariedCommodities_1.12.2(21nov19).jar
03/05/2020  02:41 PM           178,994 Waystones_1.12.2-4.1.0.jar
10/02/2019  03:11 PM           413,940 WearableBackpacks-1.12.2-3.1.4.jar
09/07/2018  07:19 PM           951,198 wolfarmor-1.12.2-2.2.3.1798-universal.jar
05/31/2019  05:36 PM             8,945 xpfromharvest-1.12.2-1.1.0.jar
10/27/2019  04:22 PM            11,877 xptome-1.12.2-v1.1.4.jar

/plugins
03/12/2020  01:16 PM         1,380,336 LuckPerms-Sponge-5.0.56.jar
03/12/2020  01:16 PM         2,519,591 Nucleus-1.14.2-S7.1-MC1.12.2-plugin.jar
03/12/2020  01:17 PM         1,473,631 worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar
`

**Issue Description**

I'm trying to figure out why sponge-forge adds NBT tags and data into the region files of world saves. What is the purpose, and can it be disabled? Sometimes I will run into "Your chunks are too big" issues. I want to do what I can do to avoid that. Is it possible to disable?
![image](https://user-images.githubusercontent.com/1046026/76696826-dd071d00-664c-11ea-8f31-16c052688055.png)

[r.3.9.mca.zip](https://github.com/SpongePowered/SpongeCommon/files/4333853/r.3.9.mca.zip)

**Comment by gabizou** [comment] 2020-03-15 08:06
> I'm trying to figure out why sponge-forge adds NBT tags and data into the region files of world saves.

There's a few reasons:
- Supporting the ability to store custom data from plugins when requested (if plugins do add their own custom data, sponge does so by storing this under the `SpongeData` compound for the `Entity`/`BlockEntity` it's related to
- Sponge does add some of it's own custom data to properly track objects correctly, notably Worlds having their own `UUID` so as to better support multi-world of the same dimension types (so if you wanted multiple overworlds, nethers, ends, etc.)
- **Sponge also uses a per-chunk pos indexing table to keep track of block position owners and notifiers to enable plugins to know who did what with events**
- **A similar form is used on `Entity` instances with reference to the Player's `UUID` as an owner or notifier or both**

At this moment, it cannot be disabled after a considerable amount of discussion was made amongst the other leaders, disabling the saving of any aspects of the `SpongeData` would result in basically a crippled system that plugins would no longer be able to depend on.

What I mean by this system that plugins depend on is what some developers have come to know as the `PhaseTracker`. This system is 'by design' handling the interactions of every entity in the world with the blocks and block entities to facilitate a "chained cause and effect" tracking to translate to plugins when those related events are being thrown, handled, and processed. Essentially, this system is what allows for all protection plugins to work without having a fear of some random mod interacting with the world without us knowing (for the most part, there's some corner cases that can exist, but they're far few). There still is a configuration option for the `tracker` module in the global config, but that will not disable the chunk-level-specific data.



> Sometimes I will run into "Your chunks are too big" issues. I want to do what I can do to avoid that.

I've yet to ever see this warning or error, is it another mod adding this detection? Is this a Forge thing? Is this a Vanilla detection thing?

What I do know about tags getting too big is usually for `ItemStack`s having too many compounds, or that a tag can be restricted to having a certain size on packets, but I've yet to see anything about chunks being too big.



> Is it possible to disable?

It's possible for us to re-enabling the configuration option to disable storing the `owner`/`notifier` information, but again, that'd be allowing crippling the event system in place. I'll be honest that I myself forgot that we disabled the config for the storage, but I do remember the discussion at the time having those deciding factors.

Note: I'm only closing this issue because I'm deeming this as more of a support question and not an issue that needs fixing in code. If we do decide to re-enable the config, it'll be a commit that *references* this issue, but there's no *closing*/*reopening* of the issue. Discussion can continue!

**Closed as completed by gabizou** 2020-03-15 08:06 UTC
Labels: type: support
