### ISSUE TITLE
Inventory NoSuchElementException error

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2057] opened 2018-08-11 12:46 UTC
This issue was originally submitted by @Shmeeb in [SpongePowered/SpongeAPI#1894](https://github.com/SpongePowered/SpongeAPI/issues/1894).
___

![image](https://user-images.githubusercontent.com/141554/43991790-fad16ebc-9db2-11e8-8976-d653e42e6e89.png)

![image](https://user-images.githubusercontent.com/141554/43991794-07838cc6-9db3-11e8-808f-ab852d0f3ad7.png)

Running: 

![image](https://user-images.githubusercontent.com/141554/43991796-0e8a5982-9db3-11e8-872b-7ae24d18bf16.png)

**Comment by randombyte-developer** [comment] 2018-08-12 19:26
I experience that bug too. I thought I was doing something wrong and through a Sponge update something got tighter enforced. I "fixed" it by checking if the inventory has children `Inventory.hasChildren()` before calling the `getInventoryProperty` method.

Btw, I also am using this for InventoryTitle, maybe it's exclusive for that one, maybe not.

Edit: It appeared on Pixelmon. It was reported to happen *randomly*. Maybe Pixelmon is doing something weird.

**Comment by randombyte-developer** [comment] 2018-08-12 19:27
#2045 duplicate

**Comment by JBYoshi** [comment] 2018-08-17 02:46
Duplicate of #2045.

**Closed as completed by JBYoshi** 2018-08-17 02:46 UTC
Labels: type: bug, resolution: duplicate, system: inventory, version: 1.12 (u)
