### ISSUE TITLE
Class cast exception when using sponge -g reload

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#2143] opened 2018-11-24 17:11 UTC
**I am currently running**
- SpongeForge version:  7.1.4

class cast exception during sponge -g reload
error: https://pastebin.com/XhFfxdmQ
config: https://pastebin.com/XhFfxdmQ

- Plugins/Mods: Direwolf 2.3.0

Install Direwolf20, reload config without any changes made in config

Not sure, but one mod might have added entities/tiles that sponge added to his config. All mods are still present, but maybe sponge still fails on reloading to one of this entites in that config

**Comment by ImMorpheus** [comment] 2018-11-24 18:22
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2349

**Closed as completed by ImMorpheus** 2018-11-24 18:22 UTC
Labels: resolution: duplicate
