### ISSUE TITLE
console spammed with runaway phases

### ISSUE THREAD

**Issue by jackytuutykcaj** [SpongePowered/Sponge#1284] opened 2017-04-05 15:40 UTC
Original issue: https://github.com/NucleusPowered/Nucleus/issues/783#issuecomment-291882859

**Comment by gabizou** [comment] 2017-04-05 16:10
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1404

**Closed as completed by gabizou** 2017-04-05 16:10 UTC
Labels: resolution: duplicate
