### ISSUE TITLE
Keys.RESPAWN_LOCATIONS returns empty Optional

### ISSUE THREAD

**Issue by guilhermepyva** [SpongePowered/Sponge#2376] opened 2019-09-10 15:52 UTC
https://forums.spongepowered.org/t/get-bed-location/33542

player.get(Keys.RESPAWN_LOCATIONS) is just returning an empty Optional value

**Comment by ImMorpheus** [comment] 2019-09-13 16:42
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1824

(the root issue is the same)

**Closed as completed by ImMorpheus** 2019-09-13 16:42 UTC
Labels: resolution: duplicate
