### ISSUE TITLE
ConstructPortalEvent not firing for Nether Portals

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1916] opened 2018-05-19 17:34 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3095
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-47

**Issue Description**
As the title says, [ConstructPortalEvent](https://jd.spongepowered.org/7.0.0/?org/spongepowered/api/event/world/ConstructPortalEvent.html) is not firing during the creation of nether portals. Tested on both spongeforge and spongevanilla.

Test code below:
```Java
@Listener
public void onPortalCreate(ConstructPortalEvent event) {
    logger.info("Fired!");
}
```

**Comment by phit** [comment] 2018-05-19 18:49
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1559

**Closed as completed by phit** 2018-05-19 18:49 UTC
Labels: resolution: duplicate, version: 1.12 (u)
