### ISSUE TITLE
Bug : Empty block owner after falling

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1442] opened 2017-07-15 16:32 UTC
- SpongeVanilla version: SpongeVanilla version: 1.12-7.0.0-BETA-300
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

When player place block with gravity property, The player is the Owner of this block.
After the block falling, the block owner is empty.

[Video](https://www.youtube.com/watch?v=sNgKmmwietA)

**Comment by ImMorpheus** [comment] 2018-02-03 13:17
Same of https://github.com/SpongePowered/SpongeCommon/issues/1439

Not able to reproduce, the owner is present.

Test plugin:
```
    @Listener
    public void onPlace(ChangeBlockEvent.Place event) {
        System.out.println(event.getContext().get(EventContextKeys.OWNER));
    }
```

This can be closed.

**Comment by ryantheleach** [comment] 2018-02-03 13:49
After looking into this, I think this was the result of the `/sponge blockinfo` command, rather then the owner in the cause, which is correct as morph said. @ImMorpheus is working on a PR.

@lesbleu I know this took us some time to look into it, but it was nearly missed, The video was great, but having text instructions would have made this crystal clear.

**Comment by ImMorpheus** [comment] 2018-03-20 22:51
PR merged. This should be closed.

**Closed as completed** 2018-03-20 23:14 UTC
Labels: type: bug, system: world, system: phase tracker, version: 1.12 (u)
