### ISSUE TITLE
Torch/Lantern lighting broken in 1.17

### ISSUE THREAD

**Issue by Owexz** [SpongePowered/Sponge#3430] opened 2021-06-13 03:57 UTC
- SpongeVanilla version: 1.17-9.0.0-RC651, 1.17-9.0.0-RC659
- Java version: AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
- Operating System: Ubuntu 20.04
- Plugins/Mods: None

Torch and lantern lighting appears to be reduced to only the adjacent block after a period of time has passed (appears to be due to chunks loading/unloading). Mobs are able to spawn on the formerly illuminated areas. Does not appear to affect glowstone blocks.

![image](https://user-images.githubusercontent.com/1373064/121794746-3c881a00-cc4e-11eb-9ce8-7b988bd33352.png)

**Comment by MrSlimeDiamond** [comment] 2021-07-03 09:46
I can confirm this happens to me too. Giving a block update appears to make them function as they should.

Relogging after placing a torch will cause the torch to only light one block, since this un-loads the chunk and then loads it again.

I tried with another player in the same area and when I relogged the torch was not glitched, the torch most likely gets glitched when the chunk un-loads.

**Comment by Zidane** [comment] 2021-07-07 04:06
Closed in api-9

**Closed as completed by Zidane** 2021-07-07 04:06 UTC
Labels: type: bug, version: 1.18 (u)
