### ISSUE TITLE
Memory leak of listeners add by Inventory.builder()

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/Sponge#2037] opened 2018-08-02 15:42 UTC
**I am currently running**

 -  Minecraft: 1.12.2
 -  SpongeAPI: 7.1.0-SNAPSHOT-7105dfc
 -  SpongeForge: 1.12.2-2705-7.1.0-BETA-3361
 -  Minecraft Forge: 14.23.4.2736

 - Plugins/Mods: 
 - Plugins (6): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, InventoryEventListenerLeak, NPCs
 - Mods (11): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleCore, AppleSkin, JMFixer, JourneyMap, RandomPatches

**Issue Description**

It wrap the lambda function in a `RegisterdListener` and add it to event manager, but never release it.
The listener add by `Inventory.builder()` is never GC'd. 

So, if you dynamic register inventory listener and close the inventory .
It will memory leak.

It won't automatically remove the listener from memory even the inventory is technically not accessible by any one  anymore.

And you also have no way to manual release it, because it is wrapped, and you don't have a way to get the wrapped listener.

[This map is never being cleared](https://github.com/SpongePowered/SpongeCommon/blob/857128a9b8f121c5bdfb1a0e12374a84718690f9/src/main/java/org/spongepowered/common/event/SpongeEventManager.java#L93)

[step to reproduce](https://gist.github.com/james58899/0bc0a855504670c37684ac0a224bec33)

**Comment by Aaron1011** [comment] 2018-08-02 17:30
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/1874

**Closed as completed by Aaron1011** 2018-08-02 17:30 UTC
Labels: version: 1.12 (u)
