### ISSUE TITLE
[1.12] Creator : Liquid flow

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1439] opened 2017-07-15 00:03 UTC
- SpongeVanilla version: 1.12-7.0.0-BETA-300
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

When player place liquid, the player is the owner of liquid ![Example](https://image.noelshack.com/fichiers/2017/28/6/1500076494-2017-07-15-01-54-34.png). 
And the liquid flowing, the owner of liquid is empty ![Example](https://image.noelshack.com/fichiers/2017/28/6/1500076595-2017-07-15-01-54-43.png)

It's a bug ? Because I want to cancel this event only when player flow liquid.

**Comment by JBYoshi** [comment] 2017-08-05 20:16
@SpongePowered/developers Is this intended behavior?

**Comment by ryantheleach** [comment] 2018-02-01 00:16
@lesbleu Are you able to check on the latest SF / SV?

Additionally, when I mentioned it to blood, he says he is having no issue at listening at ChangeBlockEvent.pre and that the context is complete in GriefPrevention.

Can you supply a test plugin that demonstrates the issue in order to clarify? I assume you mean that the metadata that Sponge logs regarding player notifier/creator is incorrect, and that you are listening to ChangeBlockEvent.place or something?

**Comment by bloodmc** [comment] 2018-02-01 00:19
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/block/ChangeBlockEvent.java#L97

The proper user will be in event. Just check if source is liquid or context (once updated to support liquid flow).

**Comment by ryantheleach** [comment] 2018-02-03 14:48
Reopening this. `/sponge blockinfo` was used by @ImMorpheus after his PR, the PR only fixes the sand falling not having owners, but doesn't correct the water not having owners. This still issue still needs to be addressed. @bloodmc I know we tested this ages and ages ago with GP, but since then there has been pre events and all sorts added. 

What's the correct behavior for water and owners/notifiers?

**Comment by ImMorpheus** [comment] 2018-03-20 22:51
PR merged. This should be closed.

**Closed as completed** 2018-03-20 23:14 UTC
Labels: system: event, status: input wanted, system: world, system: phase tracker
