### ISSUE TITLE
Water placement is mucked-up 699+

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#371] opened 2015-10-15 05:57 UTC
Forge 1519  +0 mods , water placement is normal
forge + sponge Dev-693 mod, water placement is normal
sponge-1.8-1519-2.1DEV-699 through to DEV-706  mods, water placement is mucked-up.

Placing a water-bucket on open areas results in about 50% of the time, a stationary water block appearing, 45% of the time just a flicker and nothing appearing, and 5% of the time, the water runs a block or few - yet the water bucket remains full.  It almost never ever results in a ghost-water block when placing on growing grass, just flickers.  Appears to be all client-ghosting issues.

**Comment by gabizou** [comment] 2015-10-15 06:08
Duplicate of #370 which was fixed with [this commit](https://github.com/SpongePowered/SpongeCommon/commit/a90e60b3a41e7d07b8ce590eefee8bcd83c1b2e2)

**Closed by gabizou** 2015-10-15 06:08 UTC

**Comment by theboomer** [comment] 2015-10-15 06:20
Excellent.  It was strange that it mucked up in 707 when testing before posting (tested 706, 699, 707, 693 order) but yeah, 707 is actually fine now.  Sorry for misfire
