### ISSUE TITLE
CauseTracker Issues

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#1523] opened 2017-09-11 20:28 UTC
This is a list of cause tracker issues I noticed:

- [x] MoveEntityEvent.Teleport 
    - Context TeleportType is missing sometimes (enderpearl/chorus fruit).
   - TP from End -> World is missing causes.
   - Enderpearl (no player in cause)

- [ ] SpongeCommonFactory#callChangeBlockEventModifyLiquidBreak wrong context. Should be LIQUID_BREAK or FLOW not LIQUID_MIX.

- [ ] Leaf Decay: LocatableBlock is in Cause twice. (also SPAWN_TYPE context on ChangeBlockEvent seems weird)

- [x] indirect BlockBreak/Place (e.g. Sand falling by breaking block beneath it)
   - player is not in cause nor in context as notifier or smth. else. (owner does not count)

... and more?

**Comment by lesbleu** [comment] 2017-09-11 20:33
I have already started to report CauseTracker bugs in this [issue](https://github.com/SpongePowered/SpongeCommon/issues/1521).

**Comment by ryantheleach** [comment] 2017-11-16 16:19
Leaf Decay is leaking.

**Comment by gabizou** [comment] 2017-11-17 01:04
@phit could you test some of these?

**Comment by ImMorpheus** [comment] 2018-01-30 17:56
Tested on SpongeForge bleeding branch.
I was able to reproduce:
indirect BlockBreak/Place (player not in the cause) 
LocatableBlock is in Cause twice in Leaf Decay
SpongeCommonFactory#callChangeBlockEventModifyLiquidBreak wrong context.
@RedNesto is doing the MoveEntityEvent.Teleport

**Comment by phit** [comment] 2018-04-19 22:45
https://github.com/SpongePowered/SpongeCommon/pull/1742 & https://github.com/SpongePowered/SpongeCommon/pull/1775 were merged

**Closed as completed by phit** 2018-04-19 22:45 UTC
Labels: type: bug, system: phase tracker, version: 1.12 (u), status: pr pending
