### ISSUE TITLE
java.lang.IllegalStateException: Overworld settings missing

### ISSUE THREAD

**Issue by RadiatedExodus** [SpongePowered/Sponge#3641] opened 2022-02-27 16:38 UTC
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.0.0-RC1081

### Operating System

Linux (Arch Linux)

### Java Version

java version "1.8.0_301" Java(TM) SE Runtime Environment (build 1.8.0_301-b09) Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

### Plugins/Mods

```shell
Mods:
- appliedenergistics2-8.4.7.jar
- [Forge-1.16.5]+Hololive+Records+(4.0).jar
- [Forge-1.16.5]+Hololive+Relics+(6.1.1).jar
- Smol+Holos+1.2.0.jar
- spongeforge-1.16.5-36.2.5-8.0.0-RC1081-universal.jar

Plugins:
- N/A
```

### Describe the bug

I keep getting the following error after starting the server for a while, it crashes the entire server and I would have to restart it again, only for it to crash again after a while and so on...
```
java.lang.IllegalStateException: Overworld settings missing
        at net.minecraft.world.gen.settings.DimensionGeneratorSettings.<init>(DimensionGeneratorSettings.java:73) ~[?:?]
        at net.minecraft.world.gen.settings.DimensionGeneratorSettings.bridge$copy(DimensionGeneratorSettings.java:1569) ~[?:?]
        at net.minecraft.world.storage.ServerWorldInfo.redirect$znn000$impl$ignorePluginDimensionsWhenWritingWorldGenSettings(SourceFile:2011) ~[?:?]
        at net.minecraft.world.storage.ServerWorldInfo.func_237370_a_(SourceFile:250) ~[?:?]
        at net.minecraft.world.storage.ServerWorldInfo.func_230411_a_(SourceFile:231) ~[?:?]
        at net.minecraft.world.storage.SaveFormat$LevelSave.func_237288_a_(SaveFormat.java:341) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:3869) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:3966) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
```

### Link to logs

https://paste.gg/p/anonymous/c15b6e2921244845a55bfa1b8e77755c

**Comment by RadiatedExodus** [comment] 2022-02-27 16:43
- The server launches fine at first, but after some time it would crash as explained above.
- I am migrating this server from a Purpur/Paper server to SpongeForge since me and my friends would like to use some Forge mods.
- ~~The issue does reproduce on a completely new fresh configuration (basically running the server on a empty folder and accepting the eula, after some time the same thing occurs, it crashes with the same error)~~ Needs more testing, **no it does not reproduce on a server where theres no plugins or mods other than SpongeForge**
- We used to use a hosting, but the hosting does not support changing Java versions (effectively not letting us to use SpongeForge), as a result we were forced to self-host it, we used [ZeroTier One](https://zerotier.com) to create a virtual private network, I don't know if this is related but I think it's better if I point this out. The reason we use ZeroTier is because we cannot port forward due to isp issues.

**Comment by RadiatedExodus** [comment] 2022-02-28 05:51
After further testing, this issue only happens when theres other Forge mods present, perhaps a incompatible mod?

Repro video: https://youtu.be/JBiOQsedHq0
Complete crash log (includes all logs I can find): https://paste.gg/p/anonymous/4bb80f63c7824ec0836ba781426d76eb

Mods present:
- appliedenergistics2-8.4.7.jar
- [Forge-1.16.5]+Hololive+Records+(4.0).jar
- [Forge-1.16.5]+Hololive+Relics+(6.1.1).jar
- Smol+Holos+1.2.0.jar
- spongeforge-1.16.5-36.2.5-8.0.0-RC1081-universal.jar

Plugins present:
- N/A

**Comment by gabizou** [comment] 2022-03-13 06:33
Does this happen with a fresh server not previously running Purpur (basically fresh worlds and such)?

**Comment by RadiatedExodus** [comment] 2022-03-13 09:01
@gabizou 
No, it doesn't.

**Comment by ShunL12324** [comment] 2022-04-01 14:12
Encounter the same issue
[crash report](https://gist.github.com/Eric-liucn/22e98ac19cc9fc5aa062a8a75475dc39)

**Comment by KaelaniRevyruun** [comment] 2022-09-10 14:37
adding my server to the list... Newly installed minecraft 1.16.5 server crashes after 5 minutes when booting up with spongeforge and any mods it seems.

I'm using the custom technic modpack "Halsion Reach Modded Nation Project" for my server. Adding Luckperms renders the server hanging once it finishes loading but that will be a fix for another day XD

Crash is always 5 minutes after bootup finishes, and is always "overworld settings missing".

**Comment by YUCLing** [comment] 2022-11-27 02:01
Same here.

And it happens on server stopping too.
<details>
<summary>Detailed Information</summary>

### Environment
Rocky Linux 9.0 (Blue Onyx)

### Java Version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

### Sponge Version
1.16.5-36.2.5-8.1.0-RC1188

### Crash Report
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022/11/27 上午2:27
Description: Exception in server tick loop

java.lang.IllegalStateException: Overworld settings missing
	at net.minecraft.world.gen.settings.DimensionGeneratorSettings.<init>(DimensionGeneratorSettings.java:73) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.gen.DimensionGeneratorSettingsAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.levelgen.WorldGenSettingsMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.levelgen.WorldGenSettingsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.settings.DimensionGeneratorSettings.bridge$copy(DimensionGeneratorSettings.java:1569) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.gen.DimensionGeneratorSettingsAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.levelgen.WorldGenSettingsMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.levelgen.WorldGenSettingsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.storage.ServerWorldInfo.redirect$zok000$impl$ignorePluginDimensionsWhenWritingWorldGenSettings(SourceFile:2010) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.PrimaryLevelDataAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.storage.PrimaryLevelDataMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.PrimaryLevelDataMixin,pl:mixin:A}
	at net.minecraft.world.storage.ServerWorldInfo.func_237370_a_(SourceFile:250) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.PrimaryLevelDataAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.storage.PrimaryLevelDataMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.PrimaryLevelDataMixin,pl:mixin:A}
	at net.minecraft.world.storage.ServerWorldInfo.func_230411_a_(SourceFile:231) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.PrimaryLevelDataAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.storage.PrimaryLevelDataMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.PrimaryLevelDataMixin,pl:mixin:A}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237288_a_(SaveFormat.java:341) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.LevelStorageSource_LevelStorageAccessAccessor,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.LevelStorageSource_LevelStorageAccessMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:4372) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:mixins.sponge.accessors.json:server.level.ServerLevelAccessor,pl:mixin:APP:mixins.mirage.json:level.ServerLevelMixin,pl:mixin:APP:mixins.sponge.entityactivation.json:world.server.ServerLevelMixin_EntityActivation,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.level.ServerLevelMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.level.ServerLevelMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.level.ServerLevelMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:4461) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.constant$zgf000$getSaveTickInterval(MinecraftServer.java:4407) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.gen.settings.DimensionGeneratorSettings.<init>(DimensionGeneratorSettings.java:73) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.gen.DimensionGeneratorSettingsAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.levelgen.WorldGenSettingsMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.levelgen.WorldGenSettingsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.gen.settings.DimensionGeneratorSettings.bridge$copy(DimensionGeneratorSettings.java:1569) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.gen.DimensionGeneratorSettingsAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.levelgen.WorldGenSettingsMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.levelgen.WorldGenSettingsMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.storage.ServerWorldInfo.redirect$zok000$impl$ignorePluginDimensionsWhenWritingWorldGenSettings(SourceFile:2010) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.PrimaryLevelDataAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.storage.PrimaryLevelDataMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.PrimaryLevelDataMixin,pl:mixin:A}
	at net.minecraft.world.storage.ServerWorldInfo.func_237370_a_(SourceFile:250) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.PrimaryLevelDataAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.storage.PrimaryLevelDataMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.PrimaryLevelDataMixin,pl:mixin:A}
	at net.minecraft.world.storage.ServerWorldInfo.func_230411_a_(SourceFile:231) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.PrimaryLevelDataAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.world.level.storage.PrimaryLevelDataMixin_API,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.PrimaryLevelDataMixin,pl:mixin:A}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237288_a_(SaveFormat.java:341) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.accessors.json:world.level.storage.LevelStorageSource_LevelStorageAccessAccessor,pl:mixin:APP:mixins.sponge.core.json:world.level.storage.LevelStorageSource_LevelStorageAccessMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:4372) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:mixins.sponge.accessors.json:server.level.ServerLevelAccessor,pl:mixin:APP:mixins.mirage.json:level.ServerLevelMixin,pl:mixin:APP:mixins.sponge.entityactivation.json:world.server.ServerLevelMixin_EntityActivation,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.level.ServerLevelMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.level.ServerLevelMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.level.ServerLevelMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zcn000$tracker$addPhaseTrackerToCrashReport(MinecraftServer.java:4745) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:969) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:256) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.dedicated.DedicatedServerAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.dedicated.DedicatedServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.dedicated.DedicatedServerMixin_Tracker,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:664) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.mirage.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.14.0-70.30.1.el9_0.x86_64
	Java Version: 16, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 812967448 bytes (775 MB) / 1879048192 bytes (1792 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms1G -Xmx8G
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
		/spongeforge-1.16.5-36.2.5-8.1.0-RC1188-universal.jar spongeforge TRANSFORMATIONSERVICE 
		/spongeforge-1.16.5-36.2.5-8.1.0-RC1188-universal.jar superclass_change TRANSFORMATIONSERVICE 
		/spongeforge-1.16.5-36.2.5-8.1.0-RC1188-universal.jar access_widener TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		spongeapi@1.16.5-36.2.5-8.1.0-RC1188
		sponge@1.16.5-36.2.5-8.1.0-RC1188
		java_plain@1.16.5-36.2.5-8.1.0-RC1188
	Mod List: 
		forge-1.16.5-36.2.39-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.6-14.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.6            |DONE      |Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.4-10.jar                    |Titanium                      |titanium                      |3.2.8.4             |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-420.3.jar                          |Botania                       |botania                       |1.16.5-420.3        |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-8.4.7.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.7               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		[1.16.5]+SecurityCraft+v1.9.3.1.jar               |SecurityCraft                 |securitycraft                 |v1.9.3.1            |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.16.5-6.2.1.14.jar                  |Flux Networks                 |fluxnetworks                  |6.2.1.14            |DONE      |Manifest: NOSIGNATURE
		null                                              |SpongeAPI                     |spongeapi                     |8.0.0               |DONE      |Manifest: NOSIGNATURE
		null                                              |Sponge                        |sponge                        |8.0.0               |DONE      |Manifest: NOSIGNATURE
		Nucleus-3.0.0-BETA7-MC1.16.5-SpongeAPI8.1-plugin.j|Nucleus                       |nucleus                       |3.0.0-BETA7         |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar               |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.16.5-1.101.0.jar                     |CC: Tweaked                   |computercraft                 |1.101.0             |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		LocaleAPI-2.3.0-S8.0.0-RELEASE.jar                |LocaleAPI                     |localeapi                     |2.3.0-S8.0.0-RELEASE|DONE      |Manifest: NOSIGNATURE
		TablistBoard-1.1.0-S8.0.0-RELEASE.jar             |TablistBoard                  |tablistboard                  |1.1.0-S8.0.0-RELEASE|DONE      |Manifest: NOSIGNATURE
		LuckPerms-Sponge-5.4.52.jar                       |LuckPerms                     |luckperms                     |5.4.52              |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.4.0-13.jar            |Immersive Petroleum           |immersivepetroleum            |3.4.0-13            |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		spongeforge-1.16.5-36.2.5-8.1.0-RC1188-universal.j|SpongeForge                   |spongeforge                   |1.16.5-36.2.5-8.1.0-|DONE      |Manifest: NOSIGNATURE
		Mirage-forge.jar                                  |Mirage                        |mirage                        |1.5.1-forge         |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.5.2.22.jar                     |CoFH Core                     |cofh_core                     |1.5.2.22            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.16.5-1.5.2.30.jar            |Thermal Series                |thermal                       |1.5.2.30            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_innovation-1.16.5-1.5.0.4.jar             |Thermal Innovation            |thermal_innovation            |1.5.0.4             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_cultivation-1.16.5-1.5.0.4.jar            |Thermal Cultivation           |thermal_cultivation           |1.5.0.4             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.16.5-1.5.2.16.jar             |Thermal Expansion             |thermal_expansion             |1.5.2.16            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		XConomy-Sponge8-2.19.5.jar                        |XConomy                       |xconomy                       |2.19.5-Sponge8      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 34acbd1f-b614-48ae-8f67-9a8b72b9c1cf
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:industrialforegoing (incompatible), mod:titanium (incompatible), mod:botania, mod:mekanism, mod:curios, mod:patchouli (incompatible), mod:appliedenergistics2 (incompatible), mod:securitycraft, mod:fluxnetworks, mod:mekanismtools, mod:computercraft, mod:mekanismgenerators, mod:immersivepetroleum, mod:immersiveengineering, mod:forge, mod:spongeforge, mod:cofh_core, mod:thermal, mod:thermal_innovation (incompatible), mod:thermal_cultivation (incompatible), mod:thermal_expansion
	Is Modded: Definitely; Server brand changed to 'forge/spongeforge'
	Type: Dedicated Server (map_server.txt)
```
</details>

**Comment by Harjas2102** [comment] 2022-12-28 20:06
Having a very similar issue detailed in this unanswered thread on the sponge forums
https://forums.spongepowered.org/t/1-16-5-custom-modpack-server-crash-on-launch/41134/2

**Comment by AgentLoneStar007** [comment] 2023-03-22 12:31
Having a similar issue on Arch Linux using PaperMC with an old server I'm trying to resurrect. The world used the Terralith and Amplified Nether datapacks, but I don't want to use them anymore. So I've removed them, and their entries in `level.dat`. Still getting the following error: https://gist.github.com/AgentLoneStar007/b82eda18a6224c17fa28655aa09aab1d.

**Comment by McKpol** [comment] 2023-07-23 10:09
If someone still have this error start
there is one my solution:
If you started server -> stopped server AND then added mods
to solution this error delete world directory!

**Comment by Azraeel** [comment] 2023-08-20 09:40
Update on this issue, Applied Energistics 2 seems to be the issue. I tested this as @RealEthanPlayzDev only mod that i had in common was that specific one with that removed the issue immediately disappeared and i left it running for about 2-3 hours,
with no more overworld settings errors appearing.

**Comment by Spliterash** [comment] 2023-11-23 16:04
+1. In my case world be corrupted, and im be need load backup, and nobody can join server. 
After some time server crash with java.lang.IllegalStateException: Overworld settings missing.
Also have AE2

**Comment by cafe41** [comment] 2024-03-24 16:07
Go world folder, then go level.dat and delete the datapack from the server, you can also active vanilla mode and install them again later

**Comment by ImMorpheus** [comment] 2024-05-13 18:25
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1

**Closed as completed by ImMorpheus** 2024-05-13 18:25 UTC
Labels: type: bug, status: needs triage
