### ISSUE TITLE
Custom Inventory items cloned if event is cancelled

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#1175] opened 2017-01-29 19:17 UTC
This issue was brought up in the topic https://forums.spongepowered.org/t/custom-inventories/17219

When some inventory events are cancelled if an item is clicked in a custom inventory it is sometimes cloned and put into a random slot in the users inventory or is dropped on the ground. If the action of the item clicked is to clear the inventory, everything is cleared apart from the clicked item.

**Comment by bloodmc** [comment] 2017-03-02 17:22
@Faithcaio please look into this.

**Comment by Faithcaio** [comment] 2017-03-02 19:26
@OblivionNW 
first of all:
 - `slot.peek().get().setQuantity(0);` only modifies a copy of the ItemStack in the inventory you always have to offer ItemStacks back.
 - When you cancel an event there is no need to set all the transactions to invalid.

And I am unable to reproduce the issues you are describing. (using latest SpongeForge)
If it still happens it would be nice if you could simplify your listener so there are no additional dependencies.

**Comment by ghost** [comment] 2017-03-04 14:22
My issue seems to be related to #1229 where if instead I close the inventory, the item is also dropped.

**Comment by bloodmc** [comment] 2017-03-26 03:14
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/2406e2f0114c0955b0910dff7001456a9a1e1b52

**Closed as completed by bloodmc** 2017-03-26 03:14 UTC
Labels: system: event, system: inventory
