### ISSUE TITLE
tile-entity-unload option

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/Sponge#1587] opened 2017-11-07 23:16 UTC
I wanted to try out the `tile-entity-unload` option, after enabling it and restarting the server it did still show
```
[00:00:31] [Thread Locksmith Watchdog/INFO] [threadlock]:  - java.util.ArrayList.indexOf(ArrayList.java:317)
[00:00:31] [Thread Locksmith Watchdog/INFO] [threadlock]:  - java.util.ArrayList.contains(ArrayList.java:300)
[00:00:31] [Thread Locksmith Watchdog/INFO] [threadlock]:  - java.util.ArrayList.batchRemove(ArrayList.java:720)
[00:00:31] [Thread Locksmith Watchdog/INFO] [threadlock]:  - java.util.ArrayList.removeAll(ArrayList.java:690)
```
in the thread although `removeAll` should be `removeIf`.

Did I understand something wrong or is this not implemented in this sponge version?

**Profiling of 3 different servers:**
![](https://i.imgur.com/Sl5da8h.jpg)
![](https://i.imgur.com/p1xcJsW.jpg)
![](https://i.imgur.com/iwB6P3D.jpg)

**I am currently running...**
- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2691
- Java version: 1.8.0_144
- Operating System: Ubuntu

**Comment by liach** [comment] 2017-11-08 05:07
Isn't this option removed in build 2627? You might try regenerating and reedit config to fix this error.

**Comment by Sir-Will** [comment] 2017-11-09 14:47
Yep, it's gone after regenerating it. Why was it even available?

**Comment by liach** [comment] 2017-11-09 14:51
it was there before forge added this to 1.10 (originally the optimization is java 8 only, now it also works on java 6 so forge added it)

**Comment by phit** [comment] 2017-11-09 14:54
because it wasn't backported in Forge for a while, once it was backported in Forge it was removed 
added old impl in https://github.com/SpongePowered/SpongeCommon/commit/c352510dff8293fa1b3cab730605baf302af0bfb
second impl https://github.com/SpongePowered/SpongeCommon/commit/57bdb034917eef676e1340888232b37d16543a9b
and then removed here https://github.com/SpongePowered/SpongeCommon/commit/0a464af0434287b88fea6b08e3cbe5bd73a3102b

edit: liach beat me to it

**Comment by Sir-Will** [comment] 2017-11-09 15:09
Ah okay. Is this always enabled or is there a config option which I couldn't find?

**Comment by phit** [comment] 2017-11-09 15:10
always enabled https://github.com/MinecraftForge/MinecraftForge/commit/16127a61c797c80563ab424f1eecdbb1f7ca6bc1

**Comment by Sir-Will** [comment] 2017-11-09 15:15
Alright, thanks for the information. Seems to not help a lot then as I'm still getting a lot of lag spikes because of tile unloads with forge build 2477. :/

**Comment by liach** [comment] 2017-11-09 20:30
You might need to post the time analysis if you want to have it resolved.

**Comment by Sir-Will** [comment] 2017-11-09 21:10
Hm, what do you mean?

**Comment by liach** [comment] 2017-11-09 23:58
Show your profiler time report on different parts of code. The cause may be different.

**Comment by Sir-Will** [comment] 2017-11-10 02:18
Added it to this issue: https://github.com/MinecraftForge/MinecraftForge/issues/4505#issue-272611679

**Comment by liach** [comment] 2017-11-10 02:26
It is still a sponge issue, with injections before tile entity unloading.

**Comment by Sir-Will** [comment] 2017-11-10 02:37
@phit can this issue then be reopened?

**Comment by Sir-Will** [comment] 2017-11-20 10:11
Is there any way to speed up this issue? This is a major issue for us and makes older 1.10 servers almost unplayable.

**Comment by Aaron1011** [comment] 2018-04-23 15:12
Does this still occur on 1.12?

**Comment by Sir-Will** [comment] 2018-04-23 15:27
I didn't see it occur on 1.12 yet.

**Comment by phit** [comment] 2018-04-23 16:30
closing this then, 1.10 is no longer supported, let us know when you see anything like this on 1.12 and the issue can be reopened

**Closed as completed by phit** 2018-04-23 16:30 UTC
Labels: version: 1.10 (u), type: performance
