### ISSUE TITLE
NullPointerException loading configuration

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#1142] opened 2017-01-17 21:29 UTC
I have ran into an issue loading configs (Initial discussion: https://forums.spongepowered.org/t/nullpointerexception-loading-configuration-after-initial-save/16648/7). 

I believe this may be an issue in Sponge.

**Comment by simon816** [comment] 2017-01-21 16:53
Here's the sample peice of code that causes the NPE:
```java
DataTranslators.CONFIGURATION_NODE.translate(SimpleConfigurationNode.root().setValue("test"));
```

**Comment by OblivionNW** [comment] 2017-01-28 18:47
https://www.bountysource.com/issues/41059044-nullpointerexception-loading-configuration. It's not much but it's some incentive.

**Comment by codeHusky** [comment] 2017-01-29 19:39
This is a result of trying to get the value of the root of the config as far as i've determined. Dumb mistake really 👍

**Comment by codeHusky** [comment] 2017-01-29 20:51
#Correction
As it turns out, the issue was more of setting a location as a key and trying to get it back. 
Still possibly an issue but not sure quite yet

**Comment by Deamon5550** [comment] 2017-01-30 05:51
Yeah there are definitely some issues with the ConfigurateTranslator when the keys aren't present. I also don't think it is translating lists entirely correctly.

**Comment by bloodmc** [comment] 2017-03-02 17:22
@gabizou Can you look into this?

**Comment by dualspiral** [comment] 2017-05-11 22:35
Yes, the ConfigurateTranslator has a lot of problems with it. As part of https://github.com/SpongePowered/SpongeAPI/issues/1543, I've spent a bit of time looking into it and have found myself re-writing a fair amount of it. I froze work on it because @Deamon5550 indicated that he plans to change what DataViews store - so I stopped pending such a change, but now I realise it's still important that I continue and fix it.

I'll resume work on it in the next couple of days and get parts of it committed, based on my current schedule, it'll probably be Saturday, but may get a chance tomorrow.

**Comment by phit** [comment] 2018-01-17 05:52
@dualspiral did this ever get merged?

**Comment by dualspiral** [comment] 2018-01-17 07:43
No, it’s a rabbit hole. There is more to this than I thought, it then fell by the wayside. I’ll try to resume when I get chance, I had forgotten about this.

**Comment by ImMorpheus** [comment] 2020-08-16 08:54
Fixed by https://github.com/SpongePowered/SpongeCommon/pull/2603

A test was also added for this to avoid any regression:

https://github.com/SpongePowered/SpongeCommon/blob/16b0cfa3572f9946a94a3ece56e56c14d4189503/src/test/java/org/spongepowered/common/data/translator/ConfigurateDataViewTest.java#L190

**Closed as completed by ImMorpheus** 2020-08-16 08:54 UTC
Labels: system: data, status: pr pending
