### ISSUE TITLE
MoveEntityEvent not fired for Projectiles and Items

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#2348] opened 2019-08-13 08:41 UTC
**I am currently running**
- SpongeForge version: 7.1.7-RC3881
- SpongeVanilla version: 7.1.7-RC265
- Java version: 1.8.0_162
- Operating System: Windows 10

- Plugin:
```java
@Listener
public void onMoveEntity(MoveEntityEvent e, @Getter("getTargetEntity") Entity y) {
	TestPlugin.LOGGER.info("move: " + y.getType().getId());
}
```

**Issue Description**
`MoveEntityEvent` is not fired for `Projectile`s and `Item`s. Probably caused by: https://github.com/SpongePowered/SpongeCommon/blob/b1638839846a2740e2e5a95f5fe8b7c77341ccd8/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L911

**Comment by JBYoshi** [comment] 2019-08-16 17:14
Removing the two `instanceof` checks seems to have no harmful side effects.

It was originally introduced by blood in https://github.com/SpongePowered/SpongeCommon/commit/0e3bc55efc07816a5360d0330d104ab532e507d4. @bloodmc Any particular reason for that?

**Comment by gabizou** [comment] 2019-08-16 17:45
I believe it originally was added because of how much spam would be caused by adding those move events. The events themselves are not costly to construct, but the amount of events being thrown on a large server and plugins processing them would exceed current expectations (picture a high density chest containing 200+ types of items dropping all 200+ item stacks as new entities, and each tick a new move event being thrown for each of them, and GP now processing them).

**Comment by parlough** [comment] 2019-08-16 22:31
This is a good point, especially for items. I feel as though tracking an items movement isn't necessarily that important, but projectiles definitely have more use cases while being quite a lot more common.

I'm thinking we could for now at least enable the event for projectiles. 

@Yeregorix What is your use case for tracking item entity movement?

**Comment by Yeregorix** [comment] 2019-08-17 08:26
I'm developing a custom region manager for a private server which need to detect when an entity enter or exit a region.
I understand the impact on performance but first, I think it's the responsibility of plugin developers to not do heavy things in this event. Secondly, the choice is a lot arbitrary. I can't understand it at all for Projectiles. I can understand it slightly for Items but it no longer make sense if you have another mod which add new entities way worse than Items.
I know it's not every day we need to listen for Items movements. A good compromise could be to make it configurable globally/per world, and disabled by default.

**Comment by ImMorpheus** [comment] 2019-08-18 13:36
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2004

**Closed as completed by ImMorpheus** 2019-08-18 13:36 UTC
Labels: resolution: duplicate, status: input wanted
