### ISSUE TITLE
Server NPE crash in EntityTypeRegistryModule.getForClass

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/Sponge#1380] opened 2017-05-31 00:00 UTC
**I am currently running...**
- SpongeForge version:  spongeforge-1.11.2-2282-6.1.0-BETA-2357.jar
- SpongeVanilla version: n/a
- Java version: 1.8.0_121
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, Backpacks!, SpongeAPI, SpongeForge, FoamFixCore, Animania, Just Enough Items, AppleSkin, Astral Sorcery, Alternate Terrain Generation, Psi, Quark, AutoRegLib, Battle Towers, Baubles, BetterBedrockGen, BD Lib, Bed Bugs, Better Achievements, Better Builder's Wands, Better Foliage, Better Than Mending, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Chameleon Creepers, Chisel, Chisels & Bits, Clarity, Cooking for Blockheads, CosmeticArmorReworked, Crafting Tweaks, CraftTweaker JEI Support, Crafttweaker, Dark Utilities, Earthworks, Elevator Mod, Embers, Extra Bit Manipulation, Felling, Flat Colored Blocks, FoamFix, Forestry, Forgelin, GenDustry, Pressure Pipes, Advanced Generators, Fishing Net Mod, Harvest, Hopper Ducts, Waila, InfiniteFluids, Inventory Pets, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, LLibrary, Literal Ascension, MineTweakerRecipeMaker, Morpheus, Mystical Agriculture, NetherPortalFix, No Mob Spawning on Trees, NoMoreRecipeConflict, Pam's HarvestCraft, Refined Relocation, Reliquary, RFTools, RFTools Control, Roots 2, Rope Bridge, Ruins Mod, Soul Shards - The Old Ways, Spartan Shields, The One Probe, Tiny Progressions, TOP Addons, Tough As Nails, Waddles, Waystones, Wolf Armor and Storage, WorldEdit, XNet, AntiWDL, Broadcast, GriefPrevention, LuckPerms, Nucleus, NuVotifier, Server Backup, VotifierListener, Total Economy

**What is the expected result?**
No crash

**What is the current result?**
NPE due to Sponge entity handling

Crash report:
https://gist.github.com/LemADEC/8c6cf9eaf302c143d964a0eb76ff6b80
```
java.lang.NullPointerException: Ticking block entity
	at org.spongepowered.common.registry.type.entity.EntityTypeRegistryModule.getForClass(EntityTypeRegistryModule.java:255)
	at net.minecraft.tileentity.MobSpawnerBaseLogic.readEntityFromCompoundAtWorld(MobSpawnerBaseLogic.java:604)
	at net.minecraft.tileentity.MobSpawnerBaseLogic.redirect$onConstruct$zik000(MobSpawnerBaseLogic.java:584)
	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98278_g(MobSpawnerBaseLogic.java:109)
	at net.minecraft.tileentity.TileEntityMobSpawner.func_73660_a(SourceFile:91)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:230)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2830)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2817)
	at net.minecraft.world.World.func_72939_s(World.java:6508)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
```

Server logs:
https://gist.github.com/LemADEC/95d8a0d724e50abc4df2c645a2766be4

Issue was reproduced twice from same spawner block, so we removed it from the world.

**Comment by ImMorpheus** [comment] 2018-07-24 21:29
Trying to follow the stacktrace, it looks like it's crashing here 
https://github.com/SpongePowered/SpongeCommon/blob/cf17df1c6e1b26cb6c0bd1b0bbb5469232a24186/src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java#L252

So clazz is null and it was passed here
https://github.com/SpongePowered/SpongeCommon/blob/cf17df1c6e1b26cb6c0bd1b0bbb5469232a24186/src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinMobSpawnerBaseLogic.java#L99

But that's no longer the case since it was fixed by https://github.com/SpongePowered/SpongeCommon/commit/20d85cedd4b856fb9f4dd689006cfa40e7f537f3

Which was trying to fix https://github.com/SpongePowered/SpongeForge/issues/1422

Looks like 1422 was caused by Ruins (which is also present in the mod list of this issue).

I think this is a duplicate and it can be closed.

**Comment by ImMorpheus** [comment] 2018-07-29 16:30
@phit Thoughts ?

**Comment by phit** [comment] 2018-07-30 10:17
if it pops up again, can always reopen

**Closed as completed** 2018-07-30 10:17 UTC
Labels: version: 1.11 (u)
