### ISSUE TITLE
BreedEntityEvent, CauseTracker returning more than expected.

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#2121] opened 2018-10-19 02:39 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3477
- Sponge API **7.2.0** << this is not a typo

I have this listener setup:

@Listener
public void onBreedEntity(final BreedEntityEvent.Breed event) {
      final List<Animal> parents = event.getCause().allOf(Animal.class);      
}

Issue:  the parents list is returning 3 animals, both parents and then a copy of the 1st parent in the list.

Debug:  I verified the duplication by comparing UUID's of each parent.

 System.out.println("Parent 0 UUID: " + parents.get(0).getUniqueId());
 System.out.println("Parent 1 UUID: " + parents.get(1).getUniqueId());
 System.out.println("Parent 2 UUID: " + parents.get(2).getUniqueId()); //Fail:  this always return Parent 0's UUID, not the child, what is parent 2?

Unknown cause.

**Comment by ImMorpheus** [comment] 2018-10-26 18:06
Not able to reproduce on stable-7 branch.

Fixed by https://github.com/SpongePowered/SpongeCommon/commit/19929c7d392ea7029e0a432b86dd1e54c2fdedfb

**Closed as completed by ImMorpheus** 2018-10-26 18:06 UTC
Labels: system: event, version: 1.12 (u), system: entity

**Comment by Dockter** [comment] 2018-10-26 19:45
This is because @Zidane and I fixed in with the 3497 commit.
