### ISSUE TITLE
Non player entity tracking not functioning correctly for multiple events

### ISSUE THREAD

**Issue by kencinder** [SpongePowered/Sponge#2126] opened 2018-10-20 23:18 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.2
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_181
- Operating System: Debian 9.5

- Plugins: BetterChunkLoader, GriefPrevention, LuckPerms, MMCReboot, Nucleus, SleepVote, spark

Sources returned in a griefprevention debug are showing `none` for non-player entities. `block-break`, `block-place`, `explosion`, `entity-damage`, `explosion-surface` are all coming back as `none`, movement related checks all seem to be working OK returning the correct source.

In the debug linked to below, I caused a creeper to explode and damage a spider next to it, all related checks show the creeper as being `none` for source.

https://griefprevention.github.io/debug/?5NoRJ2wZgp

**Comment by gabizou** [comment] 2018-10-20 23:45
I don’t know what I’m looking at in relation to reproducing what is being recorded as none.

**Comment by kencinder** [comment] 2018-10-21 01:23
The first instance of `entity-damage` in that debug where the target is `minecraft:spider` and the source is `none`, the source was actually `minecraft:creeper` from the creeper exploding, as are all of the `block-break`, `explosion` and `explosion-surface` with the source showing `none`, they should all be attributed to `minecraft:creeper`.

**Comment by MoeBoy76** [comment] 2018-10-24 22:56
Sponge is not tracking or not passing on the base cause of the explosion and therefore block break events and entity damage events. It _should_ be easy to reproduce by checking the events in the same way blood does in GriefPrevention

**Comment by johnfriedrich** [comment] 2018-11-29 01:46
I wrote a very simple test plugin. When I got hurt by a creepers explosion, sponge told me the correct damage source.
But when checking for ChangeBlockEvent.pre when a creepers explodes, it gave me net.minecraft.world.Explosion@176cbd7b as event source. Similiar weird string when checking for ExplosionEvent. This could be normal because I stringified the object. ( I am not familiar with sponge coding at all)
Anyway, for further testing feel free to make use of this test plugin.
https://github.com/i9hdkill/EventTest

But if damage sources, block-break and explosion sources from non player entities are not reported correctly(or not all the time), it's definitely a showstopper, as protection plugins are completely useless. Especially when running Sponge with huge mod packs.

I was testing on SpongeForge 7.1.4 with Forge 2768

**Comment by ryantheleach** [comment] 2018-11-29 02:09
That weird string is a result of calling Object.toString() on an object that doesn't override it.

By default, java will output the type, and Object.hashCode() so that you can attempt to (weakly, visually) see whether objects have an implication(but not guarantee) of reference equality.

@i9hdkill What you have confirmed is that the explosion itself, is the source, rather then the entity causing the explosion.

**Comment by bloodmc** [comment] 2019-01-10 05:14
This was a GP bug. Fixed in commit https://github.com/MinecraftPortCentral/GriefPrevention/commit/923eebede8e2fd1071f94b17627f98ab92c67e9a

**Closed as completed by bloodmc** 2019-01-10 05:14 UTC
Labels: type: bug, system: event, version: 1.12 (u)
