### ISSUE TITLE
Add support for mysql 8.0.3+

### ISSUE THREAD

**Issue by onyn** [SpongePowered/Sponge#2008] opened 2018-07-19 07:45 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- Java version: HotSpot 1.8.0_131-b11 64-bit
- Operating System: Ubuntu Xenial
- Plugins/Mods: none

**Issue Description**

When using sponge database service with mysql 8.0.11, db initialization in my plugin crashed with exception:

```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: (conn:10) Unknown system variable 'tx_isolation'
```

Code example:

```java
SqlService service = Sponge.getServiceManager().provide(SqlService.class).get();
String aliasKey = conf.getNode("db", "mysql", "spongeSqlAlias").getString();
db = service.getDataSource(service.getConnectionUrlFromAlias(aliasKey).orElse(defaultDsn));
```

This issue related to maria db jdbc driver and was resolved in release 2.2.5. Corresponding ticket: [CONJ-604](https://jira.mariadb.org/browse/CONJ-604).

**Solution**

Update mariadb-java-client dependency version to 2.2.5.

**Incompatibilities**

Not found. According to MariaDB Connector/J release notes from 2.0.3 up to 2.2.5 there is no BC breaking changes.

**Possible workarounds**

Clone sponge repo, change dependency version and build. Or repack existing sponge jar with new mariadb driver. This is bad and not recommended.

**Comment by ryantheleach** [comment] 2018-12-01 16:45
@gabizou What amount of testing would be required to get this relatively simple dependency change into the next minor/major (assuming has binary changes, and that the connector follows semver) SpongeAPI builds.

**Comment by ryantheleach** [comment] 2018-12-02 14:39
I've done a minimal amount of testing against `org.mariadb.jdbc:mariadb-java-client:2.3.0` . 

Using that connector you can indeed make a connection, and execute a query (as long as you are using an authentication method mariadb-java-client supports, see comments on #2148).

I'm no expert of the advanced usages of jdbc connectors, so I'm not sure what else would need testing, other then running with some plugins that use jdbc connections.

**Comment by dualspiral** [comment] 2020-05-01 19:18
Okay, my apologies for not acting upon this all that time ago.

There was another issue whereby the default MySQL 8.0.11+ authentication mode wasn't supported and from what I see, that was resolved in version 2.5. So we're going to see if the 2.6 release will work with what we expose and, if so, we'll push that out.

**Comment by BrainStone** [comment] 2020-05-16 00:06
Please fix this already. Literally all it takes is change 1 line.
I've been using versions of the MariaDB driver that supported MySQL 8 since the beginning in my plugins and I've yet to come across any issue whatsoever.

**Comment by ghost** [comment] 2020-05-17 23:22
Currently looking at writing some regression tests for this upgrade. Could someone detail what exactly you would want to see tested before making the change?

**Comment by dualspiral** [comment] 2020-05-19 18:50
After investigation, we're just going to bump it. It should work fine in all but corner cases, but as this is in impl for the most part, it should be fine. We'll just make a big point of the upgrade on our release notes.

**Closed as completed** 2020-05-19 19:02 UTC
Labels: status: accepted, type: enhancement, status: input wanted, version: 1.12 (u)
