### ISSUE TITLE
Duplication Dragon egg when cancelling interact event

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/Sponge#1638] opened 2017-12-05 07:11 UTC
**I am currently running...**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2758 
- SpongeVanilla version: 
- Java version: 8
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
LuckPerms-Sponge-4.0.36
griefprevention-1.12.2-4.3.0.505
**What is the expected result?**
Here how i do it i first get a ender dragon egg (vanilla)
and i make a large claim then go into survival
place the 1 egg in your claim. Then Left Click it but do not right click it
you most likely have to do that 2 time's then you will see the Egg on top and bottom essentally 2 eggs
within the same location but just 1 on top and 2nd on bottom,
**What is the current result?**
Duplication bug with cancelling interact event

**Comment by JBYoshi** [comment] 2017-12-19 20:09
Cannot reproduce.

Code:
```java
    @Listener
    public void onClickEgg(InteractBlockEvent e) {
        if (e.getTargetBlock().getState().getType().equals(BlockTypes.DRAGON_EGG)) {
            e.setCancelled(true);
        }
    }
```

I repeatedly left clicked a dragon egg in survival. While I saw particles, I did not see any new dragon eggs appear, and the original stayed in its place.

SpongeForge 1.12.2-2555-7.0.0-BETA-2783

**Comment by JoeSGT** [comment] 2017-12-19 23:18
I have updated to 
SpongeForge 1.12.2-2555-7.0.0-BETA-2783
and it seem i was wrong sorry about it
if you have a claimed base using GP
and have someone trusted and right click it or you can right click in survival,
the egg dupe's and just do it a few times and it does glitch here a screenshot of it 
https://gyazo.com/d2bc50cac5671b755777a6f6fd7237d6
sorry i should have look into a bit more
but @bloodmc had told me to report it here sorry

**Comment by bloodmc** [comment] 2017-12-20 04:33
@JBYoshi cancel all interacts to see if it can be reproduced. If not I'll look at it in GP when I get some time.

**Comment by bloodmc** [comment] 2017-12-20 16:01
OK so I did some testing and confirmed that someone broke 'ChangeBlockEvent.Place' in recent Sponge builds. The ChangeBlockEvent.Place is now sending 2 packets with the second being from "BasicPluginState".

Here is the cause that comes across second event
```
cause = Cause[Context=Context[], Stack={SpongeModGame{platform=SpongeModPlatform{type=SERVER, executionType=SERVER, api=Wrapped{spongeapi}, impl=sponge, minecraftVersion=SpongeMinecraftVersion{name=1.12.2, protocol=340}}}}]
```

This is AFTER GP cancels the first event yet the second event still maintains the transactions with a bogus cause.

Here is the stack trace that should NOT be happening after a ChangeBlockEvent is cancelled
```
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: java.lang.Exception: Stack trace
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at java.lang.Thread.dumpStack(Unknown Source)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at me.ryanhamshire.griefprevention.listener.BlockEventHandler.onBlockPlace(BlockEventHandler.java:581)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.listener.PlaceListener_BlockEventHandler_onBlockPlace145.handle(Unknown Source)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:328)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:294)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:607)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:526)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.phase.plugin.ScheduledTaskPhaseState.lambda$0(ScheduledTaskPhaseState.java:52)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.phase.plugin.ScheduledTaskPhaseState$$Lambda$1033/2087979698.accept(Unknown Source)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.CapturedSupplier.acceptAndClearIfNotEmpty(CapturedSupplier.java:67)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.phase.plugin.ScheduledTaskPhaseState.unwind(ScheduledTaskPhaseState.java:51)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.phase.plugin.BasicPluginState.unwind(BasicPluginState.java:1)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:232)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.redirect$onRun$zif000(MinecraftServer.java:4190)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:796)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:414)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[10:37:26] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by JoeSGT** [comment] 2017-12-20 19:49
@bloodmc https://gyazo.com/f0924cbfb5b2f6a5228bdee68cf907fa
not fixed it's worse
version i am running is spongeforge-1.12.2-2555-7.0.0-BETA-2785

**Comment by bloodmc** [comment] 2017-12-20 21:05
@JoeSGT Ah yes, the bug i fixed was related to dupe issue with border cancels. For some reason I got this ticket confused with other =)

**Comment by bloodmc** [comment] 2017-12-21 01:28
pushed a fix to GP to solve this issue for now.

**Closed as completed by bloodmc** 2017-12-21 01:28 UTC
Labels: system: event, system: phase tracker, version: 1.12 (u)
