### ISSUE TITLE
Possible Deadlock w/ Existing World

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/Sponge#1351] opened 2017-05-14 04:44 UTC
**I am currently running...**
- SpongeVanilla version: 1.11.2-6.1.0-BETA-3
- Java version: 1.8.0_121
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: no plugins

**What is the expected result?**
Player joins, server continues on as normal.

**What is the current result?**
Player joins, cpu usage becomes excessive, and players will lose connection. Server remains in deadlock after the first person joins.

**SpongeVanilla version the world was created in?**
- 1.10.2-5.1.0-BETA-371 or earlier

**Server Log**
https://pastebin.com/wSG3TK4x

**YourKit CPU Profile**
https://www.dropbox.com/s/o4f6zcp8ioetzqj/sponge--2017-05-13.snapshot?dl=0

**Server Files**
https://www.dropbox.com/s/58kc03bxy9rwmpg/Sponge.rar?dl=0 

**Notes**
The CPU usage may resolve itself with the provided server files. It appears to be a world related issue, but seems like something happened between the times where I was experiencing complete deadlocks and when I managed to fix the issue by creating a new world. There should still be some excessive CPU usage when the player first joins however.

**Comment by Favorlock** [comment] 2017-05-15 14:25
So I'm experiencing this problem even with newly generated worlds. Server locks up once a player joins.

**Comment by stephan-gh** [comment] 2017-05-17 14:31
I can't reproduce this on new worlds using `1.11.2-6.1.0-BETA-3`. Can you test the latest build and check if it still happens? If it still happens, can you try giving the server a bit more memory? (e.g. `-Xmx2g`). Just trying to rule out some potential causes.

**Comment by Favorlock** [comment] 2017-05-17 15:14
Tried with BETA-5 and it doesn't appear to be spiking like Beta-3 was for me. I'm not sure if something external was effecting the performance or what, but for now all I can assume is that it resolved itself. If it occurs again I'll see if I can gather some more information.

**Comment by gabizou** [comment] 2017-05-17 16:22
@Minecrell why is this tagged with cause tracker?

**Comment by stephan-gh** [comment] 2017-05-17 16:41
@gabizou When I checked the YourKit snapshot by @Favorlock it looked like a cause tracking problem, but after I checked again now it could be something different as well.

**Comment by stephan-gh** [comment] 2017-05-21 10:03
@Favorlock Please comment here if it happens again. I'm going to close this issue since it seems to be resolved for now.

**Closed as completed by stephan-gh** 2017-05-21 10:03 UTC
Labels: status: needs testing
