### ISSUE TITLE
Several WorldProperties settings not changing

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Sponge#1739] opened 2018-01-30 16:18 UTC
- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2863
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-11
- Java version: 8 U151
- Operating System: Windows 10
- Plugins/Mods: PJC, PJW

Varies world properties are not saving when being set. Tested the following

`properties.setDifficulty()`
`properties.setMapFeaturesEnabled()`
`properties.setGameMode()`
`properties.setPVPEnabled()`

Also attempted `Sponge.getServer().saveWorldProperties(world);` afterwards but values do not change.
No errors are thrown, the values simply do not change. Not sure when the issue started.

You can check the varies commands in PJW for verification of how these settings are applied.

https://github.com/trentech/ProjectWorlds/tree/7.x/src/main/java/com/gmail/trentech/pjw/commands

More information can be provided as requested.

**Comment by dualspiral** [comment] 2018-01-30 17:36
Same issue as https://github.com/SpongePowered/SpongeCommon/issues/1506

**Comment by phit** [comment] 2018-01-30 17:42
Duplicate of #1506

**Closed as completed by phit** 2018-01-30 17:42 UTC
Labels: resolution: duplicate, version: 1.12 (u)
