### ISSUE TITLE
hasPlayedBefore don't work

### ISSUE THREAD

**Issue by badgyro** [SpongePowered/Sponge#1938] opened 2018-06-12 05:02 UTC
**I am currently running**
- SpongeVanilla version:  **newest stable-7**
- Java version:  **8u171**
- Operating System: **Windows 10 x64**
- Plugins/Mods: **Test plugins from SpongeCommon and my little test plugin**

**Issue Description**
player.hasPlayedBefore() never works because
![image](https://user-images.githubusercontent.com/24192094/41270775-5e7a1eda-6e0d-11e8-930a-4bfd6e4dfbb1.png)

Quick and dirty fix would be:
`player.firstPlayed().get().truncatedTo(ChronoUnit.MINUTES)`
`player.lastPlayed().get().truncatedTo(ChronoUnit.MINUTES)`
![image](https://user-images.githubusercontent.com/24192094/41270964-311c2a86-6e0e-11e8-84dd-d4fed145c70b.png)

But I think that someone need to investigate this deeper.

**Comment by ryantheleach** [comment] 2018-06-12 06:47
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1282

**Closed as completed by ryantheleach** 2018-06-12 06:47 UTC

**Comment by ryantheleach** [comment] 2018-06-13 00:47
In case you missed it, https://github.com/SpongePowered/SpongeCommon/commit/802ea1d1d7a81f8cc37322f313f19935ab24ba73 was implemented as a quick fix, whilst https://github.com/SpongePowered/SpongeCommon/issues/1282 remains open to fix the API.

Thanks for the suggestion!

**Comment by gabizou** [comment] 2018-06-13 16:14
Also, please don't list "newest" of stable-7. that doesn't mean anything to us.
