### ISSUE TITLE
World Properties not saving 

### ISSUE THREAD

**Issue by HaniXP** [SpongePowered/Sponge#2114] opened 2018-10-07 21:55 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3477
- Java version: Version 8 - 181
- Operating System: Windows 7 Ultimate (64 - bit)

- Plugins/Mods:
Plugins : 
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, EconomyLite, FlexibleLogin, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, NPCs, Nations, Nucleus, PlaceholderAPI, UltimateCore

Mods : 
Minecraft, Minecraft Coder Pack,
 Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astikoor, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, Baubles, Better Records, BiblioCraft, BuildCraft, BuildCraft Compat, BuildCraft Lib, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Davinci's Vessels, Doggy Talents, Dynmap, EnderStorage, Exotic Birds, Extra Bit Manipulation, Extreme Reactors, FastWorkbench, FoamFix, FoamFixCore, Forestry, Forge Endertech, Forge Microblocks, Forge Multipart CBE, IndustrialCraft 2, Inventory Tweaks, Just Enough Items, MCMultiPart, MalisisCore, MalisisDoors, Mega Loot, Mekanism, MekanismGenerators, Minecraft Multipart Plugin, Modern Warfare, MorePlayerModels, Moving World, MovingWorld CORE, MrCrayfish's Device Mod, MrCrayfish's Furniture Mod, MrTJPCore, Not Enough Items, OMLib, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, ProjectRed Core, Random Things, RandomPatches, Redstone Flux, Redstone Paste, SecurityCraft, Shadowfacts' Forgelin, SignPicture, TESLA, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Treecapitator, Waila, WorldEdit, Zero CORE, bspkrsCore

**Issue Description**

![sde](https://user-images.githubusercontent.com/23115604/46587370-2afd1600-ca94-11e8-9d7e-7d32ab7ee8d2.JPG)

1) Unloading world [ /world unload (worldname) ]
2) Disabling the world [ /world disable (worldname) ]
3) Deleting the world [ /world delete (worldname) ]

And then i am finally getting an error saying i need to disable the world first in order to delete it.. but i have it already disabled so i dont really know why is it asking again and not allowing me to delete world?

Sounds like another world bug, likely related to #2111

**Comment by ryantheleach** [comment] 2018-12-06 18:51
@dualspiral Are these steps from Nucleus world management? Do you have any insight?

**Comment by ImMorpheus** [comment] 2019-03-09 20:03
Not able to reproduce with SF (updated to https://github.com/SpongePowered/SpongeForge/commit/1c1d1328c13a02960ccca626fa4713f6ce43c8e0) and SC (updated to https://github.com/SpongePowered/SpongeCommon/commit/4063674e2d3f0c2c71cbf37ac7db505ba4eeeb17)

Probably fixed by https://github.com/SpongePowered/SpongeCommon/commit/810f79f0e98d8ac90fd2c8a134c9c804766f7583

**Closed as completed by ImMorpheus** 2019-03-09 20:03 UTC
Labels: type: bug, system: world, version: 1.12 (u)
