### ISSUE TITLE
Fails to write Schematic NBT data with the RequiredMods field

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/Sponge#1052] opened 2016-12-04 23:08 UTC
When I include the `RequiredMods` field in my schematics and try to serialize, it fails to translate the `String` array to `NBTBase`. There is no error when I do not include the `RequiredMods` field.

My test code:

```java
@Listener
    public void breakBlock(ChangeBlockEvent.Break event, @Root Player player) {
        Vector3i position = event.getTransactions().get(0).getOriginal().getLocation().get().getBlockPosition();
        ArchetypeVolume volume = player.getWorld().createArchetypeVolume(position, position, position);

        Schematic schematic = Schematic.builder().volume(volume).metaValue(Schematic.METADATA_AUTHOR, player.getUniqueId())
                .metaValue(Schematic.METADATA_NAME, "Name")
                .metaValue(Schematic.METADATA_REQUIRED_MODS, new String[] {"foo"})
                .paletteType(BlockPaletteTypes.LOCAL).build();

        try {
            DataFormats.NBT.writeTo(new GZIPOutputStream(new FileOutputStream(new File("/Users/robert/test.dat"))),
                    DataTranslators.SCHEMATIC.translate(schematic));
        } catch (InvalidDataException | IOException e1) {
            e1.printStackTrace();
        }

    }
```

produces:

```
java.lang.IllegalArgumentException: Unable to translate object to NBTBase: [Ljava.lang.String;@267a696f
	at org.spongepowered.common.data.persistence.NbtTranslator.getBaseFromObject(NbtTranslator.java:165) ~[NbtTranslator.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.data.persistence.NbtTranslator.getBaseFromObject(NbtTranslator.java:151) ~[NbtTranslator.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.data.persistence.NbtTranslator.getBaseFromObject(NbtTranslator.java:151) ~[NbtTranslator.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.data.persistence.NbtTranslator.containerToCompound(NbtTranslator.java:92) ~[NbtTranslator.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.data.persistence.NbtTranslator.containerToCompound(NbtTranslator.java:73) ~[NbtTranslator.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.data.persistence.NbtTranslator.translateData(NbtTranslator.java:284) ~[NbtTranslator.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.data.persistence.NbtDataFormat.writeTo(NbtDataFormat.java:67) ~[NbtDataFormat.class:1.10.2-5.1.0-BETA-359]
	at Test.breakBlock(Test.java:34) ~[Test.class:?]
	at org.spongepowered.common.event.listener.BreakListener_Test_breakBlock3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) ~[SpongeEventManager.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) ~[SpongeEventManager.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:583) ~[TrackingUtil.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:503) ~[TrackingUtil.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$413(PacketFunction.java:425) ~[PacketFunction.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) ~[CapturedSupplier.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$418(PacketFunction.java:424) ~[PacketFunction.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) [PacketPhase.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190) [CauseTracker.class:1.10.2-5.1.0-BETA-359]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:130) [PacketUtil.class:1.10.2-5.1.0-BETA-359]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zio000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:142) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by RobertHerhold** [comment] 2016-12-04 23:09
Pinging @Deamon5550

**Comment by kashike** [comment] 2016-12-04 23:11
You shouldn't be using an array, you should be using a list, if I remember correctly.

**Comment by RobertHerhold** [comment] 2016-12-04 23:12
The [specification](https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-1.md#metadataObject) says it should be an array. Does this need changed?

**Comment by kashike** [comment] 2016-12-04 23:14
In the json it's an array, sure, but not in the code. @Deamon5550 could add an array serialiser, of course.

**Comment by RobertHerhold** [comment] 2016-12-04 23:16
Thanks for the correction.

**Comment by ryantheleach** [comment] 2018-01-31 05:46
Does this still need an Array serializer added to function?  Or can I close this as works as intended, and create a new issue regarding Array Serializers so that it's easier to find and more on-point?

**Comment by ImMorpheus** [comment] 2018-08-28 12:19
Kashike's comment is self-explanatory. It was just a misunderstanding on what language. [type](https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-1.md#metadataObject) was referring to.

The array serializer is a long-standing issue https://github.com/SpongePowered/configurate/issues/95.

EDIT: having the array serializer wouldn't have resolved the issue, since the RequiredMods field requires a `java.util.List` (not an array) which is translated as an array in json.

**Closed as completed** 2018-08-28 12:19 UTC
Labels: type: enhancement, system: world
