### ISSUE TITLE
SqlService incompatible with MySQL 8.0.x (failing to read password)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#2148] opened 2018-12-01 06:00 UTC
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: 1.12.2-7.1.5-RC139
- Java version: 1.8.0_192
- Operating System: Windows 10
- SQL Server: mysql 8.0.13

- Plugins/Mods: Irrelevant.

**Issue Description**
Despite proper URL syntax (checked against SqlService regex), a password is not being read when it is provided. 
`Access denied for user 'user'@'localhost' (using password: NO)`

`aliases {
    myalias="jdbc:mysql://user:password@localhost/test"
}`

Notably, HikariCP is outdated (latest is `com.zaxxer:HikariCP:3.2.0`) and MariaDB Java Client is outdated (latest is `org.mariadb.jdbc:mariadb-java-client:2.3.0`).

Updating the dependencies to their latest respective versions does **not** fix the issue. 

**Associated PR:** https://github.com/SpongePowered/SpongeCommon/pull/2152

**Comment by phit** [comment] 2018-12-01 10:21
Duplicate of #2008

**Comment by phit** [comment] 2018-12-01 10:23
I know its technically not the same symptoms, but we really don't need two issues to track that the libs are outdated.

**Comment by ryantheleach** [comment] 2018-12-01 10:25
I'm not sure that's the root cause, after investigation it was found that updating it didn't help.

**Comment by phit** [comment] 2018-12-01 10:30
@brjcarbone server version?

**Comment by ryantheleach** [comment] 2018-12-01 10:32
Edited in the mysql server version from information in discord.

**Comment by ryantheleach** [comment] 2018-12-01 16:10
Testing with the following plugin code:

https://gist.github.com/ryantheleach/ed688fb6510c32d93785a72a0752da13

With the following Sponge config

```
# Configuration options related to the Sql service, including connection aliases etc
    sql {
        # Aliases for SQL connections, in the format jdbc:protocol://[username[:password]@]host/database
        aliases {
            frank="jdbc:mysql://ryan:SomethingSecret@localhost/sponge"
        }
    }
```

Resulted in the following exception:

```
02:10:29] [main/INFO] [minecraft/GuiNewChat]: [CHAT] Leaking mysql connection string: jdbc:mysql://ryan:SomethingSecret@localhost/sponge
[02:10:29] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[02:10:30] [Server thread/ERROR] [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Exception during pool initialization.
java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:154) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.throwException(ExceptionMapper.java:92) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:111) ~[mariadb-java-client-2.0.3.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[HikariCP-2.6.3.jar:?]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:138) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:123) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[guava-21.0.jar:?]
	at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:163) ~[SqlServiceImpl.class:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:144) ~[SqlServiceImpl.class:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.test.SQLPluginTest.testConnection(SQLPluginTest.java:46) ~[SQLPluginTest.class:?]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) [CommandSpec.class:?]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) [SimpleDispatcher.class:?]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-7.1.5-SNAPSHOT]
	at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:1083) [ServerCommandManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1003) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:979) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47) [CPacketChatMessage.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8) [CPacketChatMessage.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-7.1.5-SNAPSHOT]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlh000(PacketThreadUtil.java:539) [PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) [PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.runTask(Util.java:53) [Util.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-7.1.5-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:4184) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.sql.SQLException: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:772) ~[AbstractConnectProtocol.class:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:701) ~[AbstractConnectProtocol.class:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:406) ~[AbstractConnectProtocol.class:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1029) ~[AbstractConnectProtocol.class:?]
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:483) ~[Utils.class:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:106) ~[Driver.class:?]
	... 41 more
[02:10:30] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'testsql' for source EntityPlayerMP['Player804'/284, l='New World', x=-202.25, y=68.00, z=255.73]: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
com.google.common.util.concurrent.UncheckedExecutionException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[guava-21.0.jar:?]
	at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:163) ~[SqlServiceImpl.class:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:144) ~[SqlServiceImpl.class:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.test.SQLPluginTest.testConnection(SQLPluginTest.java:46) ~[SQLPluginTest.class:?]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:?]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:?]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-7.1.5-SNAPSHOT]
	at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:1083) [ServerCommandManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1003) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:979) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47) [CPacketChatMessage.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8) [CPacketChatMessage.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-7.1.5-SNAPSHOT]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlh000(PacketThreadUtil.java:539) [PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) [PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.util.Util.runTask(Util.java:53) [Util.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-7.1.5-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:4184) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:543) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:535) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[HikariCP-2.6.3.jar:?]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:138) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:123) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?]
	... 27 more
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:154) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.throwException(ExceptionMapper.java:92) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:111) ~[mariadb-java-client-2.0.3.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[HikariCP-2.6.3.jar:?]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:138) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:123) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?]
	... 27 more
Caused by: java.sql.SQLException: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:772) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:701) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:406) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1029) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:483) ~[mariadb-java-client-2.0.3.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:106) ~[mariadb-java-client-2.0.3.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111) ~[HikariCP-2.6.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[HikariCP-2.6.3.jar:?]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:138) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at org.spongepowered.common.service.sql.SqlServiceImpl$1.load(SqlServiceImpl.java:123) ~[spongecommon-1.12.2-7.1.5-SNAPSHOT.jar:1.12.2-7.1.5-SNAPSHOT]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?]
	... 27 more
[02:10:30] [main/INFO] [minecraft/GuiNewChat]: [CHAT] Error occurred while executing command: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect: Access denied for user 'ryan'@'localhost' (using password: YES)
```

**NOTE:** Mine differs to your exception in that it was indeed using the password. 

I accidentally installed mysql 5, as it was the default mysql for my linux distribution.

I suspected (once I learned I installed mysql 5) that I've screwed up the permissions of the user.

So I started digging using MySQL Workbench.

I Couldn't connect using the default ports, and the password that I was able to log in as using the mysql client.

I may have made a mistake in the configuration, as logging in using a unix pipe worked instead, even though I was certain I had changed it to use password authentication.

MySQL Workbench reported that I had not set a password for the account, so setting a password through workbench and retested.

Retested on MySQL Workbench, and I was now able to connect using a user/pass. (ryan was the root account renamed).

Back to Sponge.

And... It now connects successfully on MySQL 5.

So this works as intended for MySQL 5, with a correctly configured user.

Next up, working out how to install/migrate to MySQL 8

**Comment by ryantheleach** [comment] 2018-12-01 16:42
Using the same user database, on MySQL 8, results in #2008

Sorry I'm unable to replicate, It's either something OS specific, or you have an error in your mysql users table. I'll reopen if someone else on windows can replicate, when they can connect with mysql workbench but not a sponge alias.

**Comment by ryantheleach** [comment] 2018-12-02 14:36
@brjcarbone As a followup, I updated the mariadb connector locally, and it indeed did fix #2008.

You either have a windows specific issue, or an issue with your mysql configuration.

**Comment by onyn** [comment] 2018-12-02 15:11
Access denied error is related only to mariadb client library.

In mysql 8.0 default authentication plugin was changed from `mysql_native_password` to `caching_sha2_password`. This new authentication scheme is not supported by mariadb java library. Even in latest version (2.3.0). Only official mysql connector have support of it as of version 5.1.46. So upgrading mariadb client library is not an option for now.

Happily, you can select auth plugin on per-user basis using `IDENTIFIED WITH` option of `CREATE USER` sql command:

```sql
CREATE USER 'ryan'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'SomethingSecret';
```

This might fix your problem.

**Comment by ryantheleach** [comment] 2018-12-02 15:16
@onyn I believe I was using mysql_native_password the whole time, as I updated from mysql 5.

Thanks for the addition info, I'll look into what our plans will be.

For now, I've reported this to the mariadb team, who have fixed this in the C connector, but not the Java connector: https://jira.mariadb.org/browse/CONJ-663

**Comment by onyn** [comment] 2018-12-02 15:27
You can verify what plugin used by each user for authentication:

```
mysql> SELECT `user`, `host`, `plugin` FROM `mysql`.`user` WHERE `user` LIKE 'abc%';
+------------+------+-----------------------+
| user       | host | plugin                |
+------------+------+-----------------------+
| abc        | %    | caching_sha2_password |
| abc_native | %    | mysql_native_password |
+------------+------+-----------------------+
2 rows in set (0.00 sec)
```

**Comment by ryantheleach** [comment] 2018-12-03 01:53
I've reopened this to track problems with `caching_sha2_password` separately from #2008 . 

On the off-chance that we update the mariadb drivers before the mariadb team has a fix, Or if the team decides to add mysql connector as an extra dependency to prevent issues like this in the future.

**Closed as completed** 2018-12-03 20:19 UTC
Labels: type: bug, version: 1.12 (u)
