### ISSUE TITLE
Crash on Installation

### ISSUE THREAD

**Issue by Nunnery** [SpongePowered/Sponge#346] opened 2015-09-20 17:09 UTC
When following the directions in the [SpongeDocs], I created a launch script consisting of the following:
```batch
java -Xms1G -Xmx3G -jar sponge.jar go
pause
```
When I run this script, it installs flawlessly (as far as I can tell), but crashes once it begins the "run" portion of the "go" command:
```
[13:02:53] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[13:02:53] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[13:02:53] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[13:02:53] [main/INFO]: Forge Mod Loader version 8.99.196.1499 for Minecraft 1.8 loading
[13:02:53] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_60, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_60
[13:02:53] [main/INFO]: Found a command line coremod : org.spongepowered.mod.SpongeCoremod
[13:02:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.4.6 Source=file:/C:/Users/Richard%20Harrah/Desktop/sponge-server/sponge.jar Env=SERVER
[13:02:56] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[13:02:56] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[13:02:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:02:56] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[13:02:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:02:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:02:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:02:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:02:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:02:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:02:57] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[13:02:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[13:02:58] [main/FATAL]: Mixin failed applying mixins.forge.base.json:fml.common.registry.MixinGameData -> net.minecraftforge.fml.common.registry.GameData: org.spongepowered.asm.mixin.injection.InvalidInjectionException @Inject annotation on onRegisterBlock could not find 'registerBlock'
org.spongepowered.asm.mixin.injection.InvalidInjectionException: @Inject annotation on onRegisterBlock could not find 'registerBlock'
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:152) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:112) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:38) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:298) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyInjections(MixinApplicator.java:699) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:208) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:594) ~[sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:566) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:402) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:104) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276) [launchwrapper-1.9.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174) [launchwrapper-1.9.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_60]
        at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_60]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) [?:1.8.0_60]
        at java.lang.Class.privateGetMethodRecursive(Unknown Source) [?:1.8.0_60]
        at java.lang.Class.getMethod0(Unknown Source) [?:1.8.0_60]
        at java.lang.Class.getMethod(Unknown Source) [?:1.8.0_60]
        at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:39) [forge-1.8-11.14.3.1499.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:114) [launchwrapper-1.9.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.8-11.14.3.1499.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.8-11.14.3.1499.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.spongepowered.launch.handlers.RunHandler.run(RunHandler.java:84) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.launch.handlers.GoHandler.run(GoHandler.java:51) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.launch.Main.dispatch(Main.java:134) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
        at org.spongepowered.launch.Main.main(Main.java:82) [sponge.jar:1.8-1499-2.1DEV-634+spongeproject-ci-b634.git-38a5fb2d71d332808348526a2a8c3beffb2c18c4]
A problem occurred running the Server launcher.[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Method.invoke(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Method.invoke(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.launch.handlers.RunHandler.run(RunHandler.java:84)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.launch.handlers.GoHandler.run(GoHandler.java:51)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.launch.Main.dispatch(Main.java:134)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.launch.Main.main(Main.java:82)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/GameData
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.getDeclaredMethods0(Native Method)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.getMethod0(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.getMethod(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:39)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 14 more
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.GameData
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 22 more
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: org.spongepowered.asm.mixin.MixinApplyError: Mixin [mixins.forge.base.json:fml.common.registry.MixinGameData] from phase [PREINIT] in config [mixins.forge.base.json] FAILED
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinErrorState(MixinTransformer.java:634)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:408)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:104)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 24 more
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: org.spongepowered.asm.mixin.injection.InvalidInjectionException: @Inject annotation on onRegisterBlock could not find 'registerBlock'
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:152)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:112)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:38)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:298)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyInjections(MixinApplicator.java:699)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:208)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:594)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:566)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:402)
[13:02:58] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 27 more
```

I downloaded the most recent build of Sponge (coremod) as was available at the time of writing, which was 1.8-1499-2.1DEV-634, into a completely clean directory and ran the above initialization script.

Any assistance that could be provided would be greatly appreciated.

[SpongeDocs]: https://docs.spongepowered.org/en/server/getting-started/installation.html

**Comment by ryantheleach** [comment] 2015-09-20 17:20
634 is broken, you can try using another version until the issue is fixed / the build server starts building again.

**Comment by Nunnery** [comment] 2015-09-20 17:21
After checking with blood on IRC, I resolved the issue by using the Forge installer and dropping the Sponge jar in the mods folder.

**Comment by ryantheleach** [comment] 2015-09-20 17:25
If the "go" initialization is the problem it should be fixed if possible (leaving this ticket open? until it's fixed) or the "go" initialization should be removed from the docs if it's no longer supported.

**Comment by Nunnery** [comment] 2015-09-20 17:26
I agree. Reopening the ticket for now, then.

**Comment by Zidane** [comment] 2015-09-20 18:54
Fixed in Sponge 639. Thanks!

**Closed by Zidane** 2015-09-20 18:54 UTC
