### ISSUE TITLE
World#getDirectory() - not implemented

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/Sponge#1315] opened 2017-04-20 18:18 UTC
The method `getDirectory` in the `World` object seems not to be implemented as it throws an AbstractMethodError.

**Comment by LoadingByte** [comment] 2017-04-22 07:39
(duplicate of #1172 )

I would also appreciate a quick fix since we really depend on this method in one of our plugins, and we don't really want to have to implement a workaround to fix a simple issue like this.

**Closed as completed** 2017-04-22 19:28 UTC
Labels: system: world

**Comment by Sir-Will** [comment] 2017-04-23 23:35
Thanks, in which build can I find that implementation?

**Comment by gabizou** [comment] 2017-04-24 04:12
Look [here](https://www.spongepowered.org/downloads/spongeforge/bleeding/1.11.2) and expand the builds with `...` buttons to view the commits for the submodules (SpongeCommon). Shows up being 2286

**Comment by Sir-Will** [comment] 2017-04-24 05:05
Oh, didn't see the dots. 
Will this be added to 1.10 too?
