### ISSUE TITLE
Request: Enhance the Cause of SpawnEntityEvent for ExpOrbs

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1688] opened 2018-01-05 19:17 UTC
**Issue Description**
I'm currently working on writing a plugin that controls the amount of experience players gain for different actions. Below is a capture of the causes for the different actions I want to control:

```
ExpBottle: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:experience, name=Experience}, "sponge:owner"=EntityPlayerMP['Zerthick'/1955, l='world', x=13.27, y=67.00, z=254.15]], Stack={EntityExpBottle['entity.ThrownExpBottle.name'/6348, l='world', x=10.60, y=64.25, z=250.11]}]
Fishing: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:placement, name=Placement}, "sponge:owner"=EntityPlayerMP['Zerthick'/1955, l='world', x=80.87, y=63.00, z=236.84], "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemFishingRod{Name=fishingRod}, quantity=1}, "sponge:notifier"=EntityPlayerMP['Zerthick'/1955, l='world', x=80.87, y=63.00, z=236.84]], Stack={EntityPlayerMP['Zerthick'/1955, l='world', x=80.87, y=63.00, z=236.84]}]
Smelt: Cause[Context=Context[], Stack={net.minecraft.inventory.ContainerFurnace@c478eaf, EntityPlayerMP['Zerthick'/1955, l='world', x=79.76, y=64.00, z=238.36]}]
Mining: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:used_item"=SpongeItemStackSnapshot{itemType=ItemPickaxe{Name=pickaxeDiamond}, quantity=1}], Stack={EntityPlayerMP['Zerthick'/1955, l='world', x=57.23, y=65.00, z=211.30]}]
Combat: Cause[Context=Context["sponge:notifier"=EntityPlayerMP['Zerthick'/1955, l='world', x=59.64, y=65.00, z=213.15]], Stack={EntityZombie['Zombie'/10750, l='world', x=56.65, y=64.00, z=213.70]}]
Breed:	Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:experience, name=Experience}, "sponge:notifier"=EntityPlayerMP['Zerthick'/359, l='world', x=109.57, y=80.00, z=304.20]], Stack={EntityPig['Pig'/552, l='world', x=111.03, y=80.00, z=302.54]}]
```

I've noticed a few inconsistencies in the causes and would like to request more information be added.

For fishing, the spawn_type within the context is set to placement instead of experience, is this a bug?

For smelting, no spawn type is specified. The cause also holds a reference to the furnace inventory instead of the furnace itself, is this the intended behavior? I'd also like to request if possible the cause contain an ItemStackSnapshot of the item which was smelted to produce the experience, as you cannot grab this from the furnace as the output slot has already been set to air.

For mining I'd like to request that a BlockSnapShot of the block mined be included in the cause.

Combat is missing the spawn type.

I'd like to request a way to differentiate between orbs spawned from killing an entity, and orbs spawned from breeding them, as there currently is not a way to do this, other than relying on the missing spawn type.

Thanks!

**Comment by ImMorpheus** [comment] 2018-01-07 19:57
For fishing/mining/killing mobs/bottle of exp: duplicate of https://github.com/SpongePowered/SpongeCommon/issues/920

It would be better to add smelting and breeding there to keep a list of incorrect spawntype. 
(And the 1.12 label @phit )

**Comment by dualspiral** [comment] 2020-06-09 10:41
#1749

**Closed as completed by dualspiral** 2020-06-09 10:41 UTC
Labels: system: event, system: phase tracker, version: 1.12 (u)
