### ISSUE TITLE
Minecraft Crash because of SpongeForge

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/Sponge#369] opened 2015-10-12 16:37 UTC
when ever i try to make a world it crash the game

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge-1.8-1519-2.1DEV-703.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 12/10/15 12:36 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.common.DimensionManager
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:313)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:416)
	at net.minecraft.world.storage.SaveHandler.redirectHandleWorldDataSave(SaveHandler.java:52)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:204)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2169)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:232)
	at net.minecraft.client.gui.GuiCreateWorld.func_73869_a(GuiCreateWorld.java:407)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:571)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:527)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1670)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:313)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:416)
	at net.minecraft.world.storage.SaveHandler.redirectHandleWorldDataSave(SaveHandler.java:52)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:204)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2169)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:232)
	at net.minecraft.client.gui.GuiCreateWorld.func_73869_a(GuiCreateWorld.java:407)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:571)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:527)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1670)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.11.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 342107704 bytes (326 MB) / 493879296 bytes (471 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1520 Optifine OptiFine_1.8_HD_U_D5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1520.jar) 
	UCHIJA	Forge{11.14.3.1520} [Minecraft Forge] (forge-1.8-11.14.3.1520.jar) 
	UCHIJA	Sponge{1.8-1519-2.1DEV-703} [SpongeForge] (minecraft.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (sponge-1.8-1519-2.1DEV-703.jar)
  
	Launched Version: 1.8-forge1.8-11.14.3.1520
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.10.18, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by heni123321** [comment] 2015-10-12 17:32
Optifine is loading DimensionManager too early

**Comment by LOLDERP** [comment] 2015-10-12 17:47
oh

**Comment by simon816** [comment] 2015-10-12 19:29
Duplicate of https://github.com/SpongePowered/Sponge/issues/321
Don't use Optifine

**Closed by simon816** 2015-10-12 19:29 UTC
