### ISSUE TITLE
Canceling the ChangeBlockEvent does not work when instabreaking the Block.

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#363] opened 2015-10-09 10:33 UTC
For example tallgrass & flowers can be broken. Or dirt with an efficiency V dia-shovel. Its not a visual glitch, the Block is still gone after restart. Sorry @bloodmc :D

**Comment by Zidane** [comment] 2015-10-09 14:07
@TBlueF 

```
package org.spongepowered.test;

import org.slf4j.Logger;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.block.ChangeBlockEvent;
import org.spongepowered.api.plugin.Plugin;

import javax.inject.Inject;

@Plugin(id = Test.PLUGIN_ID, name = Test.PLUGIN_NAME, version = Test.PLUGIN_VERSION)
public class Test {
    public static final String PLUGIN_ID = "test", PLUGIN_NAME = "Test", PLUGIN_VERSION = "0.1";

    @Inject public Test instance;
    @Inject private Logger logger;

    @Listener
    public void onEvent(ChangeBlockEvent.Break event) {
        event.setCancelled(true);
    }
}
```

Added this listener with latest Sponge (that I built) and could not get around it. Even with a diamond shovel at Efficiency V, it still blocked it.

**Comment by Zidane** [comment] 2015-10-09 14:19
Actually, after playing with this more...something is chewing up tick time and causing the server watchdog to freeze and crash out @bloodmc . Tested with fresh worlds and simply logging in.

**Comment by TBlueF** [comment] 2015-10-09 14:23
@Zidane are you shure you walked out of spawn protection while testing? Because i compiled your code and still get the same problem ^^ (Forge 11.14.3.1519, Sponge 1.8-1519-2.1DEV-693)

**Comment by Zidane** [comment] 2015-10-09 14:35
@TBlueF 

If you are an OP (which I am), spawn protection won't affect it.

**Comment by TBlueF** [comment] 2015-10-09 16:06
Hmm:
1. I compiled your code and set up a new server, started it an tested: **I broke some Blocks**
2. I Stopped the Server, posted the post above, read @Zidane s answer, restarted the same server with nothing changed, **i wasn't able to break blocks anymore?!?**
3. Changed `ChangeBlockEvent.Break` to `ChangeBlockEvent` started the Server and it crashed, as soon as i broke something with: http://pastebin.com/WusERqFY
4. I Restarted it and it keeps crashing with another error: http://pastebin.com/s3SLPsVa

Very strange :o

**Comment by bloodmc** [comment] 2015-10-09 16:48
@TBlueF sounds like your listener isn't cancelling the event correctly. I cannot reproduce the issue on my end using latest build. The crash you are seeing I will fix.

**Comment by TBlueF** [comment] 2015-10-12 09:39
> Zip up your world folder and provide your listener code.

Oh sorry, i just realized I've overseen that completely. Here is [the world](https://drive.google.com/file/d/0B4vy2bgB12UcbmdrYjJtSWJZZjQ/view?usp=sharing).
And the Plugin is just Zidane's Test-Plugin with `ChangeBlockEvent.Break` changed to `ChangeBlockEvent`:

    package de.craftednature.sponge.test;

    import javax.inject.Inject;

    import org.slf4j.Logger;
    import org.spongepowered.api.event.Listener;
    import org.spongepowered.api.event.block.ChangeBlockEvent;
    import org.spongepowered.api.plugin.Plugin;

    @Plugin(id = Test.PLUGIN_ID, name = Test.PLUGIN_NAME, version = Test.PLUGIN_VERSION)
    public class Test {
        public static final String PLUGIN_ID = "test", PLUGIN_NAME = "Test", PLUGIN_VERSION = "0.1";

        @Inject public Test instance;
        @Inject private Logger logger;

        @Listener
        public void onEvent(ChangeBlockEvent event) {
            event.setCancelled(true);
        }
    }

**Comment by Zidane** [comment] 2015-10-12 15:11
@TBlueF 

Never EVER cancel just ChangeBlockEvent. This causes a massive amount of lag as ChangeBlockEvent includes all place, breaks, modifies...its not just players!

**Comment by gabizou** [comment] 2015-10-12 16:56
@Zidane I think you should've mentioned that `ChangeBlockEvent` is triggered for world generation as well.

**Comment by TBlueF** [comment] 2015-10-12 20:30
Uhm ... ok! Im glad u mentioned that! I'm scared now xD
*Note to self: Revisit whole code as soon as possible!*
But it should not cause an error though, does it?

**Comment by bloodmc** [comment] 2015-10-14 00:10
It will cause a ton of issues if you cancel the base event without any check for cause. Every block change in game, excluding chunk primers, flow through this event. Closing ticket as it is not a bug.

**Closed by bloodmc** 2015-10-14 00:10 UTC
