### ISSUE TITLE
A player using a bucket is not the root cause.

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#2157] opened 2018-12-06 22:03 UTC
**I am currently running**

- SpongeVanilla version: 7.1.5
- Java version: 1.8.0_192
- Operating System: Windows 10

This may or may not be an issue, but it appears to be one the only inconsistency I've found thus far with regard to direct player interactions not putting the player as the root cause in the stack. `@First` is a workaround, but I firmly believe that I emptied these water buckets on my own free will and thus I am groot. 

Event is ChangeBlockEvent.Place.

**Comment by ImMorpheus** [comment] 2019-05-11 09:47
Not able to reproduce. Should be fixed by https://github.com/SpongePowered/SpongeCommon/commit/5b7a63f64198c7950f259c025c086878687661e7

**Closed as completed by ImMorpheus** 2019-05-11 09:47 UTC
Labels: system: phase tracker, version: 1.12 (u)
