### ISSUE TITLE
Furnace is not in cause of SpawnEntityEvent for experience orb from removing result from furnace

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1194] opened 2017-02-10 20:59 UTC
This is the result of printing out the entities and the cause when an experience orb is spawned from removing the result of a furnace. I would expect there to be the furnace in the cause in some way or at least the location of it, but it seems only the player and his/her location is. 

![image](https://cloud.githubusercontent.com/assets/18372958/22843906/4683544a-efa1-11e6-8905-7e7fcb8ebfc8.png)

This is the code that prints it out:
![image](https://cloud.githubusercontent.com/assets/18372958/22843922/51ee6f22-efa1-11e6-98d6-b324afaeae0d.png)

**Comment by JBYoshi** [comment] 2017-02-16 02:58
Once #1207 is merged, you will be able to get the `Container` in the cause. You can then check if it's a `CarriedInventory` and, if so, whether the `Carrier` is a `Furnace` (and, of course, get it).

**Closed as completed** 2017-03-23 06:59 UTC
