### ISSUE TITLE
Redundant serialized data of Location

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2109] opened 2018-09-25 04:56 UTC
This issue was originally submitted by @Lignium in [SpongePowered/SpongeAPI#1914](https://github.com/SpongePowered/SpongeAPI/issues/1914).
___
As it was already noted earlier at Discord, a world name and a block type is redundant data. Furthermore the block type may not be coincide with a block type which located in the world...

Source code:
```
World world = Sponge.getServer().getWorlds().iterator().next();
Location<World> location = world.getLocation(0, 0, 0);
        
System.out.println(DataFormats.JSON.write(location.toContainer())));
```

Result (formatted):
```
{
    "ContentVersion": 1,
    "WorldName": "world",
    "WorldUuid": "63f28a76-c4a8-4d10-b5f5-747ba8304506",
    "BlockType": "minecraft:bedrock",
    "X": 0.0,
    "Y": 0.0,
    "Z": 0.0
}
```

**Comment by randombyte-developer** [comment] 2018-09-27 12:44
A fix/refactor should be paired with this (from discord,  July 11th 2018 by @ryantheleach)

```
Honestly we need a concept of an unvalidated, offline location. Essentially a world index / co ordinate / transform
Rolling your own [TypeSerializer] is probably the correct work around for now
```

as I hit an issues with deserializing a Location whose World isn't loaded yet or was deleted: [Fix commit](https://github.com/randombyte-developer/unity/commit/1664c2d844a7e237f4f55d9d381906ce816f1c5a#diff-27540bb80c2793d00a7980b241fc77dcR34)

Also duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1720

**Comment by ImMorpheus** [comment] 2019-11-01 21:13
> duplicate of #1720 

Yup

**Closed as completed by ImMorpheus** 2019-11-01 21:13 UTC
Labels: system: data, resolution: duplicate
