### ISSUE TITLE
Game registry -> getType -> empty optional

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1325] opened 2017-04-30 12:49 UTC
`Sponge.getRegistry().getType(Key.class, "dye_color");`
This returns empty optional. Is it ok? Tried on this commit
https://github.com/SpongePowered/SpongeCommon/commit/08ed602607aed0e4e719266e5bf9f667dcc4fa0f
SpongeForge.

**Comment by ST-DDT** [comment] 2017-04-30 19:00
Try `sponge:dye_color`

**Comment by XakepSDK** [comment] 2017-05-01 16:27
Yep, it works with `sponge:`

**Comment by ryantheleach** [comment] 2017-05-19 09:39
@Minecrell Can this be closed, or is this waiting on some form of aliasing?

**Comment by stephan-gh** [comment] 2017-05-19 10:39
I'm not sure, that's the question :P We normally default to `minecraft:` when no explicit prefix is given, however we don't have any `minecraft:` keys in Sponge. Would it make sense to default to `sponge:` in this case?

**Comment by dualspiral** [comment] 2017-05-19 10:55
IMO, if we don't have any `minecraft:` keys (or any specific catalog type) in Sponge, then it _doesn't_ make sense to make that the default at all for that case - though the problem is that by doing so, the goalposts are shifting for each catalog type, some will default for `minecraft:`, some to `sponge:`, and there is no (easy, developer friendly) way to determine which one would be which unless the classes are documented as such. 

I suspect developers in general would expect that just entering the non-namespaced keys would return what is bundled with Minecraft _or_ Sponge. So for consistency's sake and to throw _another_ option into the works, should we default to the `minecraft:` prefix if no explict prefix is given, then if that yields nothing, check the `sponge:` prefix before failing _for all_ `CatalogType`s? 

The drawback here is if there is a `minecraft:[blah]` and a `sponge:[blah]` ID for any specific type, developers would have to know that they would get the `minecraft:` ID if they don't specify a prefix. I've not been through all the CatalogTypes, and I don't know if this would be a problem with the current IDs we have.

**Comment by XakepSDK** [comment] 2017-05-19 11:00
I think, is better to warn devaloper and search in all catalog types for that type and print it.
E.g.
[Warn] Xxx not fount in yyy registry! May be you want zzz:xxx or bbb:xxx?

**Comment by DenWav** [comment] 2017-05-19 18:30
I think it should always require it to be fully qualified in all cases. Clears up all confusion, and requires no ambiguous rules.

**Comment by ST-DDT** [comment] 2017-05-20 08:51
Mhh. The CommandElement could be used to try and determine any prefixes if they are missing.

**Comment by Zidane** [comment] 2018-02-03 00:04
Closing this as it is modder spec to know that for anything that is ResourceLocation-like, the default will ALWAYS be minecraft:blah and I don't feel we need to be deciding to change this global default based on the catalog. Just muddies this up much further.

**Closed as completed by Zidane** 2018-02-03 00:04 UTC
Labels: type: support, system: registry
