### ISSUE TITLE
crash-2016-12-22_23.36.47-server.txt

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/Sponge#1097] opened 2016-12-24 13:15 UTC
http://pastebin.com/ykSSbQaf

**Comment by liach** [comment] 2016-12-30 00:52
Someone should close this

**Comment by gabizou** [comment] 2016-12-30 17:37
Can't reproduce, and the NPE is pointing to non-sponge code. Re-open if it's reproduced on the latest build.

**Closed as completed by gabizou** 2016-12-30 17:37 UTC
