### ISSUE TITLE
InteractInventoryEvent.Close cannot setCancelled

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/Sponge#2525] opened 2020-03-03 00:51 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.10
- SpongeVanilla version: spongevanilla-1.12.2-7.1.10

- Plugins/Mods: 
Just mine

**Issue Description**
When there is a item on cursor. The error will appear.
And the item is on my cursor after open again
```
@Listener
public void onEvent(InteractInventoryEvent.Close event) {
    event.setCancelled(true);
}
```

Error:
https://gist.github.com/SettingDust/230c1ef6b0f533f4c6c12714f1679fc1

**Comment by IzzelAliz** [comment] 2020-03-03 02:36
Duplicate with #2415

**Comment by ImMorpheus** [comment] 2020-03-16 20:18
Duplicate of #2415

**Closed as completed by ImMorpheus** 2020-03-16 20:18 UTC
Labels: resolution: duplicate
