### ISSUE TITLE
[1.10.2] Invasion server crash

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1331] opened 2017-05-03 01:45 UTC
Invasion modpack server crashes when a player gets near a mobspawner containing a wasp from BiomesOPlenty. (Found mob type when checking affected region data in NBT editor)

Crash Report: 
[cZJT8s8b.txt](https://github.com/SpongePowered/SpongeCommon/files/972314/cZJT8s8b.txt)

Minecraft: 1.10.2
SpongeForge: 1.10.2-2281-5.2.0-BETA-2300
Minecraft Forge: 12.18.3.2281
Operating System: Linux

**Comment by phit** [comment] 2017-11-07 12:09
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1422

**Closed as completed by phit** 2017-11-07 12:09 UTC
Labels: resolution: duplicate, version: 1.10 (u)
