### ISSUE TITLE
LegacyText : Optimization

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1504] opened 2017-08-22 17:17 UTC
@Minecrell 
After the [commit](https://github.com/SpongePowered/SpongeCommon/commit/4584f6ee5920b0e3643b3d6b6fc54fe40201c250), The color at end of Text is not saved and this is usefull when I want to concatenate 2 Text with propagate TextColor.

**Comment by stephan-gh** [comment] 2017-08-22 21:10
@lesbleu I'm not sure I understand your use case, could you provide example code how you're combining the text instances. Couldn't you just concatenate before giving it into the legacy serializer?

**Comment by lesbleu** [comment] 2017-08-23 04:41
[EFormatString](https://github.com/EverCraft/EverAPI/blob/master/src/main/java/fr/evercraft/everapi/message/format/EFormatString.java#L66)
![Example](https://image.noelshack.com/fichiers/2017/34/3/1503463463-capture.jpg)

Code : [EATest](https://github.com/EverCraft/EverAPI/blob/2c7a0a6cd5bb9d717e70d440434be2354afed6a4/src/main/java/fr/evercraft/everapi/command/sub/EATest.java#L71)

Result : &cHello rexbut
Expected result : &cHello &arexbut

**Comment by XakepSDK** [comment] 2017-08-24 17:55
# **_RTFM!_**
### **https://docs.spongepowered.org/stable/en/plugin/text/templates.html**

Sorry for this, guys, but i have BUTT HURT! JUST RTFM!!!!!!1

**Comment by lesbleu** [comment] 2017-08-24 19:12
Hi @XakepSDK,
TextTemplates is not usefull for Custom Message to my usage.
In my plugins, there are approximately 50 replace per message [EReplacesPlayer](https://github.com/EverCraft/EverAPI/blob/master/src/main/java/fr/evercraft/everapi/message/replace/EReplacesPlayer.java), [EReplacesServer](https://github.com/EverCraft/EverAPI/blob/master/src/main/java/fr/evercraft/everapi/message/replace/EReplacesServer.java)

There are 2 types of replace : 
- Global variable with argument (Example : {OPTION_VALUE=prefix})
- Variable message

In EverPermissions, I have approximately 300 messages. If I use TextTemplates, I add 20 TextTemplates line to create my custom message. It's not adapted for my usage.

**Comment by XakepSDK** [comment] 2017-08-24 20:05
Do you want to replace placeholder part with 'Text' class contents?
Try to do this with sponges TextTemplate/Text.append, if everything works - problem is in your code.

**Comment by rexbut** [comment] 2017-08-24 20:56
[Append](https://github.com/EverCraft/EverAPI/blob/368ccad2ee23a532f12b0db69b6c7d7176d0a9a5/src/main/java/fr/evercraft/everapi/command/sub/EATest.java#L76) :
![Append](https://image.noelshack.com/fichiers/2017/34/4/1503607404-capture2.jpg)

[TextTemplate](https://github.com/EverCraft/EverAPI/blob/368ccad2ee23a532f12b0db69b6c7d7176d0a9a5/src/main/java/fr/evercraft/everapi/command/sub/EATest.java#L78) :
![TextTemplate](https://image.noelshack.com/fichiers/2017/34/4/1503606926-capture.jpg)

Result : &cHello rexbut
Expected result : &cHello &arexbut

The problem comes from this function:
> TextSerializers.FORMATTING_CODE.deserialize("&cHello &a") 

Since optimization if the content of a style is empty, [it is deleted](https://github.com/SpongePowered/SpongeCommon/blob/4584f6ee5920b0e3643b3d6b6fc54fe40201c250/src/main/java/org/spongepowered/common/text/serializer/LegacyTexts.java#L146). So the function returns: 
> TextSerializers.FORMATTING_CODE.deserialize("&cHello ")

**Comment by FabioZumbi12** [comment] 2018-01-31 10:59
`TextSerializers.FORMATTING_CODE.serialize(Text.of("&cHello &a"))` removes the last color code too. I having this issue when using on my chat plugin, where i need to parse a lot of placeholders and tags too, and all as string, and starting and ending with strings and color codes.

**Comment by ryantheleach** [comment] 2018-01-31 13:33
@kashike @Minecrell I'd maybe consider this a bug considering the ways that Legacy text formatting methods are usually used and peoples expectations of it just working like string appending.

Mark as bug or close?

**Comment by stephan-gh** [comment] 2018-01-31 13:53
It works as intended, but maybe we should consider disabling this in a separate method and/or a parameter.

**Comment by XakepSDK** [comment] 2018-04-02 17:23
Bump

**Comment by ImMorpheus** [comment] 2023-11-18 02:47
Hey! You seem to be running an unsupported version (API 7) of SpongeAPI. Support for API 7 ended in January 2022.

API-7 is now end-of-life. We will not be issuing any more API updates for version 7 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API7/1.12.2[^2]
___

The Text API is now supplied by the [Kyori Adventure library](https://github.com/KyoriPowered/adventure/) so this issue is no longer relevant to this repository.

[^1]: https://forums.spongepowered.org/t/status-update-8th-january-2022-spongeapi-8-released/39861#minecraft-1122-spongeapi-7-10
[^2]: https://forums.spongepowered.org/t/sponge-status-update-28th-may-2022/40135#api-71122-community-support-8

**Closed as completed by ImMorpheus** 2023-11-18 02:47 UTC
Labels: system: text
