### ISSUE TITLE
Repeating Command blocks stop looping

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1815] opened 2018-02-24 22:35 UTC
This issue was originally submitted by @simibubi in [SpongePowered/SpongeForge#1817](https://github.com/SpongePowered/SpongeForge/issues/1817).
___
forge: 1.12.2-14.23.0.2503
spongeforge: 1.12.2-2486-7.0.0-BETA-2689

Any command in Repeating Command blocks stopped looping when 
reentering the chunks after a few minutes, it has to be reactivated by a player to operate again:
Always active: Command blocks have to be replaced or changed in the UI
Needs Redstone: Redstone source has to be turned off and back on

**Comment by phit** [comment] 2018-02-24 22:36
I could reproduce this on `spongevanilla-1.12.2-7.1.0-BETA-22.jar`

**Comment by JBYoshi** [comment] 2018-03-09 02:43
I could previously reproduce this, but can't reproduce it anymore on SF 1.12.2-2611-7.1.0-BETA-2953. Will update to 2955 and test once more.

**Comment by JBYoshi** [comment] 2018-03-09 02:48
Should be fixed in 2955 (tested on the recommended Forge build). No idea when it was fixed, but it apparently is.

**Comment by LXGaming** [comment] 2018-04-08 05:52
Still an issue on the following:
 - SpongeVanilla: 1.12.2-7.1.0-BETA-38
 - SpongeForge: 1.12.2-2611-7.1.0-BETA-3005 (Forge: 1.12.2-14.23.2.2645 & 1.12.2-14.23.2.2611)

No Plugins/Mods were installed during testing.

**Comment by JBYoshi** [comment] 2018-04-12 02:53
Tested again, and reproduced it again this time.

**Comment by JBYoshi** [comment] 2018-04-17 01:35
Tracking this down has been really annoying... but I think I've traced it to an off-by-one error in some of Sponge's added optimization code. Currently testing and will report back shortly.

**Comment by JBYoshi** [comment] 2018-04-17 02:40
Apparently I revealed some nasty side effects where the chunk with the command block never gets unloaded. Will work on that before I push the fix.

**Comment by JBYoshi** [comment] 2018-04-17 15:35
Looks like that's intended. Pending review before I merge it.

**Comment by JBYoshi** [comment] 2018-05-25 13:04
Fixed a month ago in https://github.com/SpongePowered/SpongeCommon/commit/f5addf7d78eb856a0f2c761a60f4652f78d060a4.

**Closed as completed by JBYoshi** 2018-05-25 13:04 UTC
Labels: status: accepted, type: bug, system: world, version: 1.12 (u)
