### ISSUE TITLE
WorldProperties setGenerateSpawnOnLoad not obeyed

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#2290] opened 2019-06-11 08:55 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.7-RC3768
- Java version: 1.8.0_202/64-bit (Oracle Corporation)
- Operating System: Linux (4.15.0-43-generic/amd64)

- Plugins/Mods: Tekxit 3, Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, EpicBanItem, GriefPrevention, LuckPerms, MMCReboot, MMCRules, Nucleus, ServerListPlus, Total Economy, spark, worldedit-sponge

Attempting to implement regeneration for worldedit sponge,
It seems that setGenerateSpawnOnLoad is ignores and on world load the world generates the spawn area anyway.

Code in question: https://github.com/EngineHub/WorldEdit/pull/486/files

```
> [09:46:49] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for level 3 (worldedittemp)
> [09:46:51] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 6%
> [09:46:52] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 12%
> [09:46:53] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 22%
> [09:46:54] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 29%
> [09:46:55] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 37%
> [09:46:56] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 44%
> [09:46:57] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 53%
> [09:46:58] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 60%
> [09:46:59] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 69%
[09:47:00] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 79%
[09:47:01] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 88%
[09:47:02] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 98%
[09:47:02] [Server thread/INFO] [Sponge]: Unloading world [worldedittemp] (minecraft:overworld/3)
```

**Comment by JBYoshi** [comment] 2019-06-13 21:55
I can't reproduce this on SpongeForge RC3777 (no mods/plugins except for my own testing tools and Sponge's test plugins).

My test code (mostly, but not completely, copied from the link):
```java
Server server = Sponge.getServer();
final String id = "regenArchetype";
final WorldArchetype regenerationArchetype = Sponge.getRegistry().getType(WorldArchetype.class, id)
        .orElseGet(() -> WorldArchetype.builder()
                .serializationBehavior(SerializationBehaviors.NONE)
                .build(id, id));

WorldProperties tempWorldProperties;
tempWorldProperties = server.createWorldProperties("worldedittemp", regenerationArchetype);
tempWorldProperties.setGenerateSpawnOnLoad(false);

Optional<World> tempWorldOpt = server.loadWorld(tempWorldProperties);
if (!tempWorldOpt.isPresent()) {
    throw new IOException("Failed to load temp world");
}

World freshWorld = tempWorldOpt.get();

// Remove temp world
server.unloadWorld(freshWorld);
server.deleteWorld(tempWorldProperties);
```

Output:
```
[16:50:10] [Server thread/INFO] [Sponge]: Loading world [worldedittemp] (minecraft:overworld/2)
[16:50:10] [Server thread/INFO] [advancement_test]: Loading advancements...
[16:50:10] [Server thread/INFO]: Loaded 494 advancements
[16:50:10] [Server thread/INFO] [advancement_test]: Loading advancement trees...
[16:50:10] [Server thread/INFO]: Loaded 8 advancement trees
[16:50:11] [Server thread/INFO] [Sponge]: Unloading world [worldedittemp] (minecraft:overworld/2)
```

**Comment by clienthax** [comment] 2019-06-13 23:02
Hmm, I wonder if it's only generated when a chunk is requested, not able to test currently

**Comment by JBYoshi** [comment] 2019-06-14 01:01
I can reproduce this with the [experimental WorldEdit builds](http://builds.enginehub.org/job/worldedit/11979); I'll see if I can figure out the problem using that.

**Comment by JBYoshi** [comment] 2019-06-14 03:24
...Actually, I seem to have an old build. The version I got doesn't ever call `setGenerateSpawnOnLoad(false)`. Manually calling it via the debugger fixes it. No idea what's going on.

**Comment by wizjany** [comment] 2019-06-15 02:08
oof, that's my bad. pulled the original commit instead of the forcepushed one and somehow didn't notice. fixed now, and this does indeed seem to work (in my defense, clienthax said it didn't in his test too >.>) this can be closed

**Closed as completed** 2019-06-15 02:10 UTC
Labels: version: 1.12 (u)
