### ISSUE TITLE
Offering spectator mode to a player does not work correctly

### ISSUE THREAD

**Issue by widd** [SpongePowered/Sponge#1356] opened 2017-05-17 03:31 UTC
`player.offer(Keys.GAME_MODE, GameModes.SPECTATOR);`
will result in a somewhat "incomplete" spectator state:
* Player is entirely invisible rather than a transparent head box being shown
* Player does **_not_** have no-clipping ability

Setting the gamemode manually via `/gamemode 3` works normally even if the player is in this pseudo-spectator state.

**Comment by Cybermaxke** [comment] 2017-05-17 21:11
This is caused by the fact that the gamemode of a player can also be set in the tab list, and if the two gamemodes don't match, behavior like this may occur.

**Comment by gabizou** [comment] 2017-05-18 05:44
Need some version information on which this is occurring.



> This is caused by the fact that the gamemode of a player can also be set in the tab list, and if the two gamemodes don't match, behavior like this may occur.

What do you mean "this"? The data processor that is performing the game mode change is performing the *exact* same method call as if you were to run the game mode command, there's no tab list modification that needs to take place to make the player a floating head etc.

**Comment by widd** [comment] 2017-05-18 08:30
Happens on SpongeVanilla and SpongeForge - MC 1.11.2 (SpongeAPI 6.1.0).

**Comment by Cybermaxke** [comment] 2017-05-18 12:49
@gabizou The client player uses 2 different gamemodes, the one set through http://wiki.vg/Protocol#Change_Game_State and one set through http://wiki.vg/Protocol#Player_List_Item, if they don't match on the client, the behavior that @widd specified can occur. I figured this out a while back when I was playing around with those packets.

**Comment by JBYoshi** [comment] 2017-05-18 14:29
Cannot reproduce. SpongeForge build [2343](https://github.com/SpongePowered/SpongeForge/commit/5e341306df1215f0787f4cf4262e23589a2da93d) (latest stable 1.11.2) in a development workspace.

Test plugin:
```java
package jbyoshi.sponge.test;

import org.spongepowered.api.Sponge;
import org.spongepowered.api.command.CommandResult;
import org.spongepowered.api.command.args.GenericArguments;
import org.spongepowered.api.command.spec.CommandSpec;
import org.spongepowered.api.data.key.Keys;
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.entity.living.player.gamemode.GameModes;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.game.state.GameInitializationEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;

@Plugin(id = "testspongecommon1356")
public class TestSpongeCommon1356 {
    @Listener
    public void onInitialization(GameInitializationEvent e) {
        Sponge.getCommandManager().register(this, CommandSpec.builder()
                .arguments(GenericArguments.playerOrSource(Text.of("player")))
                .executor((src, args) -> {
                    ((Player) args.getOne("player").get()).offer(Keys.GAME_MODE, GameModes.SPECTATOR);
                    src.sendMessage(Text.of("You are now spectating"));
                    return CommandResult.success();
                }).build(), "test-c1356");
    }
}
```

@Cybermaxke The method used internally sends both packets.

**Comment by Cybermaxke** [comment] 2017-05-18 18:36
@widd Are you also interacting with the TabList api?

**Comment by widd** [comment] 2017-05-18 18:37
@Cybermaxke Not at all. The code I posted is the only thing I'm doing as of right now.

However it occurs upon respawn (dying puts the player in spectator mode once they respawn) - could that be related?

**Comment by Cybermaxke** [comment] 2017-05-18 19:52
When a Player dies, the player will be regenerated both on the server and client side, this will reset almost everything.
I think I may have an idea why the issue occurs, but I will have to test some things to confirm it.

**Comment by Cybermaxke** [comment] 2017-05-18 23:04
Ok, I can also not reproduce the issue with the latest bleeding version. The only ways that is issue can occur are:
- Changing a players tab list entry game mode, to one that doesn't match the players game mode
  -> Can be fixed by setting the proper game mode
- Removing a player from it's own tab list, and then updating the game mode
  -> Can be fixed by readding the player, and setting the proper game mode

I have no idea why you are having this issue without interacting with the Tab Lists.

**Comment by ryantheleach** [comment] 2017-05-19 07:57
Is another mod or plugin interacting with the tablist?

**Comment by widd** [comment] 2017-05-20 07:22
@Cybermaxke As far as I can tell the tab list doesn't update to reflect the gamemode change - I'll see if doing it elsewhere causes the same situation.

@ryantheleach No - this is on a simple test server.

**Comment by widd** [comment] 2017-05-20 07:29
This seems to do the trick to replicate it (tested with SpongeVanilla 1.11.2 (API 6.1.0) BETA-3):
```
@Listener
public void onSpawn(RespawnPlayerEvent event) {
	if (event.isDeath()) {
		event.getTargetEntity().offer(Keys.GAME_MODE, GameModes.SPECTATOR);
	}
}
```

Offering it works fine everywhere else - the tab list seems to not update correctly upon respawning if the gamemode is set at this point.

**Comment by ImMorpheus** [comment] 2018-01-27 21:38
Still happening on 1.12 (bleeding branch).

This is due to the fact that the event is thrown before the player if fully recreated https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L551

(As a quick test, moving the event to the end of the method would fix everything, but then you wouldn't be able to change the player location). 

I think a good solution would be to throw a RespawnPlayerEvent.Post at the end of the method. (Input wanted)

**Closed as completed** 2019-01-26 23:34 UTC
Labels: type: bug, system: data, system: event, version: 1.11 (u), version: 1.12 (u), status: pr pending
