### ISSUE TITLE
Crash with mixins

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/Sponge#2458] opened 2020-01-03 12:37 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.9-RC3976
- SpongeVanilla version: -
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods:
 del

**Issue Description**

Server crash on start (spongeforge-1.12.2-2838-7.1.9-RC3973 - working, RC3976 - crash)
https://pastebin.com/sbV2T43g

**Comment by dualspiral** [comment] 2020-01-03 12:58
Duplicate of #2457

**Closed as completed by dualspiral** 2020-01-03 12:58 UTC
Labels: resolution: duplicate

**Comment by bigenergy** [comment] 2020-01-03 18:15
@dualspiral Not duplicate. Retest latest spongeforge 3977 - https://pastebin.com/y3MFaGZ6

**Comment by dualspiral** [comment] 2020-01-03 19:14
Rename sponge to start with `a`. It's another mod loading mixin 0.7.11, that build uses 0.8. Not our bug.

Alternatively, I would _strongly_ recommend you use the RB, not the latest versions as we are stabilising the Mixin upgrade. RBs are recommended for a reason.
