### ISSUE TITLE
Doors Duplicate When Broken

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/Sponge#2262] opened 2019-05-12 11:19 UTC
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3708.jar
- Java version: 8
- Operating System: Ubuntu

- Plugins/Mods:
![Image of Yaktocat](https://i.imgur.com/tIrcKeS.png)

**Issue Description**
When you break any door (whether it be from Vanilla Minecraft or Modded Minecraft) it duplicates when broken. This only happens when you break the bottom part of the door. Breaking the top of the door doesn't cause the duplication. You do need to make sure `-Dsponge.shouldFireAll=true` is on to replicate. I have tested without sponge, removed pretty much all of my plugins and mods, and narrowed it down to sponge causing the issue.

**Comment by phit** [comment] 2019-05-16 07:34
probably related https://github.com/SpongePowered/SpongeCommon/issues/2259

**Comment by gabizou** [comment] 2019-05-16 23:06
Fixed with an experimental fix, it shouldn't break other things, but let me know if there's multi-block structures that end up breaking somehow.

**Comment by Aiidoneus** [comment] 2019-05-17 02:09
Did look like it fixed the doors duplicating. Will let you know when I can if any issues arise from it. 
Thank you

**Comment by runescapejon** [comment] 2019-05-17 02:41
@gabizou i have test it this and it seem it's fixed but randomly dupe, it doesn't dupe consistently just have to keep trying and then you'll get it

**Comment by gabizou** [comment] 2019-05-22 02:53
@runescapejon going to need a better explanation, how reproducible is it? How have you seen it reproduced?

Reason why I ask: when I wrote the fix, I noticed it duped when breaking the bottom half of the door because of the neighbor notification from the top half of the door. Essentially, what happens is: the bottom is broken, the top block is neighbor notified and because it's finding out that the bottom is broken, it'll drop itself. This is where sponge is intercepting the drop, because it already knows that the bottom is dropping, it prevents the block from dropping itself *again* if and only if the block was already broken at that position with that state (because I don't know, some mod could be doing something crazy with different block states). Now, because I didn't want it to go through and check all previous transactions, I only have it checking the last block change, which could possibly be avoiding previous block changes, but this is where I need something that reproduces the issue entirely, because if that's the case, well, then I need to write it to check all previous transactions to search if any of them match for the block being told to drop.

**Comment by runescapejon** [comment] 2019-05-22 03:44
my apologies, it seem when i ran a quick test and upload it the jar the test server had a corrupt download and the other downgrade it version was installed. At the time when i hop on the server and just did the test and didn't see or notice i still had the old spongeforge version that the new jar corrupted from a download.

**Comment by gabizou** [comment] 2019-05-28 17:16
Re-opening since it's been re-broken again....

**Closed as completed** 2019-05-28 17:29 UTC
Labels: type: bug, version: 1.12 (u)
