### ISSUE TITLE
Piston/Shulker box Duplication Bug Spongeforge

### ISSUE THREAD

**Issue by HallowedDream** [SpongePowered/Sponge#2155] opened 2018-12-04 01:52 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.4 
- SpongeVanilla version: N/A
- Java version: build 1.8.0_171-b11
- Operating System: Windows v1803 (OS Build 17134. 407)

- Plugins/Mods: Pixelmon 6.3.4, Nucleus-1.6.1-S7.1-MC1.12.2, griefprevention-1.12.2-4.3.0.646.jar

**Issue Description**
using spongeforge 1.12.2-2768-7.1.4  the sticky piston / shulker box dupe is still active. We replicated it with multiple versions of sponge forge. from 1.12.2-2705-7.1.0-BETA-3392 to 1.12.2-2768-7.1.4, this issue has been crated by multiple people on my server while changing spongeforge versions.

**Recreation Steps**
- make grief prevention claim
- make a redstone clock that goes real fast inside the claim
- connect to sticky piston
(at this point the piston should be spamming really fast)
- place shulker box in front of the sticky piston.
- try to look into the shulker box when placing (hard to do but do able)
- the dupe glitch will continue while you are in the shulker box GUI, the shulker box will be produces a mass amount of times

**Recreation Steps 2**
- without Grief Prevention Claim
- make a redstone clock that goes real fast inside the claim
- connect to sticky piston
(at this point the piston should be spamming really fast)
- place shulker box in front of the sticky piston.
- eventually if you keep placing it over and over the shulker box will duplicate without having to look inside of 

(Flicking a lever with a sticky piston also causes the block to duplicate )
https://gyazo.com/d7e9a8fe6814f9743fec6e4c289d9a7c (Ras)

https://imgur.com/a/Mqqj9zj
https://imgur.com/a/k85k4SO

**Comment by gabizou** [comment] 2018-12-04 16:46
Duplicate of 
https://github.com/SpongePowered/SpongeForge/issues/2443

The fix is rather complicated and needs more time to be developed without breaking a ton of stuff.

**Closed as completed by gabizou** 2018-12-04 16:46 UTC
Labels: version: 1.12 (u)
