### ISSUE TITLE
Phase incompatibility on player.closeInventory()

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/Sponge#1865] opened 2018-04-08 10:13 UTC
**I am currently running**

/* Minecraft : 1.12.2                                                                                                                   */
/* SpongeAPI : 7.1.0-SNAPSHOT-ee6579e                                                                                                   */
/* SpongeForge : 1.12.2-2611-7.1.0-BETA-2996                                                                                            */
/* Minecraft Forge : 14.23.2.2640
Debian
Java 8_160

- Plugins/Mods: my own worldedit dynmap and nucleus

**Issue Description**
I get this phase error, which I dont understand. What does it mean and what can I do against it?

possibly related:
https://github.com/SpongePowered/SpongeCommon/issues/1166
https://github.com/SpongePowered/SpongeCommon/issues/1173

```
/****************************************************************************************************************************************/
/* Phase incompatibility detected! Attempting to switch to an invalid phase!                                                            */
/*   Current Phase : GeneralPhase{}                                                                                                     */
/*   Current State : GeneralPhase{}{PostState}                                                                                          */
/*   Entering incompatible Phase : PacketPhase{}                                                                                        */
/*   Entering incompatible State : PacketPhase{}{CloseWindowState}                                                                      */
/* Current phases :                                                                                                                     */
/*   - Phase: GeneralPhase{}{PostState}                                                                                                 */
/*     Context:                                                                                                                         */
/*     - Owner: null                                                                                                                    */
/*     - Notifier: null                                                                                                                 */
/*     - Source: null                                                                                                                   */
/*     - CapturedBlocks: CapturedBlocksSupplier{Captured=0}                                                                             */
/*     - BlockItemDrops: BlockItemDropsSupplier{Captured=0}                                                                             */
/*     - BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0}                                                                 */
/*     - CapturedItems: CapturedItemsSupplier{Captured=0}                                                                               */
/*     - CapturedEntities: CapturedEntitiesSupplier{Captured=0}                                                                         */
/*     - CapturedItemStack: CapturedItemStackSupplier{Captured=0}                                                                       */
/*     - EntityItemDrops: EntityItemDropsSupplier{Captured=0}                                                                           */
/*     - EntityItemEntityDrops: EntityItemEntityDropsSupplier{Captured=0}                                                               */
/*     - BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0}                                                                */
/*     - CapturedBlockPosition: null                                                                                                    */
/*     - UnwindingState: PacketPhase{}{PrimaryInventoryClickState}                                                                      */
/*     - UnwindingContext: InventoryPacketContext{isCompleted=true}                                                                     */
/*   - Phase: PluginPhase{}{ScheduledTaskPhaseState}                                                                                    */
/*     Context:                                                                                                                         */
/*     - Owner: null                                                                                                                    */
/*     - Notifier: null                                                                                                                 */
/*     - Source: com.google.common.util.concurrent.ListenableFutureTask@6e76a9bc                                                        */
/*     - CapturedBlocks: CapturedBlocksSupplier{Captured=0}                                                                             */
/*     - BlockItemDrops: BlockItemDropsSupplier{Captured=0}                                                                             */
/*     - BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0}                                                                 */
/*     - CapturedItems: CapturedItemsSupplier{Captured=0}                                                                               */
/*     - CapturedEntities: CapturedEntitiesSupplier{Captured=0}                                                                         */
/*     - CapturedItemStack: CapturedItemStackSupplier{Captured=0}                                                                       */
/*     - EntityItemDrops: null                                                                                                          */
/*     - EntityItemEntityDrops: null                                                                                                    */
/*     - BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0}                                                                */
/*     - CapturedBlockPosition: null                                                                                                    */
/*   Printing stack trace :                                                                                                             */
/* java.lang.Exception: Stack trace                                                                                                     */
/*     org.spongepowered.common.event.tracking.PhaseTracker.printPhaseIncompatibility(PhaseTracker.java:354)                            */
/*     org.spongepowered.common.event.tracking.PhaseTracker.switchToPhase(PhaseTracker.java:157)                                        */
/*     org.spongepowered.common.event.tracking.PhaseContext.buildAndSwitch(PhaseContext.java:193)                                       */
/*     net.minecraft.entity.player.EntityPlayerMP.closeInventory(EntityPlayerMP.java:4183)                                              */
/*     goldsunsaga.rpg.teleport.TeleportMenu.teleportPlayerTo(Teleport.kt:244)                                                          */
/*     goldsunsaga.rpg.teleport.TeleportMenu$openTeleportMenu$$inlined$map$lambda$1.invoke(Teleport.kt:229)                             */
/*     goldsunsaga.rpg.teleport.TeleportMenu$openTeleportMenu$$inlined$map$lambda$1.invoke(Teleport.kt:227)                             */
/*     goldsunsaga.core.item.InventoryMenuBuilder$withItem$2.interact(MenuBuilder.kt:253)                                               */
/*     goldsunsaga.core.item.InventoryListener.onInventoryClick(MenuBuilder.kt:181)                                                     */
/*     org.spongepowered.common.event.listener.ClickInventoryEventListener_InventoryListener_onInventoryClick112.handle(Unknown Source) */
/*     org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)                                             */
/*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335)                                           */
/*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368)                                           */
/*     org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427)                                              */
/*     org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207)                                                               */
/*     org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:202)        */
/*     org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:55)         */
/*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:211)                                        */
/*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:392)                                                */
/*     org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151)                                                 */
/*     net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539)                                         */
/*     net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)                                                                      */
/*     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                          */
/*     java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                         */
/*     net.minecraft.util.Util.func_181617_a(SourceFile:46)                                                                             */
/*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276)                                                 */
/*     net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3977)                                            */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)                                                      */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)                                            */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)                                                      */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)                                                               */
/*     java.lang.Thread.run(Thread.java:748)                                                                                            */
/*                                                                                                                                      */
/* Minecraft : 1.12.2                                                                                                                   */
/* SpongeAPI : 7.1.0-SNAPSHOT-ee6579e                                                                                                   */
/* SpongeForge : 1.12.2-2611-7.1.0-BETA-2996                                                                                            */
/* Minecraft Forge : 14.23.2.2640                                                                                                       */
/****************************************************************************************************************************************/
```

This my code. But I think its mostly irrelevant beyond the `player.closeInventory()` call in `teleportPlayerTo`
```kotlin
object TeleportMenu {
    val title = Text.of(TextColors.GREEN, "Teleport")

    val teleportStack = SimpleItemBuilder(ItemTypes.EMERALD)
            .withName(title)
            .withLore(Text.of(TextColors.GRAY, "Where do you want to go?"))
            .stack

    fun openTeleportMenu(player: Player, price: Int = 0, teleportCause: TeleportType) {
        val inventoryItems = WorldRegistry.map.values.map { regWorld ->
            val stack = SimpleItemBuilder(ItemTypes.FILLED_MAP)
                    .withName(regWorld.displayName)
                    .withLore(Text.of(TextColors.GRAY, regWorld.description))
                    .stack

            InventoryItem(stack, listener = object : ItemListenerOnInteract {
                override fun invoke(player: Player, action: InventoryClickType, stack: ItemStack, slot: Slot) {
                    teleportPlayerTo(player, regWorld, teleportCause)
                }
            })
        }

        val displayMenu = DisplayMenu(inventoryItems, title)
                .withColumnLayout(MenuLayout.ColumnLayout.FULL)
                .withRowLayout(MenuLayout.BIGBLOCKCENTERED)
                .calc()
                .getInventoryMenu()[0]

        displayMenu.show(player)
    }

    fun teleportPlayerTo(player: Player, regWorld: RegisteredWorld, teleportCause: TeleportType) {
        player.closeInventory()

        val world = regWorld.getWorld()
        if (world == null) {
            player.sendLang(TeleportManager.lang.unableToFindWorld, regWorld.displayName)
            Rpg.instance.logger.error("${player.name} tried to teleport via menu to ${regWorld.id} but the world cannot be found.")
            return
        }

        val location = when (teleportCause) {
            TeleportType.PSYNERGY_SERVICE -> TeleportManager.getPsynergyWorldTeleportLocation(world)
            TeleportType.SHIP_SERVICE -> TeleportManager.getShipWorldTeleportLocation(world)
        }

        player.sendLang(TeleportManager.lang.teleportingTo, regWorld.displayName)

        val success = player.setLocation(location)
        if (!success) {
            player.sendLang(TeleportManager.lang.unableToTeleport, regWorld.displayName, location.position.toString())
        }
    }
}
```

**Comment by SimonFlash** [comment] 2018-04-08 10:48
This issue is caused by closing the player's inventory during the `ClickInventoryEvent`, as shown in the other issues you linked. If you change the player's inventory during the event, the event is no longer able to be executed or cancelled correctly - the inventory to return any items to has disappeared, and the state is now invalid. You can avoid this by delaying the call to `closeInventory` until after the event finishes using a `Task`.

I've spoken with @Faithcaio about this issue before, as it's something that pops up rather frequently and is hard to make sense of based on the phase tracker error alone. It *could* be possible to catch any calls to `closeInventory` and ensure they are not executed until after the event ends, but I'm not sure how feasible this is currently and whether it's the 'correct' solution. The majority of phase issues are caused by developers doing things at the incorrect time, and it's not really Sponge's position to try to catch and fix that behavior. In this case though, there may be a way to change this so it works as intended or at the very least be made clear in the javadocs and phase tracker error.

**Comment by nihiluis** [comment] 2018-04-08 10:54
I'd expect a proper exception here then and not a generic phase error with no info. too think one could add at least an info in the doc

**Comment by ryantheleach** [comment] 2018-04-16 01:18
https://github.com/SpongePowered/SpongeCommon/pull/1869

**Comment by JBYoshi** [comment] 2018-08-17 02:42
Can this be closed now?

**Closed as completed** 2018-08-17 06:20 UTC
Labels: version: 1.12 (u)
