### ISSUE TITLE
Sounds hilariously wrong for common minecraft things

### ISSUE THREAD

**Issue by mcmonkey4eva** [SpongePowered/Sponge#1058] opened 2016-12-07 10:36 UTC
Lightning flash? That's the sound of a shovel breaking!
Zombie spawned and caught fire? Oh no, sounds like a villager in drowning...

I think some map somewhere got mixed up. No idea what it would be, though.

**Comment by kashike** [comment] 2016-12-07 10:57
I reproduced this the other day, but now I can't.

**Comment by kashike** [comment] 2016-12-08 05:23
So this is apparently happening with Forge as well.
```
16:55:34*       Keridos | having a weird issue here in single player my sounds are fine
16:55:56*       Keridos | but when I try them on multiplayer it doesnt play the correct sound but the vanilla minecraft cave sounds or something like that
```

**Comment by codeHusky** [comment] 2016-12-19 14:25
I did notice that on some rare occasions, method parameter names don't match up with parameter types. Someone must've been drunk over at Forge last month.

**Comment by Limeth** [comment] 2016-12-19 16:37
Having the same issue. When I post an implementation of the `ChangeBlockEvent.Place`, the block is placed and a sound of a dog breathing is played.

**Comment by codeHusky** [comment] 2016-12-19 17:10
@Limeth That's, uh, kind of terrifying.

**Comment by Limeth** [comment] 2016-12-20 16:21
Snowmen have skeleton sounds. Weirdly, this bug is only affecting my local server instance, I am not encountering any odd sounds on my public server. Maybe something got incorrectly generated somewhere? Weird.

**Comment by leonbaronick** [comment] 2017-01-07 14:21
Definitely reproducable but it only happens with spongeforge. spongevailla works fine. It also happens with just forge installed so i think it is a forge bug and has nothing to do with sponge.

**Comment by Deamon5550** [comment] 2017-01-07 19:31
Is there a forge issue open for this then?

**Comment by kashike** [comment] 2017-01-07 23:07
https://github.com/MinecraftForge/MinecraftForge/issues/3613

**Comment by gabizou** [comment] 2017-03-23 07:05
Closing as this is more of a forge bug that could possibly be fixed in forge or Spongeforge itself.

**Closed as completed by gabizou** 2017-03-23 07:05 UTC
Labels: version: 1.11 (u)

**Comment by Yeregorix** [comment] 2017-06-28 13:16
I have the same issue since few months in my dev environment (currently using SpongeForge 1.12) . The issue disappears if I remove SpongeForge (1.12-2368-7.0.0-BETA-2423:dev) and keep only Forge (2368).

**Comment by ryantheleach** [comment] 2017-07-04 11:05
Discovered this in [bleeding ](https://github.com/SpongePowered/SpongeForge/commit/7789e67bbd1ef2ed2411d08d23c1ea006ef7aa56) logs, after updating my workspace from 1.11 to 1.12. [Full Log](https://gist.github.com/ryantheleach/a81c9e08908b4f72f4ab375324983230)

However, all sounds were correct, (I was running from client, could easily see this being a client server mismatch)

```
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.ghast Expected: 331 Got: 493
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.blaze Expected: 324 Got: 494
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.boat.paddle_water Expected: 151 Got: 495
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.hurt Expected: 277 Got: 496
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.stray Expected: 341 Got: 497
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.zombie Expected: 348 Got: 498
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.ambient Expected: 274 Got: 499
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.polar_bear Expected: 335 Got: 500
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.husk Expected: 332 Got: 501
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.note.chime Expected: 73 Got: 502
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.witch Expected: 344 Got: 503
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.hurt Expected: 323 Got: 504
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.endereye.death Expected: 195 Got: 505
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.enderman Expected: 328 Got: 506
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.note.guitar Expected: 75 Got: 507
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.creeper Expected: 325 Got: 508
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.skeleton Expected: 338 Got: 509
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.wither_skeleton Expected: 346 Got: 510
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.mirror_move Expected: 278 Got: 511
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.wolf Expected: 347 Got: 512
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.death Expected: 320 Got: 513
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.player.hurt_drown Expected: 368 Got: 514
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.prepare_blindness Expected: 279 Got: 515
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.vex Expected: 342 Got: 516
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.player.hurt_on_fire Expected: 369 Got: 517
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.illusion_illager Expected: 333 Got: 518
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.zombie_pigman Expected: 349 Got: 519
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.ambient Expected: 319 Got: 520
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.vindication_illager Expected: 343 Got: 521
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.silverfish Expected: 337 Got: 522
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.note.bell Expected: 72 Got: 523
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.end_portal_frame.fill Expected: 27 Got: 524
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.eat Expected: 321 Got: 525
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.evocation_illager Expected: 330 Got: 526
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.prepare_mirror Expected: 280 Got: 527
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.magmacube Expected: 334 Got: 528
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.note.xylophone Expected: 80 Got: 529
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.elder_guardian Expected: 326 Got: 530
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.endermite Expected: 329 Got: 531
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.end_portal.spawn Expected: 26 Got: 532
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.cast_spell Expected: 275 Got: 533
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:block.note.flute Expected: 74 Got: 534
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.enderdragon Expected: 327 Got: 535
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.shulker Expected: 336 Got: 536
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.slime Expected: 339 Got: 537
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.bobber.retrieve Expected: 152 Got: 538
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.spider Expected: 340 Got: 539
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.fly Expected: 322 Got: 540
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.boat.paddle_land Expected: 150 Got: 541
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.illusion_illager.death Expected: 276 Got: 542
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.wither Expected: 345 Got: 543
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.imitate.zombie_villager Expected: 350 Got: 544
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:ui.toast.in Expected: 544 Got: 547
[20:30:28] [Server thread/WARN] [FML]: Registry SoundEvent: Object did not get ID it asked for. Name: minecraft:entity.parrot.step Expected: 351 Got: 548
```

**Comment by Yeregorix** [comment] 2017-07-10 09:16
I fixed this issue in my dev environment, the fml registry in the level.dat file was invalid, so I merged my invalid file with a valid one.
