### ISSUE TITLE
Server does not start due to special characters on the root path

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#3331] opened 2021-03-11 21:50 UTC
**I am currently running**
- SpongeVanilla version: 1.16.5-8.0.0
- Java version: OpenJDK "1.8.0_282"
- Operating System: Kubuntu 18.04 LTS
- Plugins/Mods: N/A

**Issue Description**
If the path to the server root directory contains special characters (for example, a space or Cyrillic symbols), the server will crash with the following stack trace:
```
[23:41:20] [main/ERROR]: Failed to invoke main class org.spongepowered.vanilla.applaunch.Main due to an error: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.spongepowered.vanilla.installer.InstallerMain.invokeMain(InstallerMain.java:107)                                                                                
        at org.spongepowered.vanilla.installer.InstallerMain.run(InstallerMain.java:100)                                                                                       
        at org.spongepowered.vanilla.installer.InstallerMain.main(InstallerMain.java:64)                                                                                       
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException                                                                                             
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)                                                                    
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)                                                                                      
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)                                                                                      
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)                                                                                                                 
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at org.spongepowered.vanilla.applaunch.Main.run(Main.java:91)
        at org.spongepowered.vanilla.applaunch.Main.main(Main.java:62)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.spongepowered.vanilla.applaunch.handler.prod.ServerProdLaunchHandler.launchService0(ServerProdLaunchHandler.java:43)
        at org.spongepowered.vanilla.applaunch.handler.AbstractVanillaLaunchHandler.lambda$launchService$1(AbstractVanillaLaunchHandler.java:127)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 13 more
Caused by: java.lang.ExceptionInInitializerError
        at org.spongepowered.common.registry.SpongeFactoryProvider.registerDefaultFactories(SpongeFactoryProvider.java:219)
        at org.spongepowered.common.SpongeLifecycle.establishFactories(SpongeLifecycle.java:81)
        at org.spongepowered.common.SpongeBootstrap.perform(SpongeBootstrap.java:61)
        at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launchPlatform(DedicatedServerLaunch.java:55)
        at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launch(DedicatedServerLaunch.java:43)
        ... 20 more
Caused by: java.lang.ClassCastException: net.minecraft.resources.ResourceLocation cannot be cast to org.spongepowered.api.ResourceKey
        at org.spongepowered.common.world.SpongeWorldTypeEffect$FactoryImpl.<clinit>(SpongeWorldTypeEffect.java:52)
        ... 25 more
```
I assume these are characters that are URL encoded through `%`.
If you start the server from under IntelliJ IDEA, there is no such error. In this case, the server starts without dynamically loading libraries.

Full log: https://pastebin.com/s3Q1LdrS

**Comment by zml2008** [comment] 2021-03-11 22:04
It appears the log you are linking is quite old. The installer has changed a fair bit since January, please send a full `debug.log` from the latest build at https://repo.spongepowered.org/service/rest/repository/browse/maven-public/org/spongepowered/spongevanilla/ -- as of now, that is build 475.

**Comment by Lignium** [comment] 2021-03-12 17:15
Full logs for 475: [debug.log](https://github.com/SpongePowered/Sponge/files/6131743/debug.log), [latest_launcher.log](https://github.com/SpongePowered/Sponge/files/6131744/latest_launcher.log), [latest.log](https://github.com/SpongePowered/Sponge/files/6131745/latest.log)

**Comment by XakepSDK** [comment] 2021-03-12 18:03
Can reproduce; probably affects all non ASCII characters; space is not affected
Real error; no idea why last part is not in his logs
```
[00:02:32] [main/ERROR]: Failed to invoke main class org.spongepowered.vanilla.applaunch.Main due to an error: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.spongepowered.vanilla.installer.InstallerMain.invokeMain(InstallerMain.java:107)
        at org.spongepowered.vanilla.installer.InstallerMain.run(InstallerMain.java:100)
        at org.spongepowered.vanilla.installer.InstallerMain.main(InstallerMain.java:64)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at org.spongepowered.vanilla.applaunch.Main.run(Main.java:91)
        at org.spongepowered.vanilla.applaunch.Main.main(Main.java:62)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.spongepowered.vanilla.applaunch.handler.prod.ServerProdLaunchHandler.launchService0(ServerProdLaunchHandler.java:43)
        at org.spongepowered.vanilla.applaunch.handler.AbstractVanillaLaunchHandler.lambda$launchService$1(AbstractVanillaLaunchHandler.java:127)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: Bad escape
        at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:103)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at org.spongepowered.vanilla.launch.VanillaLaunch.createPlatformPlugins(VanillaLaunch.java:115)
        at org.spongepowered.common.launch.Launch.onLaunch(Launch.java:140)
        at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launchPlatform(DedicatedServerLaunch.java:52)
        at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launch(DedicatedServerLaunch.java:43)
        ... 20 more
```

**Comment by dualspiral** [comment] 2021-03-12 18:20
> Can reproduce; probably affects all non ASCII characters; space is not affected
> Real error; no idea why last part is not in his logs

Because you're using different versions of Java. @Lignium is using Java 8, you're using Java 11+. This is the reason we ask for Java version in bug reports.

For what it's worth, I can reproduce this as far as having a space in the file name goes with Java 8, but it works fine with Java 11.

**Comment by dualspiral** [comment] 2021-03-12 18:20
> Can reproduce; probably affects all non ASCII characters; space is not affected
> Real error; no idea why last part is not in his logs

Because you're using different versions of Java. @Lignium is using Java 8, you're using Java 11+. This is the reason we ask for Java version in bug reports.

For what it's worth, I can reproduce this as far as having a space in the file name goes with Java 8, but it works fine with Java 11.

**Comment by zml2008** [comment] 2021-03-12 18:31
I'll add that there are other platform-specific issues involved -- on Windows with cyrillic characters in the path but no spaces, I can't even get libraries to add to the classpath

**Comment by Lignium** [comment] 2021-03-12 18:40
I checked in Java 11, it turns out that the space no longer provokes an error, but the cyrillic does.

**Comment by zml2008** [comment] 2021-03-13 02:50
I will resolve the issue in JDK11+. However, it seems like there's some sort of bug with URL unescaping in JDK 8, so ModLauncher is failing to read Sponge's classes:

```
[12Mar2021 18:35:54] [main/TRACE] [c.mod.mod.TransformingClassLoader/CLASSLOADING]: Failed to load bytes for class org.spongepowered.vanilla.applaunch.mixin.VanillaLaunchMixinConnector at jar:file:///home/zml/dev/mc/sponge/%25D0%2597%25D0%25B0%25D0%25B3%25D1%2580%25D1%2583%25D0%25B7%25D0%25BA%25D0%25B8/spongevanilla-1.16.5-8.0.0-RC0-universal.jar!/org/spongepowered/vanilla/applaunch/mixin/VanillaLaunchMixinConnector.class reason classloading
java.io.FileNotFoundException: /home/zml/dev/mc/sponge/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/spongevanilla-1.16.5-8.0.0-RC0-universal.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_282]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_282]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_282]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_282]
	at java.util.jar.JarFile.<init>(JarFile.java:103) ~[?:1.8.0_282]
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93) ~[?:1.8.0_282]
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69) ~[?:1.8.0_282]
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84) ~[?:1.8.0_282]
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122) ~[?:1.8.0_282]
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152) ~[?:1.8.0_282]
	at cpw.mods.modlauncher.TransformingClassLoader$AutoURLConnection.<init>(TransformingClassLoader.java:174) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.9.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_282]
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-8.0.9.jar:?]
	at org.spongepowered.vanilla.applaunch.Main.run(Main.java:91) ~[spongevanilla-1.16.5-8.0.0-RC0-universal.jar:1.16.5-8.0.0-RC0]
	at org.spongepowered.vanilla.applaunch.Main.main(Main.java:62) ~[spongevanilla-1.16.5-8.0.0-RC0-universal.jar:1.16.5-8.0.0-RC0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.spongepowered.vanilla.installer.InstallerMain.invokeMain(InstallerMain.java:107) ~[spongevanilla-1.16.5-8.0.0-RC0-universal.jar:1.16.5-8.0.0-RC0]
	at org.spongepowered.vanilla.installer.InstallerMain.run(InstallerMain.java:100) ~[spongevanilla-1.16.5-8.0.0-RC0-universal.jar:1.16.5-8.0.0-RC0]
	at org.spongepowered.vanilla.installer.InstallerMain.main(InstallerMain.java:64) ~[spongevanilla-1.16.5-8.0.0-RC0-universal.jar:1.16.5-8.0.0-RC0]
[12Mar2021 18:35:54] [main/TRACE] [c.mod.mod.TransformingClassLoader/CLASSLOADING]: Delegating to parent classloader org.spongepowered.vanilla.applaunch.mixin.VanillaLaunchMixinConnector
```

**Comment by zml2008** [comment] 2021-03-13 03:01
see https://github.com/SpongePowered/Sponge/commit/dbb433e50726930113fe2b259fecccd0fd8f35c7 for a partial fix

**Comment by Zidane** [comment] 2021-07-07 04:16
Resolving this. If another case arises in the future, create a new ticket with details on that specific example and it can be looked into some more.

**Closed as completed by Zidane** 2021-07-07 04:16 UTC
Labels: type: bug, version: 1.16 (u)
