### ISSUE TITLE
Structures generating - Compatiblity of SpongeForge with Reccurent Complex mod

### ISSUE THREAD

**Issue by Krosta8** [SpongePowered/Sponge#1836] opened 2018-03-17 20:07 UTC
**I am currently running**

- SpongeForge version: 2931 (latest recommended)
- SpongeVanilla version: 
- Java version: 1.8.0 build 144
- Operating System: Linux

- Plugins/Mods: Plugins (21): Minecraft, Minecraft Coder Pack, Sponge API, SpongeForge, FastAsyncWorldEdit, BungeeTabListPlus-SpongeBridge, CatClearLag, CmdBuilder, CmdControl, CommandUtils, DailyRewards, GriefPrevention, LuckPerms, Nucleus, PlaceHolderAPI, ProjectCore, ProjectPortals, Total Economy, UltimateChat, VirtualChest, WorldEdit
Mods (21): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, BetterQuesting, CraftTweaker2, IronChest, JourneyMap, JEI, Malisis Advert, Malisis Doors, Malisis Core, Mantle, ModControl, MrCrayFish Furniture Mod, NetherPortalFix,  Tinker's Construct, IvToolkit, Reccurent Complex

**Issue Description**
Buildings from Reccurent Complex are not properly generated. Sometimes there is one chunk generated badly and it can influence natural structures. The most common problem is in villages. 
It is easy to reproduce. Install IvToolkit (needed to run Reccurent Complex), Reccurent Complex and SF. Then use /locate Village and you will see the problem with generating.
If you try it without SF or in single player, there is no problem.
Links: 
IvToolkit [https://minecraft.curseforge.com/projects/ivtoolkit/files/2443253/download](url)
Reccurent Complex [https://minecraft.curseforge.com/projects/recurrent-complex/files/2516761/download](url)

**Comment by phit** [comment] 2018-03-17 21:03
dupe of https://github.com/SpongePowered/SpongeForge/issues/1949
and wrong repo, mod bugs please on the Spongeforge tracker

**Closed as completed by phit** 2018-03-17 21:03 UTC
Labels: resolution: duplicate, version: 1.12 (u)
