### ISSUE TITLE
ChangeInventoryEvent not being fired after give command

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1392] opened 2017-06-11 08:24 UTC
**I am currently running...**

- SpongeForge version:  - 
- SpongeVanilla version:  1.12-7.0.0-BETA-278, however this is long-term problem, i enountered it with multiple previous versions of sponge vanilla (1.11, 1.10)
- Java version: 1.8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

When a player gives himself  an item by typing command /give name id the event ChangeInventoryEvent is not being fired.

**Comment by parlough** [comment] 2017-06-18 22:42
This is a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1309

**Closed as completed** 2017-06-18 22:42 UTC
Labels: resolution: duplicate, system: event, system: inventory
