### ISSUE TITLE
Detecting a runaway phase! Potentially a problem where  something isn't completing a phase!!!           

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1897] opened 2018-05-01 08:25 UTC
- SpongeVanilla version: 1.7 build 40
- Java version: 1.8
- Operating System: win10

- Plugins/Mods: https://github.com/NeumimTo/spongebugs

Build the plugin, ingame give yourself a bow and an arrow and shoot any living entity. 
My goal is: 
  cancell the first damage event,
  while inside the event handler damage entity explicitly by calling entity.damage with custom damage source  MyDamageSource
  listen for another DamageEntityEvent with MyDamageSource in the cause & set final damage in another listener. 

This call ends in an infinite loop of this https://pastebin.com/SzsPrrwh

**Comment by ryantheleach** [comment] 2018-05-02 01:36
Don't cancel, instead just edit the damages on the event.

This allows other plugins to see the damage you added and react if necessary.

Otherwise you are causing a new damage event to fire immediately after cancelling, inside the event handler, before the event has fully resolved in all plugins.


If you must do this by cancelling, and I strongly recommend **not** doing this. At least make sure not to cancel events with your damage source, or do the damage after the event has resolved by use of a scheduled task.

**Comment by gabizou** [comment] 2018-05-02 22:29
Figured out why this is causing recursion.
The old `DamageSource` is still on the Cause stack, so `@First` is still matching the "rethrown" event.
You are then throwing the new event with the *new* direct source, but you're not filtering the new event's cause to ignore the new direct source.

This can be solved with using `@Root` for the direct root cause instead of using `@First`.
There's no way to clean the cause stack while in a listener, unless you create the event yourself with your own constructed `Cause`.

**Closed as completed by gabizou** 2018-05-02 22:29 UTC
