### ISSUE TITLE
Failed loading Sponge data for World {All dimensions} Report to Sponge ASAP.(Crash)

### ISSUE THREAD

**Issue by Tommeh3** [SpongePowered/Sponge#1646] opened 2017-12-11 18:01 UTC
My server has been running fine for over a month after which it was suddenly unable to load due to the issue which can be found in the title and log(Failed loading Sponge data for World...)
I removed spongeforge and all plugins after which the server was able to load and after that i re-added spongeforge and then it couldn't load anymore yet again so it's clearly spongeforge.

- SpongeForge version: Latest for mc 1.10.2 (1.10.2-2477-5.2.0-BETA-2731)
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_131, running on Linux:amd64:4.4.30-mod-std-ipv6-64
- Operating System: Linux
-Full Log: https://www.dropbox.com/s/glmdb52kdpu6byn/fml-server-latest.log?dl=0

**Comment by dualspiral** [comment] 2017-12-11 18:48
Relevant parts:

```
[12:52:48] [Server thread/ERROR] [Sponge/]: Failed loading Sponge data for World [DIM1]}. Report to Sponge ASAP.
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_131]
	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:25) ~[ea.class:?]
	at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:910) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:658) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:52:48] [Server thread/ERROR] [Sponge/]: Failed loading Sponge data for World [DIM-1]}. Report to Sponge ASAP.
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_131]
	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:25) ~[ea.class:?]
	at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:910) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:658) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:52:48] [Server thread/ERROR] [Sponge/]: Failed loading Sponge data for World [DIM-9999]}. Report to Sponge ASAP.
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_131]
	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:25) ~[ea.class:?]
	at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:910) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:658) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:52:48] [Server thread/ERROR] [Sponge/]: Failed loading Sponge data for World [DIM-11325]}. Report to Sponge ASAP.
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_131]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_131]
	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:25) ~[ea.class:?]
	at org.spongepowered.common.world.WorldManager.registerExistingSpongeDimensions(WorldManager.java:910) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:658) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

Your `level_sponge.dat` files are corrupted, if you've got `level_sponge.dat.old` files in the `world/`, `world/DIM-9999`, `world/DIM-1` and `world/DIM-11325` directories, remove your `level_sponge.dat` files and rename the `old` files as `level_sponge.dat`. Alternatively, just delete the `level_sponge.dat` files.

**Comment by Tommeh3** [comment] 2017-12-11 19:04
I removed them and now i get this 11.12 14:03:05 [Server] Server thread/ERROR Exception reading ./world/level.dat
11.12 14:03:05 [Server] INFO java.io.EOFException
11.12 14:03:05 [Server] INFO at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_131]
11.12 14:03:05 [Server] INFO at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_131]
11.12 14:03:05 [Server] INFO at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_131]
11.12 14:03:05 [Server] INFO at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_131]
11.12 14:03:05 [Server] INFO at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_131]
11.12 14:03:05 [Server] INFO at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:25) ~[ea.class:?]
11.12 14:03:05 [Server] INFO at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:116) [azz.class:?]
11.12 14:03:05 [Server] INFO at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$zpi000(SaveHandler.java:1067) [azy.class:?]
11.12 14:03:05 [Server] INFO at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:121) [azy.class:?]
11.12 14:03:05 [Server] INFO at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:704) [WorldManager.class:1.10.2-2477-5.2.0-BETA-2731]
11.12 14:03:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3491) [MinecraftServer.class:?]
11.12 14:03:05 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
11.12 14:03:05 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
11.12 14:03:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Dockter** [comment] 2017-12-12 02:55
I have experienced the same issue once with 1.12.2 but it was caused by corruption saved to the file when my SSD was freaking out.

**Comment by Tommeh3** [comment] 2017-12-12 20:49
Apperently i had forgotten to remove one of them xD

**Comment by Zidane** [comment] 2018-01-11 19:44
Closing this as it is a world corruption issue on the side of the user and not a Sponge issue. It is also targeting a version of Minecraft we no longer support.

**Closed as completed by Zidane** 2018-01-11 19:44 UTC
Labels: type: support, version: 1.10 (u)
