### ISSUE TITLE
Player#isViewingInventory() needs to be implemented

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1104] opened 2016-12-29 07:30 UTC
I'm trying to enforce keeping a certain inventory open on the client side, but this method always returns false, suggesting that it's not implemented.

**Comment by Zidane** [comment] 2016-12-29 14:31
We accept PRs.

**Comment by codeHusky** [comment] 2016-12-29 16:17
I'd love to do that if I understood anything besides your topmost layer of abstraction.

**Comment by Zidane** [comment] 2016-12-29 16:46
@codeHusky 

Fair enough, that is my blanket response to requests such as these in hopes I can convince someone to help :p.

**Comment by Faithcaio** [comment] 2016-12-29 18:06
Well to be fair inventories are a mess...

But that method works for me. It is even implemented in the API interface: `return getOpenInventory().isPresent();`
What version are you using?

**Comment by codeHusky** [comment] 2016-12-30 00:37
The latest publically available build of SpongeVanilla.

**Comment by JBYoshi** [comment] 2017-01-02 19:56
@On my end, it always returns true. <s>I'm fixing always returning true</s>, but I can't reproduce the original problem.

**Comment by Cybermaxke** [comment] 2017-01-02 22:41
I already opened a pr to fix this issue (always returning true). #1011

**Comment by Cybermaxke** [comment] 2017-11-05 14:58
I could possibly make a new PR for this feature, but tracking packets to make a guess whether the inventory is open or not. It would not be exact but then we already have an idea of whether the inventory is open or not.

Thoughts?

**Comment by ImMorpheus** [comment] 2020-08-16 09:09
Seems to be implemented:

https://github.com/SpongePowered/SpongeAPI/blob/1b3861cc7ed1dfeab6f9b4cfc4bab027e035d041/src/main/java/org/spongepowered/api/entity/living/player/Player.java#L85

https://github.com/SpongePowered/SpongeCommon/blob/16b0cfa3572f9946a94a3ece56e56c14d4189503/src/main/java/org/spongepowered/common/mixin/api/mcp/entity/player/EntityPlayerMPMixin_API.java#L299

I can't find the exact commit it was added because there has been the mixin renaming policy thing, but since the method has been implemented I'm closing this.

**Closed as completed by ImMorpheus** 2020-08-16 09:09 UTC
Labels: system: inventory, type: impl request
