### ISSUE TITLE
Block Swap Issue

### ISSUE THREAD

**Issue by Willynator** [SpongePowered/Sponge#1676] opened 2018-01-01 16:58 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2807.jar
- SpongeVanilla version:  ---
- Java version:  8
- Operating System: Ubuntu Server 14.04 "Trusty Tahr" LTS (64bits) 

- Plugins/Mods:

 Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AGP, FastAsyncWorldEdit, Pixel Extras, Pixelmon, Pixelmon Trainer Commands, Pokestop, Wondertrade, WorldEdit

**Issue Description**
A chest is loaded, empty or filled. Chest becomes unloaded, either from walking a distance or teleporting. Chest appears to be invisible but is still there, contents are gone. 

gist of one of the occurences
https://gist.github.com/Willynator/ef1575c8c8fc2eb693ffcd906e30d5e1

[fml-server-latest.log](https://github.com/SpongePowered/SpongeCommon/files/1596230/fml-server-latest.log)

**Comment by Willynator** [comment] 2018-01-01 17:35
Also wanted to add the issue persisted when running only on base mods for Pixelmon as well.

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Pixelmon

**Comment by Willynator** [comment] 2018-01-01 17:45
Issue still persists with latest version of spongeforge 1.12.2-2555-7.1.0-BETA-2815

**Comment by phit** [comment] 2018-01-01 20:08
see https://github.com/SpongePowered/SpongeForge/issues/1919

**Comment by phit** [comment] 2018-01-07 01:43
closing this in favor of https://github.com/SpongePowered/SpongeForge/issues/1919
as it had more discussion, and nobody seems to be able to reproduce this with SpongeVanilla

**Closed as completed by phit** 2018-01-07 01:43 UTC
Labels: version: 1.12 (u), resolution: moved
