### ISSUE TITLE
PlayerInteractBlockEvent USE (right click) triggers twice

### ISSUE THREAD

**Issue by bruuff** [SpongePowered/Sponge#260] opened 2015-05-03 14:34 UTC
(I am not sure if this is the right place for it, and thus this could have been posted somewhere else)

(Forge + Sponge build 1371)

I just started fiddeling around with sponge, getting some hello world like stuff working, and i when doing this

```java
@Subscribe
    public void onPlayerInteract(PlayerInteractBlockEvent event){
        Location block = event.getBlock();
        Player player = event.getPlayer();
        if(player.getItemInHand().isPresent()){
            ItemStack itemstack = player.getItemInHand().get();
            if(itemstack.getItem().equals(ItemTypes.STICK)){
                player.sendMessage(Texts.of("That was a stick and the action was " + event.getInteractionType().getName() ));
            }
        }
    }
```

i encountered, that each time you right click (with the specified item), it puts out the line "That was a stick and the action was USE" twice. Left clicking is firing ATTACK just once, so thats fine.

greetings, bruuff

**Comment by Aaron1011** [comment] 2015-05-03 15:37
I believe @Zidane is (or was) working on fixing some problems with `PlayerInteractEvent`).

I suspect (but I'm not entirely sure) that this double firing is due to the fact the the client fires an `INTERACT_AT` for **every** right-clicked entity (as well as the normal `INTERACT`).

Are you only interacting with blocks, or with entities

**Comment by Zidane** [comment] 2015-05-03 16:36
@bruuff 

How were you testing this? Was it in SP within the IDE (so running Sponge on the client) or on a dedicated server. Can you also try your plugin on SpongeVanilla?

**Comment by Zidane** [comment] 2015-05-03 16:39
@Aaron1011 

Look at his event lol...its PlayerInteractBLOCKEvent

**Comment by ST-DDT** [comment] 2015-05-03 17:05
@bruuff You can also cause an exception in your event handler to obtain the stacktrace.
Then you can check whether the events are called from the same location.
If the source of the events differ there might be a mixin/implementation issue. (Please post the stacktraces in that case)

**Comment by Zidane** [comment] 2015-05-03 17:07
@ST-DDT 

Thread.dumpStack() ...... why cause an exception?

**Comment by Zidane** [comment] 2015-05-03 17:15
@Azatik

Are you using Sponge? Can you try your plugin on SpongeVanilla?

**Comment by Zidane** [comment] 2015-05-03 17:21
@bruuff @Azatik

You can also ping me in #spongedev to talk about this as well.

**Comment by Azatik** [comment] 2015-05-03 17:25
@Zidane use Sponge. Use SpongeVanilla can not.

Written at the end of the event: 
```
player.sendMessage();
```
So everything works fine.

**Comment by pqqqqq** [comment] 2015-05-03 17:27
Exact same issue with me. It seems to trigger another event for right clicks that has the block location at the origin (0, 0, 0) with no other noticeable changes from the first. The normal block location triggers first, then the one with the origin.

**Comment by bruuff** [comment] 2015-05-03 17:46
It was on a freshly installed forge-1.8-11.14.1.1371 server with only sponge-1.8-1371-2.1DEV-437 and my little plugin. Settings should all still be default.

I used the same fore installer for the client version and logged on locally.

ok here is the stacktrace of the two events:

http://pastebin.com/KQmMADbZ

I already structured it a little bit (shouldnt hurt)

Is sponge vanilla even usable as of now? Im not that experienced, so compiling it myself would probably bear the chance of other bugs that have nothing to do with this.

**Comment by Aaron1011** [comment] 2015-05-03 17:54
@Zidane: I know it's `PlayerInteractBlockEvent` - I wasn't certain if there was a problem with the correct event being fired.

**Comment by Zidane** [comment] 2015-05-03 17:56
@bruuff 

Could you upload a binary of your plugin (jar) and let me try it with SpongeVanilla?

**Comment by bruuff** [comment] 2015-05-03 17:57
@Zidane 
still with dumpstack in it or without?

**Comment by Azatik** [comment] 2015-05-04 18:07
I decided to test the events on the blocks.
CODE
```
    @Subscribe
    public void interact (PlayerInteractBlockEvent event){
        Player player = event.getPlayer();
        String blockType = event.getBlock().getType().getName();
        Text btype = Texts.of(blockType);
        player.sendMessage(btype);
    }
```

I clicked right-clicking on the grass.
![2015-05-04_23 03 54](https://cloud.githubusercontent.com/assets/10154956/7458992/3d73c454-f2b2-11e4-816c-85acb82cc33f.png)

**Comment by Zidane** [comment] 2015-05-04 21:20
@Azatik 

This is still with Forge, correct?

**Comment by Zidane** [comment] 2015-05-05 06:14
I've resolved this in SpongeVanilla.

Actually, funny enough, I have the inverse issue. If you right click an entity, it will fire normal PlayerInteract and PlayerInteractEntity events. I'll be fixing this in vanilla sometime (an easy vec check where I fire the normal one) but for this issue in Forge it will need us to override their logic and correct it (not hard) or fix it upstream (which may be more difficult)

**Comment by Azatik** [comment] 2015-05-05 06:41
@Zidane yes, this Forge.

**Comment by modwizcode** [comment] 2015-06-22 21:01
Could this be related to the left click for leaves? If you break leaves with shears it seems that it transverses the break with shears code twice.

**Comment by DarkArc** [comment] 2015-06-22 23:38
Not sure, this one fires an event for the actual block, and a log at 0, 0, 0.

**Comment by simon816** [comment] 2015-06-23 20:18
The problem is that Forge's `PlayerInteractEvent` is not exactly the same as Sponge's `PlayerInteractBlockEvent`. The forge event also fires when an item is right clicked in air.
It seems that the vanilla client sends two `C08PacketPlayerBlockPlacement` packets. One for the right click on block, the other for using an item. Because `PlayerInteractBlockEvent` should only be fired when a block is clicked, there needs to be a way to only fire the sponge event if that condition is met (without disrupting the firing of forge's event).
The following commit fixes the issue (AFAIK), but it's a bit of a hack about the event bus. If this is fine @SpongePowered/developers, this issue should be fixed. (Need someone to test it works too).
https://github.com/simon816/Sponge/commit/f996fe41

**Comment by DarkArc** [comment] 2015-06-23 22:00
I don't think that's the way to do it... If putting a fix in, it should be to override the bad logic about a log being interacted with, nothing more, nothing less.

**Comment by DarkArc** [comment] 2015-09-28 02:26
This issue is back.

**Comment by bloodmc** [comment] 2015-09-28 05:23
@DarkArc can you be more specific ? What build did it start to appear again?

**Comment by DarkArc** [comment] 2015-09-28 05:36
blood_: not sure the specific build haven't had the relevant code on since the "great event refactor" got it working again today and double messages again.

https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/registry/item/tool/Luminositor.java
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/registry/item/tool/SkullOfTheFallen.java

**Comment by Zidane** [comment] 2015-09-29 01:20
Fixed in the latest Sponge (once again)

**Closed by Zidane** 2015-09-29 01:20 UTC
Labels: forge-bug
