### ISSUE TITLE
Cancelled InventoryClickEvent resets slot in new inventory

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/Sponge#1229] opened 2017-03-02 20:51 UTC
1. Open a custom inventory.
![](http://puu.sh/urfDf/8d9dab8558.png)
2. Click on a slot in the inventory and cancel the resulting InventoryClickEvent.
3. Open another custom inventory in the InventoryClickEvent handler.
4. The item from the slot you clicked will be placed in the same slot in the newly opened inventory.
![](http://puu.sh/urg5J/305f392911.png)

Related to #1175 and #1045.
Verified on _SpongeVanilla 1.11.2-6.0.0-BETA-228_.

**Comment by JBYoshi** [comment] 2017-03-05 04:49
Duplicate of #1175.

**Comment by bloodmc** [comment] 2017-03-26 03:15
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/2406e2f0114c0955b0910dff7001456a9a1e1b52

**Closed as completed by bloodmc** 2017-03-26 03:15 UTC
Labels: system: event, system: inventory
