### ISSUE TITLE
LAST_DAMAGE and PARROT_VARIANT

### ISSUE THREAD

**Issue by seema84** [SpongePowered/Sponge#1561] opened 2017-10-04 16:44 UTC
Build: 1.12.2-345

[18:38:26 WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LAST_DAMAGE
[18:38:26 WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.PARROT_VARIANT

please complete this functions

**Comment by XakepSDK** [comment] 2017-10-04 18:26
Parrot variant
https://github.com/SpongePowered/SpongeCommon/pull/1495

**Comment by parlough** [comment] 2017-10-11 14:10
I'll finish the parrot PR soon. I can look into LAST_DAMAGE as well.

**Comment by parlough** [comment] 2017-12-07 21:08
Parrot variant is now implemented in the latest bleeding builds, not sure when I'll leave a chance to do last damage though as it is more involved I believe. I'll look into it though.

**Comment by gabizou** [comment] 2017-12-08 06:02
Why this wasn’t closed to direct to #8 is not something I’m going to spend time to. These warnings have been pretty standard to attach to said issue. Duplicate of #8

**Closed as completed by gabizou** 2017-12-08 06:02 UTC
Labels: status: accepted, system: data, version: 1.12 (u)
