### ISSUE TITLE
Canceling InteractItemEvent doesn't update clients inventory

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/Sponge#1432] opened 2017-07-11 09:07 UTC
- SpongeForge version: 1.10.2 - 2433
- Forge version: 2281:

If I cancel the `InteractItemEvent` when the player is trying to place a block it doesn't update the clients inventory which causes the block to go invisible in the inventory until the player rejoins or clicks on the invisible block.

Found this related old issue https://github.com/SpongePowered/SpongeCommon/issues/418

**Comment by JBYoshi** [comment] 2017-07-11 15:50
Duplicate of #1417.

**Comment by Sir-Will** [comment] 2017-07-11 16:38
Hm, what has this to do with that linked issue?

**Comment by JBYoshi** [comment] 2017-07-11 16:41
Never mind.

**Closed as completed** 2017-07-11 21:03 UTC
