### ISSUE TITLE
1.12.2(back far):  SpawnEntityEvent#getEntities().size()  is Zero on mob death (crossover with DropItem event?)

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1560] opened 2017-10-04 11:06 UTC
Have noticed in the past that sometimes event.getEntities().get(0) would return null.  
Logged SpawnEntityEvent where .size() is zero and did various server activities.

The times in which a zero-size list event is thrown is when the spawn event itself appears to be the DropItemEvent.Destruct event????? (as in, the class of spawnentityevent is that class...)  which occurs when mobs are killed which may drop items.

The odd man out of that is the death of bats, bats will catch fire and burn, and trigger the same spawn .dropped-item process, even though bats have nothing to drop, so its not the actual items that are being dropped by the mob that are throwing the event.

SpongeVanilla- 1.12.2-Beta-345, spongeforge-1.12.2-2486-7.0.0-BETA-2687
No mods/plugins except logging plugin:
![image](https://user-images.githubusercontent.com/3393225/31172536-ed41511c-a8d1-11e7-8bbc-bd3813510d42.png)

Annotated log entries below and on pastebin: https://pastebin.com/HutexPec

```
..Bat flys too close to lava and dies in a ball of flame in the lava
[06:26:10] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:30]: ========== ZERO ENTITY SPAWN SIZE ========
[06:26:10] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:31]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[06:26:10] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:32]: class net.minecraft.entity.passive.EntityBat
[06:26:10] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:33]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:owner"=EntityPlayerMP['BooMod'/31, l='world', x=436.89, y=32.00, z=-291.02]], Stack={EntityBat['Bat'/148, l='world', x=440.53, y=31.00, z=-290.77], BlockDamageSource{Name=lava, Type=fire, BlockSnapshot=SpongeBlockSnapshot{worldUniqueId=bb6df38c-0f84-406b-ac1d-7fddc95ec7e2, position=(440, 31, -291), blockState=minecraft:lava[level=0], extendedState=minecraft:lava[level=0]}, Location=Location{(440.0, 31.0, -291.0) in WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}}}, EntityBat['Bat'/148, l='world', x=440.53, y=31.00, z=-290.77]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:owner"=EntityPlayerMP['BooMod'/31, l='world', x=436.89, y=32.00, z=-291.02]], entities=[], entitySnapshots=null, source=EntityBat['Bat'/148, l='world', x=440.53, y=31.00, z=-290.77]}
[06:26:12] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:34]:  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
..bat flys to close to lava and catches fire, dies over stone.
[06:26:18] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:30]: ========== ZERO ENTITY SPAWN SIZE ========
[06:26:18] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:31]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[06:26:18] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:32]: class net.minecraft.entity.passive.EntityBat
[06:26:18] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:33]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:owner"=EntityPlayerMP['BooMod'/31, l='world', x=436.89, y=32.00, z=-291.02]], Stack={EntityBat['Bat'/160, l='world', x=438.94, y=32.07, z=-290.31], DamageSource{Name=onFire, Type=fire}, EntityBat['Bat'/160, l='world', x=438.94, y=32.07, z=-290.31]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}, "sponge:owner"=EntityPlayerMP['BooMod'/31, l='world', x=436.89, y=32.00, z=-291.02]], entities=[], entitySnapshots=null, source=EntityBat['Bat'/160, l='world', x=438.94, y=32.07, z=-290.31]}
[06:26:18] [Server thread/INFO] [STDOUT]: [QuickDirty:oddSpawn:34]:  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
 
.. killed zombie with sword
[05:40:05] [Server thread/INFO] [STDOUT]: ========== ZERO ENTITY SPAWN SIZE ========
[05:40:05] [Server thread/INFO] [STDOUT]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[05:40:05] [Server thread/INFO] [STDOUT]: class net.minecraft.entity.monster.EntityZombie
[05:40:05] [Server thread/INFO] [STDOUT]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntityZombie['Zombie'/3177, l='world', x=-178.47, y=22.00, z=-1265.04], EntityDamageSource{Name=player, Type=attack, Source=EntityPlayerMP['BooMod'/491, l='world', x=-180.30, y=22.00, z=-1262.16]}, EntityZombie['Zombie'/3177, l='world', x=-178.47, y=22.00, z=-1265.04], EntityPlayerMP['BooMod'/491, l='world', x=-180.30, y=22.00, z=-1262.16]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], entities=[], entitySnapshots=null, source=EntityZombie['Zombie'/3177, l='world', x=-178.47, y=22.00, z=-1265.04]}
[05:40:05] [Server thread/INFO] [STDOUT]:  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
.. Skeleton burned in sunlight
[05:48:39] [Server thread/INFO] [STDOUT]: ========== ZERO ENTITY SPAWN SIZE ========
[05:48:39] [Server thread/INFO] [STDOUT]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[05:48:39] [Server thread/INFO] [STDOUT]: class net.minecraft.entity.monster.EntitySkeleton
[05:48:39] [Server thread/INFO] [STDOUT]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntitySkeleton['Skeleton'/5049, l='world', x=751.21, y=69.00, z=85.56], DamageSource{Name=onFire, Type=fire}, EntitySkeleton['Skeleton'/5049, l='world', x=751.21, y=69.00, z=85.56]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], entities=[], entitySnapshots=null, source=EntitySkeleton['Skeleton'/5049, l='world', x=751.21, y=69.00, z=85.56]}
[05:48:39] [Server thread/INFO] [STDOUT]:  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
.. Chopped a large slimeblock into two smaller slimeblocks with sword
[05:50:02] [Server thread/INFO] [STDOUT]: ========== ZERO ENTITY SPAWN SIZE ========
[05:50:02] [Server thread/INFO] [STDOUT]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[05:50:02] [Server thread/INFO] [STDOUT]: class net.minecraft.entity.monster.EntitySlime
[05:50:02] [Server thread/INFO] [STDOUT]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntitySlime['Slime'/3389, l='world', x=-189.51, y=16.00, z=-1263.54], EntityDamageSource{Name=player, Type=attack, Source=EntityPlayerMP['BooMod'/491, l='world', x=-190.41, y=16.00, z=-1266.39]}, EntitySlime['Slime'/3389, l='world', x=-189.51, y=16.00, z=-1263.54], EntityPlayerMP['BooMod'/491, l='world', x=-190.41, y=16.00, z=-1266.39]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], entities=[], entitySnapshots=null, source=EntitySlime['Slime'/3389, l='world', x=-189.51, y=16.00, z=-1263.54]}
[05:50:02] [Server thread/INFO] [STDOUT]:  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
.. Small slimeblock jumps through fire and dies
=========================
[05:50:40] [Server thread/INFO] [STDOUT]: ========== ZERO ENTITY SPAWN SIZE ========
[05:50:40] [Server thread/INFO] [STDOUT]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[05:50:40] [Server thread/INFO] [STDOUT]: class net.minecraft.entity.monster.EntitySlime
[05:50:40] [Server thread/INFO] [STDOUT]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntitySlime['Slime'/4101, l='world', x=-186.12, y=17.12, z=-1264.77], BlockDamageSource{Name=inFire, Type=fire, BlockSnapshot=SpongeBlockSnapshot{worldUniqueId=bf6a8994-edbc-41bb-a432-6ad475e879e4, position=(-187, 17, -1266), blockState=minecraft:fire[age=0,east=false,north=false,south=false,up=false,west=false], extendedState=minecraft:fire[age=0,east=false,north=false,south=false,up=false,west=false]}, Location=Location{(-187.0, 17.0, -1266.0) in WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}}}, EntitySlime['Slime'/4101, l='world', x=-186.12, y=17.12, z=-1264.77]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], entities=[], entitySnapshots=null, source=EntitySlime['Slime'/4101, l='world', x=-186.12, y=17.12, z=-1264.77]}
 
.. Slash a creeper with a sword
[05:51:49] [Server thread/INFO] [STDOUT]: ========== ZERO ENTITY SPAWN SIZE ========
[05:51:49] [Server thread/INFO] [STDOUT]: class org.spongepowered.api.event.DropItemEvent$Destruct$Impl
[05:51:49] [Server thread/INFO] [STDOUT]: class net.minecraft.entity.monster.EntityCreeper
[05:51:49] [Server thread/INFO] [STDOUT]: Odd spawn process: Destruct{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntityCreeper['Creeper'/3652, l='world', x=-193.70, y=9.00, z=-1319.70], EntityDamageSource{Name=player, Type=attack, Source=EntityPlayerMP['BooMod'/491, l='world', x=-193.03, y=9.00, z=-1317.44]}, EntityCreeper['Creeper'/3652, l='world', x=-193.70, y=9.00, z=-1319.70], EntityPlayerMP['BooMod'/491, l='world', x=-193.03, y=9.00, z=-1317.44]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], entities=[], entitySnapshots=null, source=EntityCreeper['Creeper'/3652, l='world', x=-193.70, y=9.00, z=-1319.70]}
[05:51:49] [Server thread/INFO] [STDOUT]:  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ryantheleach** [comment] 2017-10-04 15:52
Even though this isn't probably intentional, I wonder how you would add drops to an entity that isn't going to drop any on death by default/chance if this was removed.

**Comment by theboomer** [comment] 2017-10-22 06:08
Its not an issue of where would you add drops to a dying mob, sure a zombie can drop something on death, i would assume that bones spawning are part of the skeleton death things there, that should be something spawned,except there appears to be nothing in the event that is the bones or armor or slimeball... but a bat dying spawns nothing.   So the primary question is why is 'nothing spawned' causing a spawn event, secondary question is 'is the wrong event being thrown/ is it thrown with incomplete information'
It would be like having the ChangeBlockEvent.Break fire when a cactus or reed grows and 'breaks' the air block above, yet, throw the event with zero transactions.

**Comment by Zidane** [comment] 2018-01-11 19:48
@theboomer 

Is this still an issue on latest SV? If so, run your test but give me a dumpStack when it happens and I'll fix. If not, let me know and I'll close. If I don't get an answer after a few days, I'll auto-close.

@ryantheleach 
There needs to be a different system in place to change who drops what. We don't want to fire empty events.

**Comment by ImMorpheus** [comment] 2018-01-17 16:31
Tested on 1.12 (bleeding branch)

Still happening for:
```
..bat flys to close to lava and catches fire, dies over stone.
.. killed zombie with sword
```

I'm not able to reproduce  `..Bat flys too close to lava and dies in a ball of flame in the lava` and I have NOT tested the others.

Code:
```
    @Listener
    public void onD(DropItemEvent.Destruct event) {
        if (event.getEntities().isEmpty()) {

            System.out.println("\n  ========== ZERO ENTITY SPAWN SIZE ======== \n" +
                    event.getCause() + "\n" +
                    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
            );
            Thread.dumpStack();
        }
    }
```


```
[INFO] [STDOUT]:   ========== ZERO ENTITY SPAWN SIZE ======== 
[INFO] [STDOUT]: Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={EntityZombie['Zombie'/1340, l='world', x=104.70, y=88.00, z=69.30], EntityDamageSource{Name=player, Type=attack, Source=EntityPlayerMP['jeb_'/187, l='world', x=102.01, y=88.00, z=71.05]}, EntityZombie['Zombie'/1340, l='world', x=104.70, y=88.00, z=69.30], EntityPlayerMP['jeb_'/187, l='world', x=102.01, y=88.00, z=71.05]}]
[INFO] [STDOUT]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Stacktrace (the zombie example):
```
[STDERR]: java.lang.Exception: Stack trace
        [ ERROR] [STDERR]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
        [ ERROR] [STDERR]: 	at org.spongepowered.test.TestTest.onD(TestTest.java:110)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.listener.DestructListener_TestTest_onD30.handle(Unknown Source)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:403)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:426)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.phase.entity.DeathPhase.unwind(DeathPhase.java:131)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.phase.entity.DeathPhase.unwind(DeathPhase.java:51)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:233)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399)
        [ ERROR] [STDERR]: 	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:3598)
        [ ERROR] [STDERR]: 	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:80)
        [ ERROR] [STDERR]: 	at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:251)
        [ ERROR] [STDERR]: 	at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:3760)
        [ ERROR] [STDERR]: 	at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1537)
        [ ERROR] [STDERR]: 	at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:2670)
        [ ERROR] [STDERR]: 	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:75)
        [ ERROR] [STDERR]: 	at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:13)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149)
        [ ERROR] [STDERR]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkh000(PacketThreadUtil.java:539)
        [ ERROR] [STDERR]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21)
        [ ERROR] [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
        [ ERROR] [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
        [ ERROR] [STDERR]: 	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        [ ERROR] [STDERR]: 	at java.util.concurrent.FutureTask.run(FutureTask.java)
        [ ERROR] [STDERR]: 	at net.minecraft.util.Util.runTask(Util.java:19)
        [ ERROR] [STDERR]: 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274)
        [ ERROR] [STDERR]: 	at net.minecraft.server.MinecraftServer.redirect$onRun$zim000(MinecraftServer.java:4563)
        [ ERROR] [STDERR]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1907)
        [ ERROR] [STDERR]: 	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:404)
        [ ERROR] [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:680)
        [ ERROR] [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
        [ ERROR] [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zidane** [comment] 2018-04-25 21:56
Closing this as it is by design that we always fire the drop (and Forge mods expect it to add drops to it).

If you feel the API should be adjusted, make an issue there.

**Closed as completed by Zidane** 2018-04-25 21:56 UTC
Labels: version: 1.12 (u)
