### ISSUE TITLE
Mixin redirect conflict on 1.16.5

### ISSUE THREAD

**Issue by FunkyNico** [SpongePowered/Sponge#3570] opened 2021-12-22 18:04 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.16.5-36.2.5-8.0.0-RC962-universal
- Java version: Azul Zulu JDK 11.52.13 (11.0.13) 64 Bits
- Operating System: Windows 10 Home 64 Bits

- Mods:
abnormals_core-1.16.5-3.3.0.jar
Abundance-1.16.5-1.0.5.jar
AI-Improvements-1.16.5-0.4.0.jar
alexsmobs-1.12.1.jar
appleskin-forge-mc1.16.x-2.2.0.jar
appliedenergistics2-8.4.4.jar
Aquaculture-1.16.5-2.1.21.jar
atmospheric-1.16.5-3.1.1.jar
AttributeFix-1.16.5-10.1.2.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.2.jar
bamboo_blocks-1.16.5-3.0.1.jar
Bayou-Blues-1.16.5-1.0.5.jar
BetterAdvancements-1.16.5-0.1.1.115.jar
Bookshelf-Forge-1.16.5-10.3.29.jar
Botania-1.16.5-420.1.jar
buzzier_bees-1.16.5-3.0.3.jar
byg-1.3.5.jar
carryon-1.16.5-1.15.5.15.jar
chiselsandbits-1.0.43.jar
chocolate-1.3.0-1.16.4.jar
citadel-1.8.1-1.16.5.jar
Clumps-6.0.0.27.jar
CodeChickenLib-1.16.5-4.0.5.438-universal.jar
cofh_core-1.16.5-1.4.0.6.jar
comforts-forge-1.16.5-4.0.1.3.jar
CommonCapabilities-1.16.5-2.8.0.jar
create-mc1.16.5_v0.3.2g.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.5-4.0.5.3.jar
CyclopsCore-1.16.5-1.12.1.jar
EnchantmentDescriptions-1.16.5-7.0.17.jar
endergetic-1.16.4-3.0.0.jar
environmental-1.16.5-1.1.1.jar
FarmersDelight-1.16.5-0.5.3.jar
fastbenchminusreplacement-1.4.jar
FastFurnace-1.16.5-4.5.0.jar
FastLeafDecay-v25.jar
ferritecore-2.1.0-forge.jar
flywheel-1.16-0.2.5.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
iceandfire-2.1.9-1.16.5.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.5-11.2.21.jar
jei-1.16.5-7.7.1.137.jar
jeiintegration_1.16.5-7.0.1.15.jar
journeymap-1.16.5-5.7.3.jar
JustEnoughResources-1.16.5-0.12.1.133.jar
lazydfu-0.1.3.jar
mclogs-forge-1.3.0-for-1.16.5.jar
mowziesmobs-1.5.19.jar
NetherPortalFix_1.16.3-7.2.1.jar
Patchouli-1.16.4-53.2.jar
Placebo-1.16.5-4.6.1.jar
polymorph-forge-1.16.5-0.33.jar
Quark-r2.4-321.jar
randompatches-2.4.4-forge.jar
selene-1.16.5-1.9.0.jar
starlight-forge-1.0.0-RC2-1.16.5.jar
StorageDrawers-1.16.3-8.3.0.jar
supplementaries-1.16.5-0.17.12b.jar
swingthroughgrass-1.16.4-1.5.3.jar
thermal_cultivation-1.16.5-1.4.1.3.jar
thermal_expansion-1.16.5-1.4.1.3.jar
thermal_foundation-1.16.5-1.4.1.7.jar
thermal_innovation-1.16.5-1.4.1.3.jar
torchmaster-2.3.8.jar
twilightforest-1.16.5-4.0.546-universal.jar
upgrade_aquatic-1.16.5-3.1.2.jar
WAWLA-1.16.5-8.0.1.jar

**Issue Description**

When you start the server stops itself without crashing and then it closes.

https://mclo.gs/UUeSLUR#L1683

**Comment by Zidane** [comment] 2022-01-03 18:35
Duplicate of https://github.com/SpongePowered/Sponge/issues/3514

**Closed as completed by Zidane** 2022-01-03 18:35 UTC
Labels: version: 1.16 (u), platform: forge
