### ISSUE TITLE
Server Thread Warning Skipping Keys

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1459] opened 2017-07-22 12:18 UTC
**SpongeForge Version:** spongeforge-1.10.2-2281-5.2.0-BETA-2464

Hello, on every startup, I receive several of these warning messages:
```
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_SPINNER
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_CHECKBOX
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_ICON
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_BUTTON
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_COLUMN
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_WEST
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_SOUTH
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_NORTH
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_EAST
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENTS
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WILL_SHATTER
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STATISTICS
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_SPAWN_RANGE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_SPAWN_COUNT
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_REQUIRED_PLAYER_RANGE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_NEXT_ENTITY_TO_SPAWN
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_MAXIMUM_NEARBY_ENTITIES
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_MAXIMUM_DELAY
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_ENTITIES
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SCALE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.PASSENGERS
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LEASH_HOLDER
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LAST_DAMAGE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LAST_ATTACKER
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.IS_SLEEPING
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.HELD_EXPERIENCE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.HEIGHT
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.FLUID_LEVEL
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.FILLED
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.DOMINANT_HAND
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.DAMAGE_ENTITY_MAP
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.BASE_SIZE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.ATTACK_DAMAGE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.AGE
22.07 08:08:55 [Server] INFO [08:08:55] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.ACHIEVEMENTS
```

**Comment by kashike** [comment] 2017-07-22 13:25
Duplicate of #1066.

**Closed as completed** 2017-07-22 13:26 UTC
Labels: resolution: duplicate, version: 1.10 (u)

**Comment by SjsolisZXA** [comment] 2017-07-22 13:27
This issue hasn't been fixed, though.

**Comment by Zidane** [comment] 2017-07-22 14:21
@SjsolisZXA 

1. This is a duplicate, no need to have multiple issues open
2. Its a warning and is completely harmless. It is not affecting your server in anyway.
