### ISSUE TITLE
ExperienceOrb from mob_spawners problem

### ISSUE THREAD

**Issue by TheoKah** [SpongePowered/Sponge#1001] opened 2016-10-27 03:51 UTC
When breaking a spawner, we get the SpawnEntityEvent event of the EntityXPOrb BEFORE we get the ChangeBlockEvent.Break event of the mob_spawner, meaning if we cancel the break, experience is still spawned.

Moreover, the source cause of the ExperienceOrbs event in that case is considered a "Placement" from the EntityPlayerMP that breaked the spawner instead of the spawner itself, making it hard to cancel the drop manually.

would it be possible for your to make sure no EntityXPOrb spawns if the break event is cancelled?
also, could you change the cause of the EntityXPOrb spawn to be the spawner and not the player?

thanks :)

**Comment by Zidane** [comment] 2016-10-28 13:47
@gabizou 

Similar issue to blood's GP issue of not having entities spawned from block breaks not tied together. I know you have a fix for this on the way.

**Comment by gabizou** [comment] 2016-10-29 01:05
Just so everyone is aware, I'll be gone the next three days after which I'll be able to continue working on a fix for this.

**Comment by malte-laukoetter** [comment] 2017-03-10 16:42
any updates on this?

**Comment by ryantheleach** [comment] 2017-11-24 01:59
I need someone to volunteer to test this in game under 1.12

**Comment by RedNesto** [comment] 2017-11-24 08:58
This is no longer an issue: The ChangeBlockEvent.Break is fired before the SpawnEntityEvent, and cancelling the ChangeBlockEvent.Break does not drop the experience orbs.

However, the cause is still the Player and not the Spawner.

Tested with:
- forge-1.12.2-14.23.0.2529-universal
- spongeforge-1.12.2-2529-7.0.0-BETA-2744
- [this test plugin](https://gist.github.com/RedNesto/940915d3586831a06a410b624cd59caa)

**Comment by ryantheleach** [comment] 2017-11-24 14:17
Thanks @RedNesto appreciated!

**Comment by gabizou** [comment] 2018-01-09 23:03
@Zidane @kashike @RedNesto @ryantheleach So, some thoughts, the problem currently is that the phase contexts for this sort of thing only tracks bulk spawns and blocks. For us to sanely throw a SpawnEntityEvent with the proper cause *including* the appropriate block snapshot that caused the entities to spawn, we'd have to specifically use multi maps for every block event and then process the entity spawns on block application (and eliminate them when they're cancelled). 

Currently, the point when we spawn the entities for a block broken, such as a mob spawner, the blocks changed are invalidated (having already been processed), and still have the possibility of having multiple blocks.

As a short workaround, do we want to use the *first* block available in the snapshot for the cause? even though in some certain cases, like a sign post causing multiple other blocks to break (chains) to be caused by the single sign post?

**Comment by gabizou** [comment] 2018-01-09 23:51
Otherwise, for the mean time, there is a direct cause associated with the first block snapshot of block changes, if available.

**Closed as completed by gabizou** 2018-01-09 23:51 UTC
Labels: type: bug, system: phase tracker, version: 1.12 (u)

**Comment by ryantheleach** [comment] 2018-01-10 00:40
My suspicion is this will cause some really un-obvious bugs with things that break multiple blocks at once e.g where 3x3 mining tools, on the edge of claims, consistently bypass plugins.

I'm going to create a new ticket for correcting this behavior in the future, since you mentioned it's a short term work-around or else it's going to be missed.
