### ISSUE TITLE
Performance drop after upgrading from SF 3029 to 3064

### ISSUE THREAD

**Issue by Lemmmy** [SpongePowered/Sponge#1896] opened 2018-04-30 18:25 UTC
**I am currently running**
- SpongeForge version: 3064
- Java version: 1.8.0_151
- Operating System: Ubuntu 16.04.4 LTS

- Plugins/Mods: Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActiveTime, AutoSpy, Buycraft, Dynmap, GriefPrevention, LuckPerms, Nucleus, SpongePrometheusExporter, SpongeSlack, TabManager, kristpay
Mods (29): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AutoRegLib, Baubles, BiblioCraft, CC Prometheus, CC: Tweaked, Chisel, Computronics, Dynmap, DynmapBlockScan, Iron Chest, Just Enough Items, MinimalPeripherals, OpenComputers, OpenComputers (Core), Plethora, Plethora Core, Quark, Sampling Performance Profiler, The Weirding Gadget, TickProfiler, WorldEdit, asielib, mercurius_updater

**Issue Description**

Last night we upgraded our server from SpongeForge 3029 to 3064, and have noticed a stable decline in TPS since. This 24-hour graph shows the TPS before upgrading, and since upgrading:

![](https://you.wouldnot.download/a-textbook.png)

Here is a snippet of a 1-minute Sampler timing: ![](https://you.wouldnot.download/a-hemp.png)
And the full NPS: https://crashes.switchcraft.pw/2018-04-30-19-13.nps

Additionally, a timings report: https://timings.aikar.co/?id=42dd995e9fa042ce9db99a8f1a35e9a6

Phit suggests this may be related to #1706.

**Comment by ProsperCraft** [comment] 2018-04-30 20:40
If it helps, here is some more data using 3064.

https://timings.aikar.co/?id=934635a70aa549adab990405becbd642

Warm Roast-
[sponge3064.zip](https://github.com/SpongePowered/SpongeCommon/files/1962058/sponge3064.zip)

Sampler-
[samplersponge3064.zip](https://github.com/SpongePowered/SpongeCommon/files/1962072/samplersponge3064.zip)

Tickprofiler- 
https://gist.github.com/ProsperCraft/dd334abea4d170a861387460af3a360a

LagGoggles-
![2018-04-30_14 39 10](https://user-images.githubusercontent.com/4427684/39449086-575e0a94-4c84-11e8-9a67-242e1135cca8.png)

**Comment by gabizou** [comment] 2018-04-30 21:27
Do you have stacktraces enabled for phase states in your config per chance?

**Comment by Lemmmy** [comment] 2018-04-30 21:33
`generate-stacktrace-per-phase=false` this? It's false in our config

**Comment by ProsperCraft** [comment] 2018-04-30 22:47
Timings includes sponge configs right? @gabizou

**Comment by ProsperCraft** [comment] 2018-04-30 22:48
generate-stacktrace-per-phase=false

In our config.

**Comment by ProsperCraft** [comment] 2018-04-30 23:02
Here are timings from 3059  https://timings.aikar.co/?id=10692105563244718a7f3f8c3836daf3

Sampler nps file from 3059-
[sponge3059.zip](https://github.com/SpongePowered/SpongeCommon/files/1962507/sponge3059.zip)

**Comment by bloodmc** [comment] 2018-05-01 02:37
@phit is correct. The issue is due to commit https://github.com/SpongePowered/SpongeCommon/commit/ba151bbf8b3b83c3a0c00aea7cae4a41d86ca165

This needs to be reverted.

**Comment by Lemmmy** [comment] 2018-05-03 21:49
Hey there! Is there any progress on this issue?

**Comment by liach** [comment] 2018-05-11 02:34
why did he use array maps?

**Comment by SquidDev** [comment] 2018-05-11 08:13
Would it be possible to switch to `Int2ObjectOpenHashMap`s? They should have substantially better performance characteristics than the ArrayMap, whilst still avoiding the unboxing overhead.

**Comment by bloodmc** [comment] 2018-05-12 16:38
@Lemmmy @ProsperCraft Please test latest SF and report back if problem is resolved.

**Comment by ProsperCraft** [comment] 2018-05-12 17:58
Looks like you nailed it!
![e95109fc059d4dadae4981702834ebc9](https://user-images.githubusercontent.com/4427684/39960209-d3532e30-55db-11e8-8111-e88070e24890.png)

will continue to monitor.

**Comment by phit** [comment] 2018-05-12 18:03
closing for now then, if it becomes an issue again reply and I'll reopen!

**Comment by ProsperCraft** [comment] 2018-05-12 19:02
Sorry, looks like I spoke too soon.

![8dee3040666fb74412e331fc6c22c659](https://user-images.githubusercontent.com/4427684/39960610-17491d82-55e3-11e8-9640-11d511e7042c.png)

https://timings.aikar.co/?id=779c21a25943480894bc4481c38e890b

Here is a sampler profile
[sponge.zip](https://github.com/SpongePowered/SpongeCommon/files/1997842/sponge.zip)

Here is a warmroast-
[sponge-warmroast.zip](https://github.com/SpongePowered/SpongeCommon/files/1997847/sponge-warmroast.zip)

**Comment by bloodmc** [comment] 2018-05-13 02:03
@ProsperCraft Please test the following 2 jars

https://www.dropbox.com/s/npevwshdg2xkfxb/spongeforge-1.12.2-2655-7.1.0-BETA-TEST1.jar
https://www.dropbox.com/s/64kxyntig2v0yp3/spongeforge-1.12.2-2655-7.1.0-BETA-TEST2.jar

Let me know if any perform better. If not then the issue has nothing to do with these changes.

**Comment by XakepSDK** [comment] 2018-05-13 11:46
Just make samples with 3029 to see diff.

**Comment by ProsperCraft** [comment] 2018-05-14 15:18
Test1- 
10 players on
![test1](https://user-images.githubusercontent.com/4427684/40006169-ecabfb56-5756-11e8-9a41-51b4a525cf4c.png)

Timings- https://timings.aikar.co/?id=0a194a4198074332af6fe12c436997bb
Sampler- 
[test1.zip](https://github.com/SpongePowered/SpongeCommon/files/2001416/test1.zip)

**Closed as completed** 2018-06-13 13:53 UTC
Labels: version: 1.12 (u), type: performance
