### ISSUE TITLE
CommandEvent setResult

### ISSUE THREAD

**Issue by UnwrittenFun** [SpongePowered/Sponge#265] opened 2015-05-06 23:26 UTC
Registering for the CommandEvent and calling setResult on the event throws the error:

```
java.lang.AbstractMethodError: org.spongepowered.api.event.impl.CommandEvent$Impl.setResult(Lorg/spongepowered/api/util/command/CommandResult;)V
	at unwrittenfun.sponge.lunge.LungePlugin.onCommand(LungePlugin.java:38) ~[LungePlugin.class:?]
	at org.spongepowered.mod.event.handler.CommandEventHandler_LungePlugin_onCommand1.handle(Unknown Source) ~[?:?]
	at org.spongepowered.mod.event.SpongeEventBus.callListener(SpongeEventBus.java:234) [SpongeEventBus.class:1.8-1371-2.1DEV-437+unknown-b437.git-unknown]
	at org.spongepowered.mod.event.SpongeEventBus.post(SpongeEventBus.java:280) [SpongeEventBus.class:1.8-1371-2.1DEV-437+unknown-b437.git-unknown]
	at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:224) [SimpleCommandService.class:1.8-1371-2.1DEV-437+unknown-b437.git-unknown]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:85) [cl.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400) [po.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:365) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
```

Code being used:
```java
  @Subscribe
  public void onCommand(CommandEvent event) {
    if (event.getCommand().equalsIgnoreCase("test")) event.setResult(CommandResult.success());
  }
```

Hope I'm not just derping here..

_Note:_
I realise I can register a command but I have reasons in needing register the event. Plus it's an issue regardless

**Comment by ZephireNZ** [comment] 2015-05-06 23:29
If you see AbstractMethodError, that means that the API you tried to use is not yet implemented. Sponge is still very much a work in progress - the implementation is still lacking quite a few major API parts.

For now this makes it difficult to test some areas of plugins, but there's not much you can do unless you want to help contribute to Sponge.

**Comment by unwrittenfun** [comment] 2015-05-06 23:31
Oh right, I didn't realise it was _that_ unfinished, my bad :P

**Comment by Zidane** [comment] 2015-05-06 23:35
Why would you close this? Its an issue that should get fixed -_-.

**Comment by Aaron1011** [comment] 2015-05-06 23:36
This is an actual bug - all of the methods in the generated event classes should work.

**Comment by kenzierocks** [comment] 2015-05-07 00:24
Found the cause, the mutator detection regex is incorrect in `AccessorFirstStrategy`. Want me to PR?

**Comment by kenzierocks** [comment] 2015-05-07 00:35
Ah, it's a mismatch in the types between what's set and what's returned by get. The `get` returns `Optional<CommandResult>` but the `set` takes `@Nullable CommandResult`. We need support for this `Optional`/`@Nullable` pairing in the event factory.

**Comment by Aaron1011** [comment] 2015-05-07 00:36
@kenzierocks: I'm currently working on this - my changes are also including test s to make sure we'll catch this kind of problem.

**Comment by Zidane** [comment] 2015-05-28 14:36
Fixed by @Aaron1011 in the API.

**Closed by Zidane** 2015-05-28 14:36 UTC
Labels: accepted, bug
