### ISSUE TITLE
Asynchronous Thread Access to PhaseTracker

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#3542] opened 2021-09-18 17:50 UTC
**I am currently running**

- SpongeVanilla version: 3535a838 and later

**Issue Description**

An exception is thrown when scheduling tasks in the asynchronous scheduler. 

Test code:
```java
@Listener
public void onStartedServer(StartedEngineEvent<Server> event) {
    ExecutorService executorService = Sponge.game().asyncScheduler().createExecutor(plugin);
    executorService.submit(() -> {});
}
```
Exception:

```
Exception in thread "Sponge Async Scheduler Thread" java.lang.IllegalStateException: Asynchronous Thread Access to PhaseTracker: PhaseTracker[sidedThread=java.lang.ref.WeakReference@520cb52e, hasRun=false]
        at org.spongepowered.common.event.tracking.PooledPhaseState.createPhaseContext(PooledPhaseState.java:42)
        at org.spongepowered.common.scheduler.SpongeScheduler.executeTaskRunnable(SpongeScheduler.java:300)
        at org.spongepowered.common.scheduler.SpongeScheduler.startTask(SpongeScheduler.java:259)
        at org.spongepowered.common.scheduler.SpongeScheduler.processTask(SpongeScheduler.java:245)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
        at org.spongepowered.common.scheduler.SpongeScheduler.runTick(SpongeScheduler.java:176)
        at org.spongepowered.common.scheduler.AsyncScheduler.mainLoop(AsyncScheduler.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by dualspiral** [comment] 2021-09-19 08:37
Duplicate of https://github.com/SpongePowered/Sponge/issues/3537

**Closed as completed by dualspiral** 2021-09-19 08:37 UTC
Labels: resolution: duplicate
