### ISSUE TITLE
Cannot set tile entity properties of BlockSnapshot 

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1962] opened 2018-06-27 04:03 UTC
Test code (positional data needed re: #1960):
```java
// Player p;
String command = "give pie_flavor minecraft:diamond 1";
BlockState state = BlockState.builder().blockType(BlockTypes.COMMAND_BLOCK).build();
BlockSnapshot snapshot = BlockSnapshot.builder()
        .blockState(state)
        .world(p.getWorld().getProperties())
        .position(p.getLocation().getPosition())
        .add(Keys.COMMAND, command)
        .build();
```
Resulting snapshot data:
```json
{
  "ContentVersion": 1,
  "WorldUuid": "d2e9aee8-534d-4a1d-8c40-fd1b33b94713",
  "Position": {
    "X": -72,
    "Y": 76,
    "Z": 194
  },
  "BlockState": {
    "ContentVersion": 2,
    "BlockState": "minecraft:command_block[conditional=false,facing=north]"
  }
}
```

**Comment by gabizou** [comment] 2018-06-28 03:51
It should be noted that `TileEntityArchetype `s should be used on `ItemStack`s instead of `BlockSnapshot`s. It originally was intended that snapshots were the only things we "knew" about to use for representing a possible `TileEntity`. It should be possible to fix this in the implementation to support both, while adding a new method to include a `TileEntityArchetype`, while still supporting `BlockSnapshot`s.

**Comment by ImMorpheus** [comment] 2018-10-26 17:58
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/461

**Closed as completed by ImMorpheus** 2018-10-26 17:58 UTC
Labels: resolution: duplicate
