### ISSUE TITLE
Cancelling DropItemEvent.Pre destroys the ItemStack in some cases

### ISSUE THREAD

**Issue by eternel22** [SpongePowered/Sponge#1178] opened 2017-02-01 18:42 UTC
When a player drops an item by pressing _**"ctrl+q"**_ and the event called is cancelled, the whole stack **disappears**.

![bug](https://cloud.githubusercontent.com/assets/23460744/22520894/590dad78-e8b6-11e6-84b1-3ad113f3f2a1.gif)

**Comment by bloodmc** [comment] 2018-01-27 21:14
I can't reproduce this issue so closing as it was probably fixed awhile back.

**Closed as completed by bloodmc** 2018-01-27 21:14 UTC
Labels: type: bug, status: needs testing
