### ISSUE TITLE
/sponge not erroring as expected when no permission

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/Sponge#2507] opened 2020-02-18 04:08 UTC
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: https://github.com/SpongePowered/SpongeVanilla/commit/e80a16e4ad22d2eca549900e959bf8e7d70269f5
- Java version: 1.8.0_241
- Operating System: Windows 10

- Plugins/Mods: Nucleus, Luckperms

**Issue Description**
When running `/sponge plugins`, or any sponge command without permission it errors with 
![image](https://user-images.githubusercontent.com/9203727/74703107-c1d1fa80-51d1-11ea-9823-7adc264e23a3.png)
instead of a "No permission to use this command" message.

**Comment by gabizou** [comment] 2020-02-21 05:29
Is this reproducible on SpongeForge?

**Comment by dualspiral** [comment] 2020-02-21 08:20
It is. It's basically because the subcommand fails and the parent command then tries to parse the string instead. It's a simple fix.

**Comment by dualspiral** [comment] 2021-07-02 16:24
I'm going to close this - it's not really going to get looked at now, especially as 1.16.5+ is really our main focus now.

**Closed as completed by dualspiral** 2021-07-02 16:24 UTC
