### ISSUE TITLE
MoveEntityEvent using old Player momentarily during respawn

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/Sponge#2202] opened 2019-03-01 03:45 UTC
**I am currently running**

- SpongeForge version:  1.12.2-2768-7.1.5-RC3512
- SpongeVanilla version:  n/a
- Java version:  8
- Operating System: windows and ubuntu

- Plugins/Mods:
BorderProtector 

**Issue Description**
So, let me get start it by this I use Nucleus in a way to obtain if your outside the world border on here for *testing purposes only* https://github.com/NucleusPowered/Nucleus/blob/31055391de340cfb2a93d5a494c804db0d7115bc/src/main/java/io/github/nucleuspowered/nucleus/Util.java#L386-L408 and took out on line 407 1 which will check if your outside the border of course i had use what was in mine plugin as well.https://github.com/runescapejon/BorderProtector/blob/master/src/main/java/me/runescapejon/borderprotector/BorderProtector.java#L91
The issue here is that both `boolean return true` if you fall in the void in another dimensions which should give `false` both overworld and another dimensions for example the end world both has a world border of diameter 2000 *(testing only)*. You teleport to the end world and fall in void boolean that made for detecting if your outside the border will give a false positive. Then i began to think of few numbers of way to recreating a method if your outside the border but all with the same result. Furthermore I went to see if it's sponge issue so i test this boolean with Bukkit and it seem bukkit give the right result if you fall in the void in end world it will `return false` the right way. If you need anymore information please feel free to ask and thank

**Comment by phit** [comment] 2019-05-16 07:43
would be nice to know what is returning the wrong value here, none of those methods care about Y level of the player, so what's going on?

**Comment by runescapejon** [comment] 2019-05-16 08:43
Putting a Y level is redundant to detecting world border. So, Why put it to player?

**Comment by phit** [comment] 2019-05-16 08:46
that's not what I asked, I'm confused how falling into the void would cause this, as the players Y level isn't used at all, so I'm asking what returns the wrong value to lead to the false positive

**Comment by runescapejon** [comment] 2019-05-16 08:51
Oh my apologies, my mistake didn't understood what you was trying to asked. Although i am confuse. Also at the time of writing this i was certain that i was a sponge bug due to how it perform and there was no issue with how i wrote it. I couldn't find what exactly returns wrong value that lead to false positive that why i assume it was sponge bug.

**Comment by dualspiral** [comment] 2019-05-16 08:55
When you get your false positive, what is the player location according to the code? The only way I see this being a Sponge issue is if the player location is incorrect. Otherwise there is some weird logic flaw going on in my own code.

Attach a debugger and have a look at that, and make sure the correct border centre and diameter is being returned. If both of these are correct, then it's not a Sponge issue.

**Comment by dualspiral** [comment] 2019-05-16 09:32
Also

https://github.com/runescapejon/BorderProtector/blob/master/src/main/java/me/runescapejon/borderprotector/BorderProtector.java#L99

That line is non-sensical. When would `-x` or `-z` be greater than the always positive radius (which you've labeled diameter)? So, if you're outside the border in the -/- quadrant, or out of the the border in a specific direction in the +/- or -/+ quadrants, you're going to get a false positive.

Correct your code, and if there is still a deficiency,  please provide a minimal test case that we can use to replicate and fix the issue with.

**Comment by runescapejon** [comment] 2019-05-16 09:51
Ahh i found the issue on the worldborder issue i was having on the github issue, i look into today, it seem that it's possible that it's not a sponge bug. I do admit i should have look into it deeper that a dumb on my part  Well it seem on obtaining a player locations i correct. However what value gave the false positive was how i obtain the Center.


This is what i found during the debugging
`
(0.5, 0.0, 0.5) 25.0
(31.5, 0.0, 129.5) true
`

that should be false but it's mix numbers  so it's true. 
It seem the issue is this 

`int centerZ = (int) player.getWorld().getWorldBorder().getCenter().getZ();`
`int centerX = (int) player.getWorld().getWorldBorder().getCenter().getX();`

obtaining a player CenterX/Z during the teleportation between dimensions causing these mix numbers. As of this moment i am still doing more debugging and testing. Also i can see how it's deficiency at the time it was the only thing i can think of to make it in a proper way. I'll try to make it more sufficient in more detail.

**Comment by dualspiral** [comment] 2019-05-16 10:10
> This is what i found during the debugging...

Those numbers mean nothing on their own. Which one is the player location, and which one is the border centre? Please be explicit with what you tell us.

> mix numbers

Do you mean that the player position is in one world, but the border centre is from another? 

If the first set of numbers is from your player position, then you end up with a negative x and negative z and your code is absolutely going to send a false positive - but that's a bug on _your_ end.

If you still think there is an issue, first [correct your problem in your code here](https://github.com/runescapejon/BorderProtector/blob/master/src/main/java/me/runescapejon/borderprotector/BorderProtector.java#L99) to read:

```java
return (Math.abs(x) > diameter) || Math.abs(z) > diameter);
```

because your radius is always positive. Then, if it still doesn't work, from code (so, not where you think you are, where Sponge says you are):

* The player position at the time of the check
* The player world at the time of the check

Ensure that you are getting the world border from the player world, and include that too. Then tell me which world you _think_ you should be in, if different. If it works, then please close the issue.

**Comment by runescapejon** [comment] 2019-05-16 13:48
Sorry that i didn't go into specific, it was late around 5-6 am for me at that time. Anyway let me explain my reply from earlier so we both can have a better understanding from each other. The [boolean that i had recreated it,](https://github.com/runescapejon/BorderProtector/blob/master/src/main/java/me/runescapejon/borderprotector/BorderProtector.java#L91) it was checking for the center of the border twice, as i began to debug it with `	System.out.println(player.getWorld().getWorldBorder().getCenter());` and put it within the `private boolean check(Player player)` i had found that using this, it was calling twice this is an issue and it shouldn't be doing that. It should be calling once. When performing the debug with `	System.out.println(player.getWorld().getWorldBorder().getCenter());` here are the result of the testing at the time. https://pastebin.com/raw/f4fBd2VQ Here it indicate the center of the world border that a player is currently in. As it you see within the pastebin there are false but because the player is still in the the end dimension `(0.5, 0.0, 0.5)`  this here it's the  world border center of the end dimension using the debug, another indication is also shown here `(31.5, 0.0, 129.5)` which this is world border center of the over-world. So, when falling into the void of the end dimension and it will produce with `(0.5, 0.0, 0.5)` then once your teleport it to the over-world it also produce with `(31.5, 0.0, 129.5)` then true. This is an issue because there are two centers from each dimension that are being called twice for no reason. I hope this is a better explanation, if there's something not quite clear please let me know. Thank you

**Comment by dualspiral** [comment] 2019-05-16 14:11
No, it's not clear, specifically this:

>  So, when falling into the void of the end dimension and it will produce with (0.5, 0.0, 0.5) then once your teleport it to the over-world it also produce with (31.5, 0.0, 129.5) then true. This is an issue because there are two centers from each dimension that are being called twice for no reason.

What do you mean? Is the real problem here that the player location object is reporting the wrong world? What do you mean two centres from each dimension? What is being called twice? Your pastebin isn't clear either.

Rather than try to explain it again, please can you:

* Write a **minimal** test code that we (and you) can run on a server that shows the problem
* Steps for reproduction in a bullet point form
* What you expect to happen
* What actually happens (labelling any results as necessary)

**Comment by runescapejon** [comment] 2019-05-16 21:52
Sorry it seem what i was trying to explain earlier it's redundant. I had found the real culprit of the issue.

Here what i wrote to test:
https://pastebin.com/RXSx4kZM

Step on how to reproduce
1) make a end portal 
2) then go into it 
3) fall in the void and die
4) then click respawn once you respawn you'll see the bug

What i expect to happen during this is `getX` will not be accurate when you attempt to respawn
Here is a GIF on a demonstration https://gyazo.com/a76a9df98a847065548f0bbe94c25193
as you see there a `-2.5`  when there shouldn't be there when 28.0 is more accurate. Same thing happen to `getZ` these methods are not quite accurate when you respawn. 

EDIT: Also you can die in the overworld void as it's give inaccurate X/Z

**Comment by dualspiral** [comment] 2019-05-17 10:37
Okay - now I see what is going on - the `MoveEntityEvent` is capturing the movement of the dead `Player` object as a respawn is occuring for a moment or two before the newly recreated respawned player appears.

I suppose you could try checking the health of the player or cache the last known block of a player and only act if they change block/world as a workaround. Remember, the `MoveEntityEvent` can fire many, _many_ times in a tick so it might be in your interest to cache positions and only execute the logic when a block boundary is crossed/world is changed.

**Closed as completed** 2019-05-30 15:54 UTC
Labels: version: 1.12 (u), status: more information needed
