### ISSUE TITLE
[1.11.2] Holograms fail to register a DataManipulatorBuilder

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/Sponge#1450] opened 2017-07-18 08:28 UTC
**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2468
- Forge: forge-1.11.2-13.20.1.2414-universal
- SpongeVanilla version: N/A
- Java version: 1.8.0_131
- Operating System:
 - [x] Windows Server 2012 R2

- Plugins/Mods: 
Holograms-2.2

some were, some time ago RandomByte asked me to make this issue here, but forgot where that was.

**What is the current result?**
[![Screenshot from Gyazo](https://gyazo.com/322d1b1f8b9f8f96c7e43126d4c6b650/raw)](https://gyazo.com/322d1b1f8b9f8f96c7e43126d4c6b650)

-  Seen during startup:
https://gist.github.com/FiveEYZ/cf07f3d0b0f86d8690eeeec031faabbf

-  Seen when doing a command from Holograms:
https://gist.github.com/FiveEYZ/5f47099d6b9184d57f75b496ce063257

-  full log:
https://gist.github.com/FiveEYZ/6eeb047d1cdc30f16f610d8167d932d6

**Comment by Zidane** [comment] 2017-07-18 13:44
The log is pretty clear on this: He needs to update for the latest changes in API 6. Not a Sponge issue.

**Comment by randombyte-developer** [comment] 2017-07-18 17:40
This is a Sponge bug, confirmed by @gabizou #1396

**Comment by Zidane** [comment] 2017-07-18 17:49
I stand corrected.

@gabizou where is the fix for this as you mentioned elsewhere you would do?

**Comment by TehFoxFire** [comment] 2017-07-21 16:18
Im having the same issue on spongeforge-1.11.2-2393-6.1.0-BETA-2468 with holograms 2.2.

**Comment by randombyte-developer** [comment] 2017-12-23 19:20
So this won't ever be fixed? I heard support for 1.11.2 will be dropped on 31st December.

**Comment by gabizou** [comment] 2017-12-23 19:52
I tried poking the issue but for some reason, even though fix is already in place, it doesn't seem to work as intended in this circumstance. But yes, eventually development will cease for 1.11.2. If anyone is able to fix the issue itself, by all means, but I'm not likely to have the time to resolve this one by the due date for API 7's release.

**Comment by ImMorpheus** [comment] 2018-08-29 13:04
Closing this issue, as of Jan 1st 2018 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue on Minecraft 1.12.2 and this issue was wrongly closed, please open a new issue with updated information.

Note: the legacy data registration was removed with https://github.com/SpongePowered/SpongeCommon/commit/5409aef39d4b6c1ee2db8484d9d92a0e0acfc69a . I think this is not even reproducible

**Closed as completed by ImMorpheus** 2018-08-29 13:04 UTC
Labels: system: data, version: 1.11 (u)
