### ISSUE TITLE
EventContextKeys.USED_ITEM is no longer present in ChangeBlockEvent.Place Event Context

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#2182] opened 2019-02-03 21:21 UTC
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5-RC3539
- SpongeVanilla version: 1.12.2-7.1.5 (Recommended)
- Java version: 1.8.0_181
- Operating System: Win 10 / Linux

**Issue Description**
EventContextKeys.USED_ITEM is no longer present in ChangeBlockEvent.Place's event context.

`event.getContext().get(EventContextKeys.USED_ITEM).isPresent()` returns false.

```java
    @Listener(order = Order.PRE)
    public void blockPlaced(ChangeBlockEvent.Place event, @Root Player player){
        System.out.println(event.getContext().get(EventContextKeys.USED_ITEM).isPresent());
    }
```

**Comment by ImMorpheus** [comment] 2019-03-02 11:00
I'm not able to reproduce this on stable-7 updated to https://github.com/SpongePowered/SpongeCommon/commit/7de73b25245c0f7d8a5e24091095ab758874ebc0

This was probably fixed with other issues when working on EventContextKeys

**Closed as completed by ImMorpheus** 2019-03-02 11:00 UTC
Labels: version: 1.12 (u)
