### ISSUE TITLE
commands showing up in /help for players without permission to use

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/Sponge#2372] opened 2019-09-08 21:34 UTC
**I am currently running**

- SpongeForge version: 1.12.2 2838 7.1.7 RC 3910
- Java version: 1.8.0_221-b11
- Operating System: Windows 10

Sponge plugins:

GriefPrevention 4.3.0.692
KaroglanSignEditor 3.4.1
LuckPerms Sponge 4.4.29
Nucleus 1.14.0 S7.1
project core 7.2.0 0.3.0
project inventories 7.2.0 0.12.2
project portals 7.2.0 0.15.2
project worlds 7.2.0 0.13.1
TimeWarp 2.3 r7.0.0
worldedit sponge 7.1.0–6.1.10 SNAPSHOT

Mods:

Aroma1997Core 1.12.2 2.0.0.2 b165
AromaBackup 1.12.2 3.0.0.0 b129
BetterFps 1.4.8
BiblioCraft 2.4.5
Biomes O’ Plenty 7.0.1.2441
BuildCraft 7.99.24.2
CodeChickenLib 3.2.3.357
foamfix 0.10.5
Forestry 5.8.2.394
IndustrialCraft 2 2.8.187 ex112
ironchest 7.0.59.842
JEI 4.15.0.289
NotEnoughItems 2.4.3.245

**Issue Description**
Players are able to see commands that they do not have permission to use.
This includes mod commands like
/forestry
And some plugin commands like
/timewarp
/luckperms
/brush
(from WorldEdit which produces the error to the player "You are not permitted to do that.")

- maybe these mods have these commands but do not link them to permissions.... WorldEdit is another one... none of my players should have WE permissions, but they are able to use "/sponge:help superpickaxe"  for example.... it doesn't give them a superpickaxe, but it doesn't autocomplete for them

/aroma1997 and /luckperms and /forestry
There are things like that that the players cannot actually use, but they are in the list of available commands regardless.

**Comment by WillBAnders** [comment] 2019-09-09 01:42
Dual and I have both confirmed the proper permission checks are being called on Sponge's side. I took a look at some of the plugins you've mentioned and it's pretty all over the place.

 - LuckPerms: Always [returns true](https://github.com/lucko/LuckPerms/blob/f49446011a63739522fe2d20815613a8322e1d53/sponge/src/main/java/me/lucko/luckperms/sponge/SpongeCommandExecutor.java#L76-L79) on permission checks, needs to be fixed there.
 - WorldEdit: Seems to handle this via [CommandAdapter](https://github.com/EngineHub/WorldEdit/blob/a3ca670a328981d0672f5762e4730c616249926a/worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/CommandAdapter.java); should work?
 - Forestry: Base permission level [is 0](https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/core/commands/RootCommand.java#L91), but...
     - This one should have been handled by Sponge because we add a permission for mod commands. Tracking things through, it looks like [`MinecraftCommandWrapper#testPermission`](https://github.com/SpongePowered/SpongeCommon/blob/e451c700ffc78b9adcdd21b1894d987832fa5c17/src/main/java/org/spongepowered/common/command/MinecraftCommandWrapper.java#L186-L190) uses the permission level rather than the actual permission string. I believe this is a change that needs to be made in Sponge.
 - TimeWarp: Registers children in a parent [without setting a permission](https://github.com/InspireNXE/TimeWarp/blob/master/src/main/java/org/inspirenxe/timewarp/util/Commands.java#L63), needs to be fixed there.
 - Aroma1997: Private source from what I can tell :(, but being a mod probably the same as Forestry.

I'll look into the `MinecraftCommandWrapper` piece and likely open a PR for it. It's also not clear to me why WorldEdit would not be working, but I can explore it more later.

**Comment by JBYoshi** [comment] 2019-10-12 19:46
I think this was fixed by https://github.com/SpongePowered/SpongeCommon/commit/2d60942e3fd6cd3e43461fedf524c4c32df925c5.

**Closed as completed by JBYoshi** 2019-10-12 19:46 UTC
Labels: type: bug, system: command, version: 1.12 (u), status: investigation
