### ISSUE TITLE
Flying mounts in LycanitesMobs stop working when you press the sneak button to go down.

### ISSUE THREAD

**Issue by nikoflame** [SpongePowered/Sponge#3049] opened 2020-07-11 20:34 UTC
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.4-RC4054
- SpongeVanilla version: 
- Java version: 1.12.2
- Operating System: PC

- Plugins/Mods: SpongeForge, LycanitesMobs

**Flying mounts in LycanitesMobs stop working when you press the sneak button to go down. Only happens with SpongeForge installed. Issue can be replicated easily by installing the two mods, summoning a flying mount, putting a saddle on it, and flying it, then trying to go down.**

**Comment by ImMorpheus** [comment] 2020-07-13 19:44
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/3133

**Closed as completed by ImMorpheus** 2020-07-13 19:44 UTC
