### ISSUE TITLE
Calling closeInventory on a workbench 'dupes' the contents back to the player

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#1784] opened 2018-02-09 21:55 UTC
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2890
- SpongeVanilla version: 
- Java version: 1.8
- Operating System: Win10

- Plugins/Mods: 
```
Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, mercurius_updater
```

**Issue Description**

Open workbench, place in recipe.
Have event listening for that recipe, cancel preview event (may not be relavant) and call player.closeinv()
The items in the crafting table will be returned to the player, but they are doubled as the items in the players inv are also set back to the state at which they opened the workbench.

```
    @Listener
    public void craft(CraftItemEvent.Preview event, @First Player player) {
        ItemType type = event.getPreview().getFinal().getType();
        if (type == IRON_HELMET ||
                type == IRON_CHESTPLATE ||
                type == IRON_LEGGINGS ||
                type == IRON_BOOTS ||
                type == GOLDEN_HELMET ||
                type == GOLDEN_CHESTPLATE ||
                type == GOLDEN_LEGGINGS ||
                type == GOLDEN_BOOTS ||
                type == GOLDEN_SWORD ||
                type == DIAMOND_HELMET ||
                type == DIAMOND_CHESTPLATE ||
                type == DIAMOND_LEGGINGS ||
                type == DIAMOND_BOOTS ||
                type == DIAMOND_SWORD
                ) {
            //Check if the player is a gunsmith, if they are not, cancel the event and close down the window
            if(player.get(WinterFellRPKeys.JOB).get() != WinterFellRPKeys.Job.GUNSMITH) {
                event.setCancelled(true);
                //player.closeInventory();//Calling this makes the items dupe :(
                player.sendMessage(Text.of("Only gunsmiths can make this"));
            }
        }

    }
```

**Comment by Faithcaio** [comment] 2018-02-11 09:54
Might have been fixed in one of the latest changes to the events.
Cannot reproduce it ; try again.

**Closed as completed by Faithcaio** 2018-02-11 09:54 UTC
Labels: system: event, system: inventory
