### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/Sponge#259] opened 2015-05-02 15:38 UTC
```prolog
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge-1.8-1371-2.1DEV-436.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 5/2/15 6:34 PM
Description: Exception in server tick loop

java.lang.NullPointerException: color
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.spongepowered.api.text.TextBuilder.color(TextBuilder.java:101)
	at org.spongepowered.api.text.TextBuilder$Translatable.color(TextBuilder.java:696)
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:94)
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400)
	at net.minecraft.server.dedicated.DedicatedServer.func_71228_a(DedicatedServer.java:321)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 454320128 bytes (433 MB) / 692060160 bytes (660 MB) up to 1905262592 bytes (1817 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.76.1397 Minecraft Forge 11.14.1.1397 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{8.0.76.1397} [Forge Mod Loader] (forge-1.8-11.14.1.1397-universal.jar) Unloaded->Constructed->Pre-initialized
	Forge{11.14.1.1397} [Minecraft Forge] (forge-1.8-11.14.1.1397-universal.jar) Unloaded->Constructed->Pre-initialized
	Sponge{} [Sponge] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Loaded coremods (and transformers): 
SpongeCoremod (sponge-1.8-1371-2.1DEV-436.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by simon816** [comment] 2015-05-02 15:40
Some explanation would be useful. What caused this to happen?

**Comment by Minecrell** [comment] 2015-05-02 15:44
This should happen only on the first start when you have not accepted the EULA yet. Set eula to true and it should be fixed the next start. This is caused by SpongePowered/SpongeCommon#6

**Closed by Minecrell** 2015-05-02 15:44 UTC
