### ISSUE TITLE
Request Implimentation: IgniteEntityEvent

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1537] opened 2017-09-23 20:12 UTC
IgniteEntityEvent is one of the events that appears to still not be implimented, and may have just slipped through the cracks unnoticed.

1.12.2 Sponge

**Comment by ImMorpheus** [comment] 2018-01-26 21:10
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/970

This can be closed.

**Closed as completed** 2018-01-26 21:11 UTC
Labels: system: event, version: 1.12 (u), type: impl request
